export const submissions = [
  {
    id: 'J2tv_0zBzFe6jBsYsBX34',
    contestId: 'uw-2024',
    categoryId: 'wide-angle',
    userEmail: 'stefano.cerb@libero.it',
    title: 'Sea Dragon',
    description: '',
    result: 'first',
    firstName: 'Stefano',
    lastName: 'Cerbai',
    fileName: 'sea-dragon.jpg',
  },
  {
    id: 'QfiZp-BDxeWF1VAdtSN3l',
    contestId: 'uw-2024',
    categoryId: 'wide-angle',
    userEmail: 'luc.rooman@telenet.be',
    title: 'Snoek',
    description: '',
    result: 'second',
    firstName: 'Luc',
    lastName: 'Rooman',
    fileName: 'snoek.jpg',
  },
  {
    id: 'i-JTs6jORIXHpy35YqS4r',
    contestId: 'uw-2024',
    categoryId: 'wide-angle',
    userEmail: 'enrico.pati@fabbricamare.it',
    title: 'Il Treno',
    description: '',
    result: 'third',
    firstName: 'Enrico',
    lastName: 'Pati',
    fileName: 'il-treno.jpg',
  },
  {
    id: 'BRwkzj7TtYNiqz54i1COP',
    contestId: 'uw-2024',
    categoryId: 'wide-angle',
    userEmail: 'luc.rooman@telenet.be',
    title: 'Parende Kikkers',
    description: '',
    result: 'runner-up',
    firstName: 'Luc',
    lastName: 'Rooman',
    fileName: 'parende-kikkers.jpg',
  },
  {
    id: 'tlQvfH5DIaxu7YblNuPp6',
    contestId: 'uw-2024',
    categoryId: 'wide-angle',
    userEmail: 'rosario.scariati@gmail.com',
    title: 'Faccia a faccia',
    description: '',
    result: 'runner-up',
    firstName: 'Rosario',
    lastName: 'Scariati',
    fileName: 'face-to-face.jpg',
  },
  {
    id: '5I9m9Il7HH2hK2TeBsjE7',
    contestId: 'uw-2024',
    categoryId: 'wide-angle',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'il Granchio ed il ponte',
    description: '',
    firstName: 'Francesco',
    lastName: 'Visintin',
    result: 'runner-up',
    fileName: 'il-granchio-ed-il-ponte.jpg',
  },
  {
    id: 'cRe2lWpv4A264SYz7101N',
    contestId: 'uw-2024',
    categoryId: 'wide-angle',
    userEmail: 'stefano.cerb@libero.it',
    title: 'Gambero di fiume',
    description: '',
    result: 'runner-up',
    firstName: 'Stefano',
    lastName: 'Cerbai',
    fileName: 'gambero-di-fiume.jpg',
  },
  {
    id: '-ks58wviNjf3uP-mgbQgJ',
    contestId: 'uw-2024',
    categoryId: 'wide-angle',
    userEmail: 'buzzichelli@virgilio.it',
    title: 'Cave',
    description: '',
    result: 'runner-up',
    firstName: 'Alessandro',
    lastName: 'Buzzichelli',
    fileName: 'cave.jpg',
  },
  {
    id: '4dMRuuCbAuReo8aDVU3MS',
    contestId: 'uw-2024',
    categoryId: 'wide-angle',
    userEmail: 'lombrosod@gmail.com',
    title: 'Wide 2',
    description: '',
    result: 'runner-up',
    firstName: 'Davide',
    lastName: 'Lombroso',
    fileName: 'wide-2.jpg',
  },
  {
    id: 'QCO7exLR013iOAmeXGtXF',
    contestId: 'uw-2024',
    categoryId: 'wide-angle',
    userEmail: 'gabriella.luongo@yahoo.it',
    title: 'Night Walk',
    description: '',
    result: 'runner-up',
    firstName: 'Gabriella',
    lastName: 'Luongo',
    fileName: 'night-walk.jpg',
  },
  {
    id: 'M-cI2y_SAsKR_uziqEMVc',
    contestId: 'uw-2024',
    categoryId: 'macro',
    userEmail: 'info@maxgiorgetta.it',
    title: '',
    description: '',
    result: 'first',
    firstName: 'Massimo',
    lastName: 'Giorgetta',
    fileName: 'macro-first.jpg',
  },
  {
    id: 'f0bGy0H79T84CUvQuwypw',
    contestId: 'uw-2024',
    categoryId: 'macro',
    userEmail: 'luc.rooman@telenet.be',
    title: 'Japanse kruiskwal',
    description: '',
    result: 'second',
    firstName: 'Luc',
    lastName: 'Rooman',
    fileName: 'japanse-kruiskwal.jpg',
  },
  {
    id: 'OI7r822HH1G4LzVMRoVoj',
    contestId: 'uw-2024',
    categoryId: 'macro',
    userEmail: 'giancarlo.mazarese@me.com',
    title: '',
    description: '',
    result: 'third',
    firstName: 'Giancarlo',
    lastName: 'Mazarese',
    fileName: 'macro-third.jpg',
  },
  {
    id: 'K3PlZelgc-nwF_FaqE1vY',
    contestId: 'uw-2024',
    categoryId: 'macro',
    userEmail: 'galice.g.hoarau@nord.no',
    title: '',
    description: '',
    result: 'runner-up',
    firstName: 'Galice',
    lastName: 'Hoarau',
    fileName: '2024-macro-runner-up-1.jpg',
  },
  {
    id: '-M_An40J4idR_Ti7d5wva',
    contestId: 'uw-2024',
    categoryId: 'macro',
    userEmail: 'groppo@me.com',
    title: '',
    description: '',
    result: 'runner-up',
    firstName: 'Alberto',
    lastName: 'Groppo',
    fileName: '2024-macro-runner-up-2.jpg',
  },
  {
    id: '_wkqj-04Aq_DYnkWWU-Bz',
    contestId: 'uw-2024',
    categoryId: 'macro',
    userEmail: 'luc.rooman@telenet.be',
    title: 'Salamander',
    description: '',
    result: 'runner-up',
    firstName: 'Luc',
    lastName: 'Rooman',
    fileName: 'salamander.jpg',
  },
  {
    id: 'EL3-Lk33z75J6RZ6ffGsl',
    contestId: 'uw-2024',
    categoryId: 'macro',
    userEmail: 'raffaelelivornese@alice.it',
    title: 'The good father',
    description: '',
    result: 'runner-up',
    firstName: 'Raffaele',
    lastName: 'Livornese',
    fileName: 'the-good-father.jpg',
  },
];
