export interface MigrationSubmission {
  id: string;
  contestId: string;
  categoryId: string;
  userEmail: string;
  title: string;
  description: string;
  result: string;
  firstName: string;
  lastName: string;
  fileName: string;
}

export const submissions: MigrationSubmission[] = [
  {
    id: 'YToOpPSk_NIMgXrj2vFOA',
    contestId: 'uw-2014',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'Capodacqua BW',
    description: '',
    result: 'first',
    firstName: 'Pietro',
    lastName: 'Cremone',
    fileName: 'capodacqua-bw.jpg',
  },
  {
    id: 'UpjmDUoRXVIM_N5v_KOt0',
    contestId: 'uw-2014',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'Bufi',
    description: '',
    result: 'second',
    firstName: 'Pietro',
    lastName: 'Formis',
    fileName: 'bufi.jpg',
  },
  {
    id: 'ehZIp4NbtuMCdRmHSgE0G',
    contestId: 'uw-2014',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'Bubbles',
    description: '',
    result: 'third',
    firstName: 'Matteo',
    lastName: 'Visconti',
    fileName: 'bubbles.jpg',
  },
  {
    id: 'CWWvaWO9IsBygg89FUljc',
    contestId: 'uw-2014',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'Rutilus aula',
    description: '',
    result: 'runner-up',
    firstName: 'Guido',
    lastName: 'Villani',
    fileName: 'rutilus-aula.jpg',
  },
  {
    id: 'VgR7DO-2hdJB-IoURB6lb',
    contestId: 'uw-2014',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'My friend the pike',
    description: '',
    result: 'runner-up',
    firstName: 'Alessio',
    lastName: 'Viora',
    fileName: 'my-friend-the-pike.jpg',
  },
  {
    id: 'ZwCJQ7pSS7h4BzZC5iNbb',
    contestId: 'uw-2014',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'Roots',
    description: '',
    result: 'runner-up',
    firstName: 'Pietro',
    lastName: 'Formis',
    fileName: 'roots.jpg',
  },
  {
    id: 'nLWBNYmmx0cztQ5iUNRCH',
    contestId: 'uw-2014',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'Green Planet',
    description: '',
    result: 'runner-up',
    firstName: 'Matteo',
    lastName: 'Visconti',
    fileName: 'green-planet.jpg',
  },
  {
    id: '_HLyaF9PQVbP02-QbBw_O',
    contestId: 'uw-2014',
    categoryId: 'fresh-waters',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Little river crab',
    description: '',
    result: 'runner-up',
    firstName: 'Francesco',
    lastName: 'Pacienza',
    fileName: 'little-river-crab.jpg',
  },
  {
    id: '0rO3EpD7R5oQVe3tfd_ny',
    contestId: 'uw-2014',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'Mulini sommersi',
    description: '',
    result: 'runner-up',
    firstName: 'Gianni',
    lastName: 'Cicalese',
    fileName: 'mulini-sommersi.jpg',
  },
  {
    id: 'iCi6G9GEE8GzSZQZojO7t',
    contestId: 'uw-2014',
    categoryId: 'fresh-waters',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'The flea',
    description: '',
    result: 'runner-up',
    firstName: 'Francesco',
    lastName: 'Sessa',
    fileName: 'the-flea.jpg',
  },
  {
    id: 'j3CgxU_8Lp1-AjX--DiJ-',
    contestId: 'uw-2014',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Channel barracuda school',
    description: '',
    result: 'first',
    firstName: 'Gianni',
    lastName: 'Cicalese',
    fileName: 'channel-barracuda-school.jpg',
  },
  {
    id: 'iK0z5TgXYMu5Zq4nVVQKo',
    contestId: 'uw-2014',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Fly',
    description: '',
    result: 'second',
    firstName: 'Mario',
    lastName: 'Odorisio',
    fileName: 'fly.jpg',
  },
  {
    id: 'rqVV-f9-rHVsNWVY2lWi3',
    contestId: 'uw-2014',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Face to face',
    description: '',
    result: 'third',
    firstName: 'Davide',
    lastName: 'Lopresti',
    fileName: 'face-to-face.jpg',
  },
  {
    id: 'wOgFgkIVv01j9fZRF5Zwz',
    contestId: 'uw-2014',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'A caccia',
    description: '',
    result: 'runner-up',
    firstName: 'Domenico',
    lastName: 'Roscigno',
    fileName: 'a-caccia.jpg',
  },
  {
    id: 'fuf3zwwHeXr-vxCC2_MWL',
    contestId: 'uw-2014',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Denti aguzzi',
    description: '',
    result: 'runner-up',
    firstName: 'Alessio',
    lastName: 'Viora',
    fileName: 'denti-aguzzi.jpg',
  },
  {
    id: 'DkdzHIYIetzQMzVldezTr',
    contestId: 'uw-2014',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'A bocca aperta',
    description: '',
    result: 'runner-up',
    firstName: 'Alberto',
    lastName: 'Gallucci',
    fileName: 'a-bocca-aperta.jpg',
  },
  {
    id: 'Zpbd1sxB4x0-hJnboXB6b',
    contestId: 'uw-2014',
    categoryId: 'wide-angle',
    userEmail: 'info@gmphotosub.com',
    title: 'Grande bocca',
    description: '',
    result: 'runner-up',
    firstName: 'Giacomo',
    lastName: 'Marchione',
    fileName: 'grande-bocca.jpg',
  },
  {
    id: 'hdv5xnBKj6el1ft_DpxMT',
    contestId: 'uw-2014',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Patrolling',
    description: '',
    result: 'runner-up',
    firstName: 'Beth',
    lastName: 'Watson',
    fileName: 'patrolling.jpg',
  },
  {
    id: 'uRr7AqRkeNSnYQ75Kn21z',
    contestId: 'uw-2014',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Rise and shine',
    description: '',
    result: 'runner-up',
    firstName: 'Beth',
    lastName: 'Watson',
    fileName: 'rise-and-shine.jpg',
  },
  {
    id: 'hvNF9rP9hTpfBTuqXt6Hr',
    contestId: 'uw-2014',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'My blue',
    description: '',
    result: 'runner-up',
    firstName: 'David',
    lastName: 'Mocholi',
    fileName: 'my-blue.jpg',
  },
  {
    id: 'cJ5b1jai35ORhX9Dngw4A',
    contestId: 'uw-2014',
    categoryId: 'macro',
    userEmail: '',
    title: 'Those eyes',
    description: '',
    result: 'first',
    firstName: 'Beth',
    lastName: 'Watson',
    fileName: 'those-eyes.jpg',
  },
  {
    id: 'VYiTAX-LB706bMn5CyREr',
    contestId: 'uw-2014',
    categoryId: 'macro',
    userEmail: '',
    title: 'Faccia a faccia',
    description: '',
    result: 'second',
    firstName: 'Marco',
    lastName: 'Caraceni',
    fileName: 'faccia-a-faccia.jpg',
  },
  {
    id: 'fUiD2xT0pedo4jt2uwPgt',
    contestId: 'uw-2014',
    categoryId: 'macro',
    userEmail: 'pbau63@libero.it',
    title: 'Scream',
    description: '',
    result: 'third',
    firstName: 'Paolo',
    lastName: 'Bausani',
    fileName: 'scream.jpg',
  },
  {
    id: 'pdDrTw1yRfylnf-5EGeAP',
    contestId: 'uw-2014',
    categoryId: 'macro',
    userEmail: 'info@gmphotosub.com',
    title: 'Merletti',
    description: '',
    result: 'runner-up',
    firstName: 'Giacomo',
    lastName: 'Marchione',
    fileName: 'merletti.jpg',
  },
  {
    id: 'cx_BRhHyWW5WytCXv5dEm',
    contestId: 'uw-2014',
    categoryId: 'macro',
    userEmail: 'varafolo1971@coffeejeans.com.ua',
    title: 'Sheep eat grass',
    description: '',
    result: 'runner-up',
    firstName: 'Lynn',
    lastName: 'Wu',
    fileName: 'sheep-eat-grass.jpg',
  },
  {
    id: 'Vf8sv9wx3JQ737GfRFW6Q',
    contestId: 'uw-2014',
    categoryId: 'macro',
    userEmail: '',
    title: 'Like a bird',
    description: '',
    result: 'runner-up',
    firstName: 'Jordi',
    lastName: 'Riba',
    fileName: 'like-a-bird.jpg',
  },
  {
    id: 'jfDUSFgPb47wzpPPZSj4e',
    contestId: 'uw-2014',
    categoryId: 'macro',
    userEmail: '',
    title: 'Shy gobi',
    description: '',
    result: 'runner-up',
    firstName: 'Jordi',
    lastName: 'Riba',
    fileName: 'shy-gobi.jpg',
  },
  {
    id: 'QpNL5pGvhLN9dZiFufl2_',
    contestId: 'uw-2014',
    categoryId: 'macro',
    userEmail: '',
    title: 'Little beauty',
    description: '',
    result: 'runner-up',
    firstName: 'Raimundo',
    lastName: 'Fernandez Diez',
    fileName: 'little-beauty.jpg',
  },
  {
    id: 'u6afNdQjcxk74TRI43XIK',
    contestId: 'uw-2014',
    categoryId: 'macro',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Elegant Feathers',
    description: '',
    result: 'runner-up',
    firstName: 'Francesco',
    lastName: 'Pacienza',
    fileName: 'elegant-feathers.jpg',
  },
  {
    id: 'pJPhSj2vqQx6q7hsq5FY2',
    contestId: 'uw-2014',
    categoryId: 'macro',
    userEmail: 'nicholas.samaras@me.com',
    title: 'Fly high and smile',
    description: '',
    result: 'runner-up',
    firstName: 'Nicholas',
    lastName: 'Samaras',
    fileName: 'fly-high-and-smile.jpg',
  },
  {
    id: 'sF-mg8LQ7xA9uiFYyN5Y2',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Cima viva',
    description: '',
    result: 'first',
    firstName: 'Domenico',
    lastName: 'Roscigno',
    fileName: 'cima-viva.jpg',
  },
  {
    id: 'KbWJVbr1xs_mHZBgN8Z4Z',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Edo e spugna',
    description: '',
    result: 'first',
    firstName: 'Domenico',
    lastName: 'Roscigno',
    fileName: 'edo-e-spugna.jpg',
  },
  {
    id: 'SOMds3iAPeu5ihiodgqee',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Hidden',
    description: '',
    result: 'first',
    firstName: 'Domenico',
    lastName: 'Roscigno',
    fileName: 'hidden.jpg',
  },
  {
    id: 'OKrXDdOYJ_-zy-F0UvCPr',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: 'nicholas.samaras@me.com',
    title: 'These eyes',
    description: '',
    result: 'second',
    firstName: 'Nicholas',
    lastName: 'Samaras',
    fileName: 'these-eyes.jpg',
  },
  {
    id: 'adCUqS9nV8FRdu8SH_7CY',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: 'nicholas.samaras@me.com',
    title: 'Spaceship',
    description: '',
    result: 'second',
    firstName: 'Nicholas',
    lastName: 'Samaras',
    fileName: 'spaceship.jpg',
  },
  {
    id: 'fD8g5y7VWSeVlqtR3blLh',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: 'nicholas.samaras@me.com',
    title: 'Swimming in the sunset',
    description: '',
    result: 'second',
    firstName: 'Nicholas',
    lastName: 'Samaras',
    fileName: 'swimming-in-the-sunset.jpg',
  },
  {
    id: 'o9sMs7dDF0Oj-ti-l7wkX',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Cothyloriza dream',
    description: '',
    result: 'third',
    firstName: 'Adriano',
    lastName: 'Morettin',
    fileName: 'cothyloriza-dream.jpg',
  },
  {
    id: 'VZkAORX5chUvOT4uWeq8T',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Tubeworms Tree',
    description: '',
    result: 'third',
    firstName: 'Adriano',
    lastName: 'Morettin',
    fileName: 'tubeworms-tree.jpg',
  },
  {
    id: 'k3cXltm-_mkEfhLXYpJAZ',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'On stage',
    description: '',
    result: 'third',
    firstName: 'Adriano',
    lastName: 'Morettin',
    fileName: 'on-stage.jpg',
  },
  {
    id: 'invRhhcrVKpsaDfb2CtRY',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Life is 1',
    description: '',
    result: 'runner-up',
    firstName: 'Elio',
    lastName: 'Nicosia',
    fileName: 'life-is-1.jpg',
  },
  {
    id: '6g5KWQF4IRfmgCJbP2BE1',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Life is 2',
    description: '',
    result: 'runner-up',
    firstName: 'Elio',
    lastName: 'Nicosia',
    fileName: 'life-is-2.jpg',
  },
  {
    id: 'pyzWXsaFBpWZQfwLw1ME3',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Life is 3',
    description: '',
    result: 'runner-up',
    firstName: 'Elio',
    lastName: 'Nicosia',
    fileName: 'life-is-3.jpg',
  },
  {
    id: 'PT5HcOWjDnalf7gye0siW',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: 'margar68@gmail.com',
    title: 'Grotta',
    description: '',
    result: 'runner-up',
    firstName: 'Marco',
    lastName: 'Gargiulo',
    fileName: 'grotta.jpg',
  },
  {
    id: 'QOmud8le_1PzzX14YT0vo',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: 'margar68@gmail.com',
    title: 'In volo',
    description: '',
    result: 'runner-up',
    firstName: 'Marco',
    lastName: 'Gargiulo',
    fileName: 'in-volo.jpg',
  },
  {
    id: 'Py0Bj6w7I_Tn_H38GMR8-',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: 'margar68@gmail.com',
    title: 'The circle',
    description: '',
    result: 'runner-up',
    firstName: 'Marco',
    lastName: 'Gargiulo',
    fileName: 'the-circle.jpg',
  },
  {
    id: 'Xjz29KG6ev2Ytn1v7h-aa',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Resting in a cloud',
    description: '',
    result: 'runner-up',
    firstName: 'Jordi',
    lastName: 'Riba',
    fileName: 'resting-in-a-cloud.jpg',
  },
  {
    id: 'IvDhMwLuXCQq-hoGfgbrV',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Underwater world',
    description: '',
    result: 'runner-up',
    firstName: 'Jordi',
    lastName: 'Riba',
    fileName: 'underwater-world.jpg',
  },
  {
    id: 'nXERi7Re96osrQ06QA41F',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Equilibrist',
    description: '',
    result: 'runner-up',
    firstName: 'Jordi',
    lastName: 'Riba',
    fileName: 'equilibrist.jpg',
  },
  {
    id: 'zHINuY1NGeIe8-2oIT89q',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'La gorgone',
    description: '',
    result: 'runner-up',
    firstName: 'Filippo',
    lastName: 'Borghi',
    fileName: 'la-gorgone.jpg',
  },
  {
    id: 'fi6VQ2Ee9ThDFNmz8I3na',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'La pescatrice',
    description: '',
    result: 'runner-up',
    firstName: 'Filippo',
    lastName: 'Borghi',
    fileName: 'la-pescatrice.jpg',
  },
  {
    id: 'h6fkkI2qo0ghiikxkbt2P',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: "Sotto l'ombrello",
    description: '',
    result: 'runner-up',
    firstName: 'Filippo',
    lastName: 'Borghi',
    fileName: 'sotto-lombrello.jpg',
  },
  {
    id: '5t0eTmCy0fKYvOGFAriUL',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Umbrella',
    description: '',
    result: 'runner-up',
    firstName: 'David',
    lastName: 'Mocholi',
    fileName: 'umbrella.jpg',
  },
  {
    id: 'D0PYlq1PbT_UOo7U-oC0P',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Blue neon',
    description: '',
    result: 'runner-up',
    firstName: 'David',
    lastName: 'Mocholi',
    fileName: 'blue-neon.jpg',
  },
  {
    id: 'UuMqKlhD25ye2ltncJB3F',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'The cave',
    description: '',
    result: 'runner-up',
    firstName: 'David',
    lastName: 'Mocholi',
    fileName: 'the-cave.jpg',
  },
  {
    id: 'evww3qRjAdt1uNGhSA_sG',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Trapanie lineate in rosa',
    description: '',
    result: 'runner-up',
    firstName: 'Virginia',
    lastName: 'Salzedo',
    fileName: 'trapanie-lineate-in-rosa.jpg',
  },
  {
    id: 'hyrARIu9J9qonNgybkZE4',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Daddy',
    description: '',
    result: 'runner-up',
    firstName: 'Virginia',
    lastName: 'Salzedo',
    fileName: 'daddy.jpg',
  },
  {
    id: 'T29PnXwI2s73-xwu1wuxP',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Tina mon amour',
    description: '',
    result: 'runner-up',
    firstName: 'Virginia',
    lastName: 'Salzedo',
    fileName: 'tina-mon-amour.jpg',
  },
  {
    id: '48smQ2GN8BZegqQyDwunf',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Lady viola',
    description: '',
    result: 'runner-up',
    firstName: 'David',
    lastName: 'Mocholi',
    fileName: 'lady-viola.jpg',
  },
  {
    id: '5UAVTjRzsxG6wOcz0CDj-',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Luci dello stretto',
    description: '',
    result: 'runner-up',
    firstName: 'Francesco',
    lastName: 'Sesso',
    fileName: 'luci-dello-stretto.jpg',
  },
  {
    id: 'uMj0GooHr0-b8zzhn_m9-',
    contestId: 'uw-2014',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Tina',
    description: '',
    result: 'runner-up',
    firstName: 'David',
    lastName: 'Mocholi',
    fileName: 'tina.jpg',
  },
  {
    id: 'K68CQgDwEsPm1QzMC7Va1',
    contestId: 'uw-2014',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Trasparenze',
    description: '',
    result: 'first',
    firstName: 'Mario',
    lastName: 'Bonelli',
    fileName: 'trasparenze.jpg',
  },
  {
    id: 'SYzvS1vbpPK6FSZsGyMYD',
    contestId: 'uw-2014',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Che bel sorriso',
    description: '',
    result: 'second',
    firstName: 'Filippo',
    lastName: 'Ioni',
    fileName: 'che-bel-sorriso.jpg',
  },
  {
    id: 'aAvFMCfdMjVMUdIhMCIbk',
    contestId: 'uw-2014',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Fashion night',
    description: '',
    result: 'third',
    firstName: 'Adriano',
    lastName: 'Di Nocera',
    fileName: 'fashion-night.jpg',
  },
  {
    id: 'jFHCQHddXlsGPc0BuMHBI',
    contestId: 'uw-2014',
    categoryId: 'newcomers',
    userEmail: '',
    title: '',
    description: '',
    result: 'runner-up',
    firstName: 'Marco',
    lastName: 'Faimali- Coral Abstract',
    fileName: 'image-64.jpg',
  },
  {
    id: '8FJG04q40pnkNaUYRWTu_',
    contestId: 'uw-2014',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Il vezzo del cavalluccio',
    description: '',
    result: 'runner-up',
    firstName: 'Roberto',
    lastName: 'Strafella',
    fileName: 'il-vezzo-del-cavalluccio.jpg',
  },
  {
    id: '0f2zDha48528XgHDiD3rm',
    contestId: 'uw-2014',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Melibe',
    description: '',
    result: 'runner-up',
    firstName: 'Domenico',
    lastName: 'Maiorano',
    fileName: 'melibe.jpg',
  },
  {
    id: 'LNF4dM578EQNbdGjpQ7nL',
    contestId: 'uw-2014',
    categoryId: 'newcomers',
    userEmail: 'giancarlo.mazarese@me.com',
    title: 'Le gemelle',
    description: '',
    result: 'runner-up',
    firstName: 'Giancarlo',
    lastName: 'Zambelli',
    fileName: 'le-gemelle.jpg',
  },
  {
    id: 'QNJiN62jWYJ3lEcpZhyI0',
    contestId: 'uw-2014',
    categoryId: 'newcomers',
    userEmail: 'pdececco@yahoo.it',
    title: 'Occhio squilla (cicala)',
    description: '',
    result: 'runner-up',
    firstName: 'Pier',
    lastName: 'Domenico Donato',
    fileName: 'occhio-squilla-cicala.jpg',
  },
  {
    id: 'HUhd1HsqdBJO-Qyw0ynX1',
    contestId: 'uw-2014',
    categoryId: 'newcomers',
    userEmail: 'mauapule@tin.it',
    title: 'Hippy',
    description: '',
    result: 'runner-up',
    firstName: 'Mauro',
    lastName: 'Di Lecce',
    fileName: 'hippy.jpg',
  },
  {
    id: 'O6_tm-pgf2k1R82b-wanW',
    contestId: 'uw-2014',
    categoryId: 'the-professions-of-the-sea',
    userEmail: '',
    title: 'Sistemazione delle reti',
    description: '',
    result: 'first',
    firstName: 'Aldo',
    lastName: 'Costa',
    fileName: 'sistemazione-delle-reti.jpg',
  },
  {
    id: '4JxzrfaBFoB6uuoknLk3E',
    contestId: 'uw-2014',
    categoryId: 'the-professions-of-the-sea',
    userEmail: '',
    title: 'The human shadow on the sea',
    description: '',
    result: 'second',
    firstName: 'Marco',
    lastName: 'Faimali',
    fileName: 'the-human-shadow-on-the-sea.jpg',
  },
  {
    id: 'HSQ8FD3dSsRFeamvfeADJ',
    contestId: 'uw-2014',
    categoryId: 'the-professions-of-the-sea',
    userEmail: '',
    title: 'Raccolta delle alghe al tramonto',
    description: '',
    result: 'third',
    firstName: 'Gianni',
    lastName: 'Cicalese',
    fileName: 'raccolta-delle-alghe-al-tramonto.jpg',
  },
  {
    id: 'HjSUsEOPHBBDqp0F6ReTp',
    contestId: 'uw-2014',
    categoryId: 'the-professions-of-the-sea',
    userEmail: '',
    title: "L'alba dei pescatori",
    description: '',
    result: 'runner-up',
    firstName: 'Aldo',
    lastName: 'Costa',
    fileName: 'lalba-dei-pescatori.jpg',
  },
  {
    id: 'Y8-cHNQMUnr-B0gAu9yDu',
    contestId: 'uw-2014',
    categoryId: 'the-professions-of-the-sea',
    userEmail: '',
    title: 'La raccolta',
    description: '',
    result: 'runner-up',
    firstName: 'Alessio',
    lastName: 'Viora',
    fileName: 'la-raccolta.jpg',
  },
  {
    id: '-mO7rSpq7AovJbMj1Etkq',
    contestId: 'uw-2014',
    categoryId: 'the-professions-of-the-sea',
    userEmail: '',
    title: 'Mattanza',
    description: '',
    result: 'runner-up',
    firstName: 'Alessio',
    lastName: 'Viora',
    fileName: 'mattanza.jpg',
  },
  {
    id: 'dNJEcdnxt-oGv3sB9JE5w',
    contestId: 'uw-2014',
    categoryId: 'the-professions-of-the-sea',
    userEmail: '',
    title: 'Tonnarolo',
    description: '',
    result: 'runner-up',
    firstName: 'Pietro',
    lastName: 'Formis',
    fileName: 'tonnarolo.jpg',
  },
  {
    id: 'TSAuDkSpRM0ii4-KMVTMT',
    contestId: 'uw-2014',
    categoryId: 'the-professions-of-the-sea',
    userEmail: '',
    title: "Pescatori tongani all'alba",
    description: '',
    result: 'runner-up',
    firstName: 'Andrea',
    lastName: 'Izzotti',
    fileName: 'pescatori-tongani-allalba.jpg',
  },
  {
    id: 'Z6ZiPyeSNbkDnUyCxieAo',
    contestId: 'uw-2014',
    categoryId: 'the-professions-of-the-sea',
    userEmail: '',
    title: 'Fishing still works',
    description: '',
    result: 'runner-up',
    firstName: 'Jordi',
    lastName: 'Riba',
    fileName: 'fishing-still-works.jpg',
  },
  {
    id: 'ubjCwSEzAov98K8cOlC84',
    contestId: 'uw-2014',
    categoryId: 'the-professions-of-the-sea',
    userEmail: '',
    title: 'Lavori quotidiani',
    description: '',
    result: 'runner-up',
    firstName: 'Gianni',
    lastName: 'Cicalese',
    fileName: 'lavori-quotidiani.jpg',
  },
];
