export interface MigrationSubmission {
  id: string;
  contestId: string;
  categoryId: string;
  userEmail: string;
  title: string;
  description: string;
  result: string;
  firstName: string;
  lastName: string;
  fileName: string;
}

export const submissions: MigrationSubmission[] = [
  {
    id: 'PMpRCgfg8vcrNY_-jcYM5',
    contestId: 'uw-2013',
    categoryId: 'art-in-the-water',
    userEmail: '',
    title: 'Giro',
    description: '',
    result: 'first',
    firstName: 'FERNANDEZ',
    lastName: 'SERGI GARCIA',
    fileName: 'giro.jpg',
  },
  {
    id: 'up1Fsmm2prLM0R13Dw2VS',
    contestId: 'uw-2013',
    categoryId: 'art-in-the-water',
    userEmail: '',
    title: 'Primavera',
    description: '',
    result: 'second',
    firstName: 'MARCO',
    lastName: 'CARACENI',
    fileName: 'primavera.jpg',
  },
  {
    id: 'k1zrV3ftlf1WsxybtCNio',
    contestId: 'uw-2013',
    categoryId: 'art-in-the-water',
    userEmail: '',
    title: 'Pianeta acqua',
    description: '',
    result: 'third',
    firstName: 'RAIMUNDO',
    lastName: 'FERNANDEZ DIAZ',
    fileName: 'pianeta-acqua.jpg',
  },
  {
    id: 'CZYYVAurKkC1m8RVDbd-1',
    contestId: 'uw-2013',
    categoryId: 'art-in-the-water',
    userEmail: '',
    title: 'Lacrime di luce',
    description: '',
    result: 'runner-up',
    firstName: 'GIORDANO',
    lastName: 'CIPRIANI',
    fileName: 'lacrime-di-luce.jpg',
  },
  {
    id: 'ENMtec3oyC4a4uBBvKg-8',
    contestId: 'uw-2013',
    categoryId: 'art-in-the-water',
    userEmail: '',
    title: 'Allo specchio',
    description: '',
    result: 'runner-up',
    firstName: 'TIZIANA',
    lastName: 'DELLA ZANNA',
    fileName: 'allo-specchio.jpg',
  },
  {
    id: 'phEe_6fJJTSAgF-_CXZ5Y',
    contestId: 'uw-2013',
    categoryId: 'special-mention',
    userEmail: 'pignatarog65@gmail.com',
    title: 'Angelic',
    description: '',
    result: 'first',
    firstName: 'GIUSEPPE',
    lastName: 'PICCCIOLI RESTA',
    fileName: 'angelic.jpg',
  },
  {
    id: 'gulNSQBEkXpcpZdKmlsu3',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: 'pignatarog65@gmail.com',
    title: 'Iridescenze',
    description: '',
    result: 'first',
    firstName: 'GIUSEPPE',
    lastName: 'PICCOLI RESTA',
    fileName: 'iridescenze.jpg',
  },
  {
    id: '4w6IwARftRNqm3Fs2jasH',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: 'luc.rooman@telenet.be',
    title: 'Plantvis',
    description: '',
    result: 'second',
    firstName: 'LUC',
    lastName: 'ROOMAN',
    fileName: 'plantvis.jpg',
  },
  {
    id: 'zVmuDcE5rQnObSEVYdSbz',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: '',
    title: 'The dentist',
    description: '',
    result: 'third',
    firstName: 'DAVIDE',
    lastName: 'LOPRESTI',
    fileName: 'the-dentist.jpg',
  },
  {
    id: '-2iipIrh_bdwE3UQblFjs',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: 'pbau63@libero.it',
    title: 'In punta di pinne',
    description: '',
    result: 'runner-up',
    firstName: 'PAOLO',
    lastName: 'BAUSANI',
    fileName: 'in-punta-di-pinne.jpg',
  },
  {
    id: '71123iAvXGgWkhCJ7gn3N',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: '',
    title: 'Goby's',
    description: '',
    result: 'runner-up',
    firstName: 'FILIPPO',
    lastName: 'BORGHI',
    fileName: 'gobys.jpg',
  },
  {
    id: 'p3fTwd2YoyOKcGgGmnjUX',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: 'pignatarog65@gmail.com',
    title: 'Panzona',
    description: '',
    result: 'runner-up',
    firstName: 'GIUSEPPE',
    lastName: 'PICCOLI RESTA',
    fileName: 'panzona.jpg',
  },
  {
    id: 'ndIiHRL1wbd1jfFV5-Ek6',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: '',
    title: 'Frog fish',
    description: '',
    result: 'runner-up',
    firstName: 'MATTEO',
    lastName: 'VISCONTI',
    fileName: 'frog-fish.jpg',
  },
  {
    id: 'R5VoW1B5cOxAy9b9SXRGI',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: '',
    title: 'Pigmy',
    description: '',
    result: 'runner-up',
    firstName: 'PIETRO',
    lastName: 'FORMIS',
    fileName: 'pigmy.jpg',
  },
  {
    id: 'iQ6ZvkByUVN8Ioeypk-0V',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: '',
    title: 'Nuova generazione',
    description: '',
    result: 'runner-up',
    firstName: 'DAVIDE',
    lastName: 'LOPRESTI',
    fileName: 'nuova-generazione.jpg',
  },
  {
    id: '5wtlVYqo4dl5wKWqTtYkS',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: '',
    title: 'La strana coppia',
    description: '',
    result: 'runner-up',
    firstName: 'ADRIANO',
    lastName: 'MORETTIN',
    fileName: 'la-strana-coppia.jpg',
  },
  {
    id: '7g8Q-fz55QeZkaKkMmd9Q',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Blue shark',
    description: '',
    result: 'first',
    firstName: 'FILIPPO',
    lastName: 'BORGHI',
    fileName: 'blue-shark.jpg',
  },
  {
    id: 'sf-Oikzh6TpaedWl0SWfF',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Incontri ravvicinati',
    description: '',
    result: 'second',
    firstName: 'DOMENICO',
    lastName: 'ROSCIGNO',
    fileName: 'incontri-ravvicinati.jpg',
  },
  {
    id: 'utz8HapC54XFnmhJ3CyhY',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Afternoon',
    description: '',
    result: 'third',
    firstName: 'FERNANDEZ',
    lastName: 'SERGI GARCIA',
    fileName: 'afternoon.jpg',
  },
  {
    id: '5Nh9nXLzsSi-WcZs7_UPf',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Cerchio della vita',
    description: '',
    result: 'runner-up',
    firstName: 'ISABELLA',
    lastName: 'MAFFEI',
    fileName: 'cerchio-della-vita.jpg',
  },
  {
    id: 'U-Q1U0IbDebHGXuO1sM8Y',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Iguana',
    description: '',
    result: 'runner-up',
    firstName: 'FILIPPO',
    lastName: 'BORGHI',
    fileName: 'iguana.jpg',
  },
  {
    id: 'n8ndKjCAzrzc7kUQemYEq',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Fallen in the sky',
    description: '',
    result: 'runner-up',
    firstName: 'MONTSE',
    lastName: 'GRILLO',
    fileName: 'fallen-in-the-sky.jpg',
  },
  {
    id: 'Zusmh1YtYmVNb5FcLRxom',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Predator',
    description: '',
    result: 'runner-up',
    firstName: 'MARCELLO',
    lastName: 'DI FRANCESCO',
    fileName: 'predator.jpg',
  },
  {
    id: 'dPCci8pKpHidOJMwQepJb',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Connessione',
    description: '',
    result: 'runner-up',
    firstName: 'ISABELLA',
    lastName: 'MAFFEI',
    fileName: 'connessione.jpg',
  },
  {
    id: '-dd887Vw1Hw8QGX538mzB',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'La medusa e le sue ancelle',
    description: '',
    result: 'runner-up',
    firstName: 'ALBERTO',
    lastName: 'GALLUCCI',
    fileName: 'la-medusa-e-le-sue-ancelle.jpg',
  },
  {
    id: 'tJPLEtCiF4dYRWtkxSbKT',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: '',
    description: '',
    result: 'first',
    firstName: 'ROSANNA',
    lastName: 'BONATI- Cardinal Crossing',
    fileName: 'image-26.jpg',
  },
  {
    id: '1F956js3mdpxbDDYfC_yc',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Giochi di luce',
    description: '',
    result: 'second',
    firstName: 'FRANCESCO',
    lastName: 'BAZZOTTI',
    fileName: 'giochi-di-luce.jpg',
  },
  {
    id: 'QZKIt6T3_LX3Gjns3C-hx',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Nido d'amore',
    description: '',
    result: 'third',
    firstName: 'FILIPPO',
    lastName: 'IONI',
    fileName: 'nido-damore.jpg',
  },
  {
    id: 'QC3ImBVn57j4IPBe6t22D',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Granchietto',
    description: '',
    result: 'runner-up',
    firstName: 'NADIA',
    lastName: 'DE SANTIS',
    fileName: 'granchietto.jpg',
  },
  {
    id: 'umfScLHnJ8phqwHPscV3D',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Proud mama',
    description: '',
    result: 'runner-up',
    firstName: 'ROSANNA',
    lastName: 'BONATI',
    fileName: 'proud-mama.jpg',
  },
  {
    id: 'FL4FLyRhYM7-asKs9ti4Z',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Cavalluccio rosso',
    description: '',
    result: 'runner-up',
    firstName: 'GIANNI',
    lastName: 'COLUCCI',
    fileName: 'cavalluccio-rosso.jpg',
  },
  {
    id: 'QhyL-ZJKJg6HFQhwV7duo',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Terminator',
    description: '',
    result: 'runner-up',
    firstName: 'MARCO',
    lastName: 'FANTIN',
    fileName: 'terminator.jpg',
  },
  {
    id: '6Wt_7wrj0bt7YdH1Mp6RH',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Nuove generazioni',
    description: '',
    result: 'runner-up',
    firstName: 'PAOLO',
    lastName: 'FONTANELLA',
    fileName: 'nuove-generazioni.jpg',
  },
  {
    id: 'PH7qzTWzDvaC0EJKesYt5',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Twist',
    description: '',
    result: 'runner-up',
    firstName: 'FLAVIO',
    lastName: 'VAILATI',
    fileName: 'twist.jpg',
  },
  {
    id: 'us-68mycwVu-vfRkAFej6',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Apollo 13',
    description: '',
    result: 'runner-up',
    firstName: 'MARCO',
    lastName: 'FANTINO',
    fileName: 'apollo-13.jpg',
  },
  {
    id: 'BqO_9WSUA4_b3QiKO_p3j',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'The monster,...',
    description: '',
    result: 'first',
    firstName: 'MARC',
    lastName: 'FELIX CASANOVAS',
    fileName: 'the-monster.jpg',
  },
  {
    id: 'DhQZ8smumk_Ka0QfDvVrd',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Zeus',
    description: '',
    result: 'first',
    firstName: 'MARC',
    lastName: 'FELIX CASANOVAS',
    fileName: 'zeus.jpg',
  },
  {
    id: 'fuBZ4CP0KP9GP98pMO6-_',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Hippocampus',
    description: '',
    result: 'first',
    firstName: 'MARC',
    lastName: 'FELIX CASANOVAS',
    fileName: 'hippocampus.jpg',
  },
  {
    id: 'TEwFUnu08nN8aTNfiT27Q',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Cova de la vaca,...',
    description: '',
    result: 'second',
    firstName: 'PIETRO',
    lastName: 'FORMIS',
    fileName: 'cova-de-la-vaca.jpg',
  },
  {
    id: '6g9hhwWVqG6a-BRSW8sL2',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Apogon',
    description: '',
    result: 'second',
    firstName: 'PIETRO',
    lastName: 'FORMIS',
    fileName: 'apogon.jpg',
  },
  {
    id: '-koBHPUgHEHmglxvJLOh8',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Spada',
    description: '',
    result: 'second',
    firstName: 'PIETRO',
    lastName: 'FORMIS',
    fileName: 'spada.jpg',
  },
  {
    id: 'Q5dntF6h5_Z5kBDX4I9UL',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Deep hunting,...',
    description: '',
    result: 'third',
    firstName: 'MAURIZIO',
    lastName: 'PASI',
    fileName: 'deep-hunting.jpg',
  },
  {
    id: 'B3WjI9PNOwWgbVMdG-QKI',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Firework',
    description: '',
    result: 'third',
    firstName: 'MAURIZIO',
    lastName: 'PASI',
    fileName: 'firework.jpg',
  },
  {
    id: 'QbVNJYciWzMTL6QyRGNWe',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Twins',
    description: '',
    result: 'third',
    firstName: 'MAURIZIO',
    lastName: 'PASI',
    fileName: 'twins.jpg',
  },
  {
    id: 'noL4vK1cgO6aXr9LXUDhf',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Friedegg',
    description: '',
    result: 'runner-up',
    firstName: 'DAVID',
    lastName: 'ANTOJA MAS',
    fileName: 'friedegg.jpg',
  },
  {
    id: 'gjefqYbYH0GXyn4iTIhWN',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Janolus',
    description: '',
    result: 'runner-up',
    firstName: 'DAVID',
    lastName: 'ANTOJA MAS',
    fileName: 'janolus.jpg',
  },
  {
    id: '4LcWrJpg4LQqdRAxnWtGO',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Zeusfaber',
    description: '',
    result: 'runner-up',
    firstName: 'DAVID',
    lastName: 'ANTOJA MAS',
    fileName: 'zeusfaber.jpg',
  },
  {
    id: '6CP0hInp09rx2DKb199fZ',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Cassiopea',
    description: '',
    result: 'runner-up',
    firstName: 'DOMENICO',
    lastName: 'ROSCIGNO',
    fileName: 'cassiopea.jpg',
  },
  {
    id: 'RQGrmMKv9TN4C-Ljmxjxz',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'San Pietro',
    description: '',
    result: 'runner-up',
    firstName: 'DOMENICO',
    lastName: 'ROSCIGNO',
    fileName: 'san-pietro.jpg',
  },
  {
    id: 'OVuTWCJiB6OvdqPOje9L5',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Spirografi',
    description: '',
    result: 'runner-up',
    firstName: 'DOMENICO',
    lastName: 'ROSCIGNO',
    fileName: 'spirografi.jpg',
  },
  {
    id: 'AIzhWjW1iNdwNqz0Yfu6_',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Cothyloriza',
    description: '',
    result: 'runner-up',
    firstName: 'ADRIANO',
    lastName: 'MORETTIN',
    fileName: 'cothyloriza.jpg',
  },
  {
    id: '4YxzvJF7PvNidRh5NgAlA',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Protula',
    description: '',
    result: 'runner-up',
    firstName: 'ADRIANO',
    lastName: 'MORETTIN',
    fileName: 'protula.jpg',
  },
  {
    id: 'C4sVtncI6RvMSPx1mkM8M',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Rhyzostoma',
    description: '',
    result: 'runner-up',
    firstName: 'ADRIANO',
    lastName: 'MORETTIN',
    fileName: 'rhyzostoma.jpg',
  },
  {
    id: 'vKbYChbPX8JoADhMbgDsY',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: 'sadilauro@live.it',
    title: 'In attesa',
    description: '',
    result: 'runner-up',
    firstName: 'SALVATORE',
    lastName: 'IANNIELLO',
    fileName: 'in-attesa.jpg',
  },
  {
    id: 'GI3CECb4_E0iBaG5a8O_U',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: 'sadilauro@live.it',
    title: 'Testa e coda',
    description: '',
    result: 'runner-up',
    firstName: 'SALVATORE',
    lastName: 'IANNIELLO',
    fileName: 'testa-e-coda.jpg',
  },
  {
    id: 'CK2s8s_KbNY_iJsGUx9m6',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: 'sadilauro@live.it',
    title: 'Viaggio meraviglioso',
    description: '',
    result: 'runner-up',
    firstName: 'SALVATORE',
    lastName: 'IANNIELLO',
    fileName: 'viaggio-meraviglioso.jpg',
  },
  {
    id: 'r-zy9c-2DBAGALZCd0iam',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Esplode la vita',
    description: '',
    result: 'runner-up',
    firstName: 'ALBERTO',
    lastName: 'GALLUCCI',
    fileName: 'esplode-la-vita.jpg',
  },
  {
    id: '2z6BmNzHQNK6eRWGVrqmi',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Pesce balestra',
    description: '',
    result: 'runner-up',
    firstName: 'ALBERTO',
    lastName: 'GALLUCCI',
    fileName: 'pesce-balestra.jpg',
  },
  {
    id: 'o4yfGtGB_2AJV-DkC5vrU',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Serpula vermicularis',
    description: '',
    result: 'runner-up',
    firstName: 'ALBERTO',
    lastName: 'GALLUCCI',
    fileName: 'serpula-vermicularis.jpg',
  },
  {
    id: 'EYH0YSb_PniSTDG3vWMlg',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: 'pignatarog65@gmail.com',
    title: 'Angelic',
    description: '',
    result: 'runner-up',
    firstName: 'GIUSEPPE',
    lastName: 'PICCOLI RESTA',
    fileName: 'angelic-1.jpg',
  },
  {
    id: 'TQRxEholyEEcr-sqwr5bi',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: 'pignatarog65@gmail.com',
    title: 'Angelic',
    description: '',
    result: 'runner-up',
    firstName: 'GIUSEPPE',
    lastName: 'PICCOLI RESTA',
    fileName: 'angelic-2.jpg',
  },
  {
    id: 'YJWoZ0heTcsQVI2HOoC1i',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: 'pignatarog65@gmail.com',
    title: 'Angelic',
    description: '',
    result: 'runner-up',
    firstName: 'GIUSEPPE',
    lastName: 'PICCOLI RESTA',
    fileName: 'angelic-3.jpg',
  },
  {
    id: 'EXyXqIkRQQFacwkCNMRb0',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Condominio',
    description: '',
    result: 'runner-up',
    firstName: 'MARCELLO',
    lastName: 'DI FRANCESCO',
    fileName: 'condominio.jpg',
  },
  {
    id: 'bwFPEcEI_GtI-9kQ4zSfQ',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Newlife',
    description: '',
    result: 'runner-up',
    firstName: 'MARCELLO',
    lastName: 'DI FRANCESCO',
    fileName: 'newlife.jpg',
  },
  {
    id: 'Ztcr_ZVJa9vMv4gTSLufX',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'The intruder',
    description: '',
    result: 'runner-up',
    firstName: 'MARCELLO',
    lastName: 'DI FRANCESCO',
    fileName: 'the-intruder.jpg',
  },
  {
    id: 'bMbmAE4sUgLhOQy9vTVRL',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: '',
    title: 'Contrasti',
    description: '',
    result: 'first',
    firstName: 'CORRADO',
    lastName: 'CIAVALINI',
    fileName: 'contrasti.jpg',
  },
  {
    id: 'IVKUiEhX78-Gg-caP22NL',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: '',
    title: '',
    description: '',
    result: 'second',
    firstName: 'MANUELA',
    lastName: 'CAMPITELLI- Where I belong',
    fileName: 'image-67.jpg',
  },
  {
    id: 'bb6591vkQLn0oOw15nfSX',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: '',
    title: 'A riposo nelle onde',
    description: '',
    result: 'third',
    firstName: 'CORRADO',
    lastName: 'CIAVALINI',
    fileName: 'a-riposo-nelle-onde.jpg',
  },
  {
    id: 'L4JeEIgHJxEV9Ruzzftt3',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: 'dcg1983@alice.it',
    title: 'Come correre sui trampoli',
    description: '',
    result: 'runner-up',
    firstName: 'GABRIELE',
    lastName: 'DI CREDICO',
    fileName: 'come-correre-sui-trampoli.jpg',
  },
  {
    id: '2GMTkmNxFjctLnwqM6xHS',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: '',
    title: '',
    description: '',
    result: 'runner-up',
    firstName: 'MARIO',
    lastName: 'RAPINI- La mucchiola',
    fileName: 'image-70.jpg',
  },
  {
    id: '0nRCFMZDr9YoCc54BVqhf',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: '',
    title: 'Illuminata',
    description: '',
    result: 'runner-up',
    firstName: 'FABIO',
    lastName: 'COSTANZO',
    fileName: 'illuminata.jpg',
  },
  {
    id: 'sOl2OB-c8a7PnVtKZ4qXp',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: '',
    title: 'Tramonto',
    description: '',
    result: 'runner-up',
    firstName: 'MARCO',
    lastName: 'CARACENI',
    fileName: 'tramonto.jpg',
  },
  {
    id: 'WLdgkk4qxJGbY5-9Ie9zG',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: '',
    title: 'Vallevò',
    description: '',
    result: 'runner-up',
    firstName: 'MARIO',
    lastName: 'RAPINI',
    fileName: 'vallev.jpg',
  },
  {
    id: 'kK5PN4I7R3iUb0r13_IDp',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: 'fabriziopompilio@gmail.com',
    title: 'Traboccalba',
    description: '',
    result: 'runner-up',
    firstName: 'FABRIZIO',
    lastName: 'POMPILIO',
    fileName: 'traboccalba.jpg',
  },
  {
    id: 'w0wHWqC-_3hRNW4ovVygT',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: '',
    title: 'Alba',
    description: '',
    result: 'runner-up',
    firstName: 'MARCO',
    lastName: 'CARACENI',
    fileName: 'alba.jpg',
  }
];
