export interface MigrationSubmission {
  id: string;
  contestId: string;
  categoryId: string;
  userEmail: string;
  title: string;
  description: string;
  result: string;
  firstName: string;
  lastName: string;
  fileName: string;
}

export const submissions: MigrationSubmission[] = [
  {
    id: 'PMpRCgfg8vcrNY_-jcYM5',
    contestId: 'uw-2013',
    categoryId: 'art-in-the-water',
    userEmail: '',
    title: 'Giro',
    description: '',
    result: 'first',
    firstName: 'Fernandez',
    lastName: 'Sergi Garcia',
    fileName: '2013-giro.jpg',
  },
  {
    id: 'up1Fsmm2prLM0R13Dw2VS',
    contestId: 'uw-2013',
    categoryId: 'art-in-the-water',
    userEmail: '',
    title: 'Primavera',
    description: '',
    result: 'second',
    firstName: 'Marco',
    lastName: 'Caraceni',
    fileName: '2013-primavera.jpg',
  },
  {
    id: 'k1zrV3ftlf1WsxybtCNio',
    contestId: 'uw-2013',
    categoryId: 'art-in-the-water',
    userEmail: '',
    title: 'Pianeta Acqua',
    description: '',
    result: 'third',
    firstName: 'Raimundo',
    lastName: 'Fernandez Diaz',
    fileName: '2013-pianeta-acqua.jpg',
  },
  {
    id: 'CZYYVAurKkC1m8RVDbd-1',
    contestId: 'uw-2013',
    categoryId: 'art-in-the-water',
    userEmail: '',
    title: 'Lacrime Di Luce',
    description: '',
    result: 'runner-up',
    firstName: 'Giordano',
    lastName: 'Cipriani',
    fileName: '2013-lacrime-di-luce.jpg',
  },
  {
    id: 'ENMtec3oyC4a4uBBvKg-8',
    contestId: 'uw-2013',
    categoryId: 'art-in-the-water',
    userEmail: '',
    title: 'Allo Specchio',
    description: '',
    result: 'runner-up',
    firstName: 'Tiziana',
    lastName: 'Della Zanna',
    fileName: '2013-allo-specchio.jpg',
  },
  {
    id: 'phEe_6fJJTSAgF-_CXZ5Y',
    contestId: 'uw-2013',
    categoryId: 'special-mention',
    userEmail: 'pignatarog65@gmail.com',
    title: 'Angelic',
    description: '',
    result: 'first',
    firstName: 'Giuseppe',
    lastName: 'Picccioli Resta',
    fileName: '2013-angelic.jpg',
  },
  {
    id: 'gulNSQBEkXpcpZdKmlsu3',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: 'pignatarog65@gmail.com',
    title: 'Iridescenze',
    description: '',
    result: 'first',
    firstName: 'Giuseppe',
    lastName: 'Piccoli Resta',
    fileName: '2013-iridescenze.jpg',
  },
  {
    id: '4w6IwARftRNqm3Fs2jasH',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: 'luc.rooman@telenet.be',
    title: 'Plantvis',
    description: '',
    result: 'second',
    firstName: 'Luc',
    lastName: 'Rooman',
    fileName: '2013-plantvis.jpg',
  },
  {
    id: 'zVmuDcE5rQnObSEVYdSbz',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: '',
    title: 'The Dentist',
    description: '',
    result: 'third',
    firstName: 'Davide',
    lastName: 'Lopresti',
    fileName: '2013-the-dentist.jpg',
  },
  {
    id: '-2iipIrh_bdwE3UQblFjs',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: 'pbau63@libero.it',
    title: 'In Punta Di Pinne',
    description: '',
    result: 'runner-up',
    firstName: 'Paolo',
    lastName: 'Bausani',
    fileName: '2013-in-punta-di-pinne.jpg',
  },
  {
    id: '71123iAvXGgWkhCJ7gn3N',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: '',
    title: "Goby's",
    description: '',
    result: 'runner-up',
    firstName: 'Filippo',
    lastName: 'Borghi',
    fileName: '2013-gobys.jpg',
  },
  {
    id: 'p3fTwd2YoyOKcGgGmnjUX',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: 'pignatarog65@gmail.com',
    title: 'Panzona',
    description: '',
    result: 'runner-up',
    firstName: 'Giuseppe',
    lastName: 'Piccoli Resta',
    fileName: '2013-panzona.jpg',
  },
  {
    id: 'ndIiHRL1wbd1jfFV5-Ek6',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: '',
    title: 'Frog Fish',
    description: '',
    result: 'runner-up',
    firstName: 'Matteo',
    lastName: 'Visconti',
    fileName: '2013-frog-fish.jpg',
  },
  {
    id: 'R5VoW1B5cOxAy9b9SXRGI',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: '',
    title: 'Pigmy',
    description: '',
    result: 'runner-up',
    firstName: 'Pietro',
    lastName: 'Formis',
    fileName: '2013-pigmy.jpg',
  },
  {
    id: 'iQ6ZvkByUVN8Ioeypk-0V',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: '',
    title: 'Nuova Generazione',
    description: '',
    result: 'runner-up',
    firstName: 'Davide',
    lastName: 'Lopresti',
    fileName: '2013-nuova-generazione.jpg',
  },
  {
    id: '5wtlVYqo4dl5wKWqTtYkS',
    contestId: 'uw-2013',
    categoryId: 'macro',
    userEmail: '',
    title: 'La Strana Coppia',
    description: '',
    result: 'runner-up',
    firstName: 'Adriano',
    lastName: 'Morettin',
    fileName: '2013-la-strana-coppia.jpg',
  },
  {
    id: '7g8Q-fz55QeZkaKkMmd9Q',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Blue Shark',
    description: '',
    result: 'first',
    firstName: 'Filippo',
    lastName: 'Borghi',
    fileName: '2013-blue-shark.jpg',
  },
  {
    id: 'sf-Oikzh6TpaedWl0SWfF',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Incontri Ravvicinati',
    description: '',
    result: 'second',
    firstName: 'Domenico',
    lastName: 'Roscigno',
    fileName: '2013-incontri-ravvicinati.jpg',
  },
  {
    id: 'utz8HapC54XFnmhJ3CyhY',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Afternoon',
    description: '',
    result: 'third',
    firstName: 'Fernandez',
    lastName: 'Sergi Garcia',
    fileName: '2013-afternoon.jpg',
  },
  {
    id: '5Nh9nXLzsSi-WcZs7_UPf',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Cerchio Della Vita',
    description: '',
    result: 'runner-up',
    firstName: 'Isabella',
    lastName: 'Maffei',
    fileName: '2013-cerchio-della-vita.jpg',
  },
  {
    id: 'U-Q1U0IbDebHGXuO1sM8Y',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Iguana',
    description: '',
    result: 'runner-up',
    firstName: 'Filippo',
    lastName: 'Borghi',
    fileName: '2013-iguana.jpg',
  },
  {
    id: 'n8ndKjCAzrzc7kUQemYEq',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Fallen in the Sky',
    description: '',
    result: 'runner-up',
    firstName: 'Montse',
    lastName: 'Grillo',
    fileName: '2013-fallen-in-the-sky.jpg',
  },
  {
    id: 'Zusmh1YtYmVNb5FcLRxom',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Predator',
    description: '',
    result: 'runner-up',
    firstName: 'Marcello',
    lastName: 'Di Francesco',
    fileName: '2013-predator.jpg',
  },
  {
    id: 'dPCci8pKpHidOJMwQepJb',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Connessione',
    description: '',
    result: 'runner-up',
    firstName: 'Isabella',
    lastName: 'Maffei',
    fileName: '2013-connessione.jpg',
  },
  {
    id: '-dd887Vw1Hw8QGX538mzB',
    contestId: 'uw-2013',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'La Medusa E Le Sue Ancelle',
    description: '',
    result: 'runner-up',
    firstName: 'Alberto',
    lastName: 'Gallucci',
    fileName: '2013-la-medusa-e-le-sue-ancelle.jpg',
  },
  {
    id: 'tJPLEtCiF4dYRWtkxSbKT',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: '',
    description: '',
    result: 'first',
    firstName: 'Rosanna',
    lastName: 'Bonati',
    fileName: '2013-image-26.jpg',
  },
  {
    id: '1F956js3mdpxbDDYfC_yc',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Giochi Di Luce',
    description: '',
    result: 'second',
    firstName: 'Francesco',
    lastName: 'Bazzotti',
    fileName: '2013-giochi-di-luce.jpg',
  },
  {
    id: 'QZKIt6T3_LX3Gjns3C-hx',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: "Nido D'amore",
    description: '',
    result: 'third',
    firstName: 'Filippo',
    lastName: 'Ioni',
    fileName: '2013-nido-damore.jpg',
  },
  {
    id: 'QC3ImBVn57j4IPBe6t22D',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Granchietto',
    description: '',
    result: 'runner-up',
    firstName: 'Nadia',
    lastName: 'De Santis',
    fileName: '2013-granchietto.jpg',
  },
  {
    id: 'umfScLHnJ8phqwHPscV3D',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Proud Mama',
    description: '',
    result: 'runner-up',
    firstName: 'Rosanna',
    lastName: 'Bonati',
    fileName: '2013-proud-mama.jpg',
  },
  {
    id: 'FL4FLyRhYM7-asKs9ti4Z',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Cavalluccio Rosso',
    description: '',
    result: 'runner-up',
    firstName: 'Gianni',
    lastName: 'Colucci',
    fileName: '2013-cavalluccio-rosso.jpg',
  },
  {
    id: 'QhyL-ZJKJg6HFQhwV7duo',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Terminator',
    description: '',
    result: 'runner-up',
    firstName: 'Marco',
    lastName: 'Fantin',
    fileName: '2013-terminator.jpg',
  },
  {
    id: '6Wt_7wrj0bt7YdH1Mp6RH',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Nuove Generazioni',
    description: '',
    result: 'runner-up',
    firstName: 'Paolo',
    lastName: 'Fontanella',
    fileName: '2013-nuove-generazioni.jpg',
  },
  {
    id: 'PH7qzTWzDvaC0EJKesYt5',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Twist',
    description: '',
    result: 'runner-up',
    firstName: 'Flavio',
    lastName: 'Vailati',
    fileName: '2013-twist.jpg',
  },
  {
    id: 'us-68mycwVu-vfRkAFej6',
    contestId: 'uw-2013',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Apollo 13',
    description: '',
    result: 'runner-up',
    firstName: 'Marco',
    lastName: 'Fantino',
    fileName: '2013-apollo-13.jpg',
  },
  {
    id: 'BqO_9WSUA4_b3QiKO_p3j',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'The Monster',
    description: '',
    result: 'first',
    firstName: 'Marc',
    lastName: 'Felix Casanovas',
    fileName: '2013-the-monster.jpg',
  },
  {
    id: 'DhQZ8smumk_Ka0QfDvVrd',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Zeus',
    description: '',
    result: 'first',
    firstName: 'Marc',
    lastName: 'Felix Casanovas',
    fileName: '2013-zeus.jpg',
  },
  {
    id: 'fuBZ4CP0KP9GP98pMO6-_',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Hippocampus',
    description: '',
    result: 'first',
    firstName: 'Marc',
    lastName: 'Felix Casanovas',
    fileName: '2013-hippocampus.jpg',
  },
  {
    id: 'TEwFUnu08nN8aTNfiT27Q',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Cova De La Vaca,...',
    description: '',
    result: 'second',
    firstName: 'Pietro',
    lastName: 'Formis',
    fileName: '2013-cova-de-la-vaca.jpg',
  },
  {
    id: '6g9hhwWVqG6a-BRSW8sL2',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Apogon',
    description: '',
    result: 'second',
    firstName: 'Pietro',
    lastName: 'Formis',
    fileName: '2013-apogon.jpg',
  },
  {
    id: '-koBHPUgHEHmglxvJLOh8',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Spada',
    description: '',
    result: 'second',
    firstName: 'Pietro',
    lastName: 'Formis',
    fileName: '2013-spada.jpg',
  },
  {
    id: 'Q5dntF6h5_Z5kBDX4I9UL',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Deep Hunting,...',
    description: '',
    result: 'third',
    firstName: 'Maurizio',
    lastName: 'Pasi',
    fileName: '2013-deep-hunting.jpg',
  },
  {
    id: 'B3WjI9PNOwWgbVMdG-QKI',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Firework',
    description: '',
    result: 'third',
    firstName: 'Maurizio',
    lastName: 'Pasi',
    fileName: '2013-firework.jpg',
  },
  {
    id: 'QbVNJYciWzMTL6QyRGNWe',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Twins',
    description: '',
    result: 'third',
    firstName: 'Maurizio',
    lastName: 'Pasi',
    fileName: '2013-twins.jpg',
  },
  {
    id: 'noL4vK1cgO6aXr9LXUDhf',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Friedegg',
    description: '',
    result: 'runner-up',
    firstName: 'David',
    lastName: 'Antoja Mas',
    fileName: '2013-friedegg.jpg',
  },
  {
    id: 'gjefqYbYH0GXyn4iTIhWN',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Janolus',
    description: '',
    result: 'runner-up',
    firstName: 'David',
    lastName: 'Antoja Mas',
    fileName: '2013-janolus.jpg',
  },
  {
    id: '4LcWrJpg4LQqdRAxnWtGO',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Zeusfaber',
    description: '',
    result: 'runner-up',
    firstName: 'David',
    lastName: 'Antoja Mas',
    fileName: '2013-zeusfaber.jpg',
  },
  {
    id: '6CP0hInp09rx2DKb199fZ',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Cassiopea',
    description: '',
    result: 'runner-up',
    firstName: 'Domenico',
    lastName: 'Roscigno',
    fileName: '2013-cassiopea.jpg',
  },
  {
    id: 'RQGrmMKv9TN4C-Ljmxjxz',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'San Pietro',
    description: '',
    result: 'runner-up',
    firstName: 'Domenico',
    lastName: 'Roscigno',
    fileName: '2013-san-pietro.jpg',
  },
  {
    id: 'OVuTWCJiB6OvdqPOje9L5',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Spirografi',
    description: '',
    result: 'runner-up',
    firstName: 'Domenico',
    lastName: 'Roscigno',
    fileName: '2013-spirografi.jpg',
  },
  {
    id: 'AIzhWjW1iNdwNqz0Yfu6_',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Cothyloriza',
    description: '',
    result: 'runner-up',
    firstName: 'Adriano',
    lastName: 'Morettin',
    fileName: '2013-cothyloriza.jpg',
  },
  {
    id: '4YxzvJF7PvNidRh5NgAlA',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Protula',
    description: '',
    result: 'runner-up',
    firstName: 'Adriano',
    lastName: 'Morettin',
    fileName: '2013-protula.jpg',
  },
  {
    id: 'C4sVtncI6RvMSPx1mkM8M',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Rhyzostoma',
    description: '',
    result: 'runner-up',
    firstName: 'Adriano',
    lastName: 'Morettin',
    fileName: '2013-rhyzostoma.jpg',
  },
  {
    id: 'vKbYChbPX8JoADhMbgDsY',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: 'sadilauro@live.it',
    title: 'In Attesa',
    description: '',
    result: 'runner-up',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: '2013-in-attesa.jpg',
  },
  {
    id: 'GI3CECb4_E0iBaG5a8O_U',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: 'sadilauro@live.it',
    title: 'Testa E Coda',
    description: '',
    result: 'runner-up',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: '2013-testa-e-coda.jpg',
  },
  {
    id: 'CK2s8s_KbNY_iJsGUx9m6',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: 'sadilauro@live.it',
    title: 'Viaggio Meraviglioso',
    description: '',
    result: 'runner-up',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: '2013-viaggio-meraviglioso.jpg',
  },
  {
    id: 'r-zy9c-2DBAGALZCd0iam',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Esplode La Vita',
    description: '',
    result: 'runner-up',
    firstName: 'Alberto',
    lastName: 'Gallucci',
    fileName: '2013-esplode-la-vita.jpg',
  },
  {
    id: '2z6BmNzHQNK6eRWGVrqmi',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Pesce Balestra',
    description: '',
    result: 'runner-up',
    firstName: 'Alberto',
    lastName: 'Gallucci',
    fileName: '2013-pesce-balestra.jpg',
  },
  {
    id: 'o4yfGtGB_2AJV-DkC5vrU',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Serpula Vermicularis',
    description: '',
    result: 'runner-up',
    firstName: 'Alberto',
    lastName: 'Gallucci',
    fileName: '2013-serpula-vermicularis.jpg',
  },
  {
    id: 'TQRxEholyEEcr-sqwr5bi',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: 'pignatarog65@gmail.com',
    title: 'Angelic',
    description: '',
    result: 'runner-up',
    firstName: 'Giuseppe',
    lastName: 'Piccoli Resta',
    fileName: '2013-angelic-2.jpg',
  },
  {
    id: 'YJWoZ0heTcsQVI2HOoC1i',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: 'pignatarog65@gmail.com',
    title: 'Angelic',
    description: '',
    result: 'runner-up',
    firstName: 'Giuseppe',
    lastName: 'Piccoli Resta',
    fileName: '2013-angelic-3.jpg',
  },
  {
    id: 'EXyXqIkRQQFacwkCNMRb0',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Condominio',
    description: '',
    result: 'runner-up',
    firstName: 'Marcello',
    lastName: 'Di Francesco',
    fileName: '2013-condominio.jpg',
  },
  {
    id: 'bwFPEcEI_GtI-9kQ4zSfQ',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Newlife',
    description: '',
    result: 'runner-up',
    firstName: 'Marcello',
    lastName: 'Di Francesco',
    fileName: '2013-newlife.jpg',
  },
  {
    id: 'Ztcr_ZVJa9vMv4gTSLufX',
    contestId: 'uw-2013',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'The Intruder',
    description: '',
    result: 'runner-up',
    firstName: 'Marcello',
    lastName: 'Di Francesco',
    fileName: '2013-the-intruder.jpg',
  },
  {
    id: 'bMbmAE4sUgLhOQy9vTVRL',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: '',
    title: 'Contrasti',
    description: '',
    result: 'first',
    firstName: 'Corrado',
    lastName: 'Ciavalini',
    fileName: '2013-contrasti.jpg',
  },
  {
    id: 'IVKUiEhX78-Gg-caP22NL',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: '',
    title: 'Where I Belong',
    description: '',
    result: 'second',
    firstName: 'Manuela',
    lastName: 'Campitelli',
    fileName: '2013-image-67.jpg',
  },
  {
    id: 'bb6591vkQLn0oOw15nfSX',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: '',
    title: 'A Riposo Nelle Onde',
    description: '',
    result: 'third',
    firstName: 'Corrado',
    lastName: 'Ciavalini',
    fileName: '2013-a-riposo-nelle-onde.jpg',
  },
  {
    id: 'L4JeEIgHJxEV9Ruzzftt3',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: 'dcg1983@alice.it',
    title: 'Come Correre Sui Trampoli',
    description: '',
    result: 'runner-up',
    firstName: 'Gabriele',
    lastName: 'Di Credico',
    fileName: '2013-come-correre-sui-trampoli.jpg',
  },
  {
    id: '2GMTkmNxFjctLnwqM6xHS',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: '',
    title: '',
    description: '',
    result: 'runner-up',
    firstName: 'Mario',
    lastName: 'Rapini',
    fileName: '2013-image-70.jpg',
  },
  {
    id: '0nRCFMZDr9YoCc54BVqhf',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: '',
    title: 'Illuminata',
    description: '',
    result: 'runner-up',
    firstName: 'Fabio',
    lastName: 'Costanzo',
    fileName: '2013-illuminata.jpg',
  },
  {
    id: 'sOl2OB-c8a7PnVtKZ4qXp',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: '',
    title: 'Tramonto',
    description: '',
    result: 'runner-up',
    firstName: 'Marco',
    lastName: 'Caraceni',
    fileName: '2013-tramonto.jpg',
  },
  {
    id: 'WLdgkk4qxJGbY5-9Ie9zG',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: '',
    title: 'Vallevò',
    description: '',
    result: 'runner-up',
    firstName: 'Mario',
    lastName: 'Rapini',
    fileName: '2013-vallev.jpg',
  },
  {
    id: 'kK5PN4I7R3iUb0r13_IDp',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: 'fabriziopompilio@gmail.com',
    title: 'Traboccalba',
    description: '',
    result: 'runner-up',
    firstName: 'Fabrizio',
    lastName: 'Pompilio',
    fileName: '2013-traboccalba.jpg',
  },
  {
    id: 'w0wHWqC-_3hRNW4ovVygT',
    contestId: 'uw-2013',
    categoryId: 'trabocchi-coast',
    userEmail: '',
    title: 'Alba',
    description: '',
    result: 'runner-up',
    firstName: 'Marco',
    lastName: 'Caraceni',
    fileName: '2013-alba.jpg',
  },
];
