export interface MigrationSubmission {
  id: string;
  contestId: string;
  categoryId: string;
  userEmail: string;
  title: string;
  description: string;
  result: string;
  firstName: string;
  lastName: string;
  fileName: string;
}

export const submissions: MigrationSubmission[] = [
  {
    id: '8hGGW1e7gqv0bhBCGeLaA',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: '',
    title: 'Specchio',
    description: '',
    result: 'first',
    firstName: 'Edoardo',
    lastName: 'Errani',
    fileName: '2016-specchio.jpg',
  },
  {
    id: 'Lk0UH_JEcGptmMDR24Zpp',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: '',
    title: 'In the Mood for Love',
    description: '',
    result: 'second',
    firstName: 'Gianluca',
    lastName: 'Cucco',
    fileName: '2016-in-the-mood-for-love.jpg',
  },
  {
    id: 'TRm4mWRyH_QMT0JEioBKz',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: '',
    title: 'Dugongo',
    description: '',
    result: 'third',
    firstName: 'Andrea',
    lastName: 'Izzotti',
    fileName: '2016-dugongo.jpg',
  },
  {
    id: 'Z12bqJBAgeNZZ61WR5rOl',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: '',
    title: "Il Polpo Da Un' altra prospettiva",
    description: '',
    result: 'runner-up',
    firstName: 'Pierluigi',
    lastName: 'Peis',
    fileName: '2016-il-polpo-da-un-altra-prospettiva.jpg',
  },
  {
    id: 'i0IxfDm2KRuWFJf5bY9OJ',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: 'info@maxgiorgetta.it',
    title: 'Rosso Di Notte',
    description: '',
    result: 'runner-up',
    firstName: 'Massimo',
    lastName: 'Giorgetta',
    fileName: '2016-rosso-di-notte.jpg',
  },
  {
    id: 'B5Mu6kngeZCQvXSO3iTzM',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: '',
    title: 'Upside down',
    description: '',
    result: 'runner-up',
    firstName: 'Lynn',
    lastName: 'Wu',
    fileName: '2016-upside-down.jpg',
  },
  {
    id: 'YVAgJvIR7nNEuAjqmU2FA',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: '',
    title: 'Anemone Leopardo',
    description: '',
    result: 'runner-up',
    firstName: 'Virginia',
    lastName: 'Salzedo',
    fileName: '2016-anemone-leopardo.jpg',
  },
  {
    id: 'DhWqpAjNdXaQ4mpZjuhwg',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: '',
    title: 'Atteggiamento Difensivo',
    description: '',
    result: 'runner-up',
    firstName: 'Gianni',
    lastName: 'Colucci',
    fileName: '2016-atteggiamento-difensivo.jpg',
  },
  {
    id: 'sMfHyl74g7tUDtioinA2Q',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: 'stefano.cerb@libero.it',
    title: 'Pulizia Meccanica',
    description: '',
    result: 'runner-up',
    firstName: 'Stefano',
    lastName: 'Cerbai',
    fileName: '2016-pulizia-meccanica.jpg',
  },
  {
    id: 'gD5EejmNFy7e2UmnHWqm4',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: '',
    title: 'Ascentic',
    description: '',
    result: 'runner-up',
    firstName: 'Emanuele',
    lastName: 'Vitale',
    fileName: '2016-ascentic.jpg',
  },
  {
    id: '62119fs-s8Bxa9hEXAEkZ',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: 'info@gmphotosub.com',
    title: 'Acrobata',
    description: '',
    result: 'first',
    firstName: 'Giacomo',
    lastName: 'Marchione',
    fileName: '2016-acrobata.jpg',
  },
  {
    id: 'nnffRNn9eTn5anoqRKqAz',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: 'Clownfish',
    description: '',
    result: 'second',
    firstName: 'Rooman',
    lastName: 'Luc',
    fileName: '2016-clownfish.jpg',
  },
  {
    id: '0_LVA4xclDOR7FAN8qCLT',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: 'Ladybug',
    description: '',
    result: 'third',
    firstName: 'Jorge',
    lastName: 'Marco',
    fileName: '2016-ladybug.jpg',
  },
  {
    id: '56L4yUDl7bHYTGPR1GCNq',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: 'albyx@icloud.com',
    title: 'Mi Casa Es Tu Casa !',
    description: '',
    result: 'runner-up',
    firstName: 'Alberto',
    lastName: 'Buonanno',
    fileName: '2016-mi-casa-es-tu-casa.jpg',
  },
  {
    id: 'EZV3jmDy_qsXQpq_cnhOu',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: 'Eye in the Dark',
    description: '',
    result: 'runner-up',
    firstName: 'Lynn',
    lastName: 'Wu',
    fileName: '2016-eye-in-the-dark.jpg',
  },
  {
    id: 'zPJom7RxXrt_v0o-HG7zt',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: 'The Little King',
    description: '',
    result: 'runner-up',
    firstName: 'Mauro',
    lastName: 'Mainardi',
    fileName: '2016-the-little-king.jpg',
  },
  {
    id: 'CZgbEOqkXW9vqSJ8AuGIu',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: 'Gorgonia Snooty',
    description: '',
    result: 'runner-up',
    firstName: 'Alessandro',
    lastName: 'Giannaccini',
    fileName: '2016-gorgonia-snooty.jpg',
  },
  {
    id: 'CNn6SZDCKsx6gE94kocs0',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: "L'Ago",
    description: '',
    result: 'runner-up',
    firstName: 'Domenico',
    lastName: 'Tritto',
    fileName: '2016-lago.jpg',
  },
  {
    id: 'LnXWjDhncQo396et7IgqW',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: 'Red Devil',
    description: '',
    result: 'runner-up',
    firstName: 'Staes',
    lastName: 'Filip',
    fileName: '2016-red-devil.jpg',
  },
  {
    id: 'S3RRKtkInbMNnXkLpjfAp',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: 'Parto Con Successo',
    description: '',
    result: 'runner-up',
    firstName: 'Gianni',
    lastName: 'Colucci',
    fileName: '2016-parto-con-successo.jpg',
  },
  {
    id: 'qVF361bRTvxZrpv_N2mXx',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: 'Sul Tappeto Rosso',
    description: '',
    result: 'runner-up',
    firstName: 'Gianluca',
    lastName: 'Romano',
    fileName: '2016-sul-tappeto-rosso.jpg',
  },
  {
    id: 'BwUOgQaF_MElP923r6Gqn',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: 'gabriella.luongo@yahoo.it',
    title: 'Dancers',
    description: '',
    result: 'first',
    firstName: 'Gabriella',
    lastName: 'Luongo',
    fileName: '2016-dancers.jpg',
  },
  {
    id: 'st6MBQ17SqMM3E34IBdWP',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Le Pseudo Orche Di Karam Masamirit',
    description: '',
    result: 'second',
    firstName: 'Renato',
    lastName: 'La Grassa',
    fileName: '2016-le-pseudo-orche-di-karam-masamirit.jpg',
  },
  {
    id: 'Zw9T3wLcIoOiuLWL9Bys4',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Red Velvet',
    description: '',
    result: 'third',
    firstName: 'Fabio',
    lastName: 'Iardino',
    fileName: '2016-red-velvet.jpg',
  },
  {
    id: 'hBGxp-tSkdRkxLBWazYG-',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Verdesche Atlantiche',
    description: '',
    result: 'runner-up',
    firstName: 'Flavio',
    lastName: 'Vailati',
    fileName: '2016-verdesche-atlantiche.jpg',
  },
  {
    id: 'wSZ9TPG_eJLWrOdspXYdw',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: 'albyx@icloud.com',
    title: 'Sunray in the Deep',
    description: '',
    result: 'runner-up',
    firstName: 'Alberto',
    lastName: 'Buonanno',
    fileName: '2016-sunray-in-the-deep.jpg',
  },
  {
    id: 'PMVyMuhzF6pCXd7O_ATeW',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Diagonale Doppia',
    description: '',
    result: 'runner-up',
    firstName: 'Mauro',
    lastName: 'Rapini',
    fileName: '2016-diagonale-doppia.jpg',
  },
  {
    id: 'bpkjLTTj7OxdxKj2410KH',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Shark Torpedo',
    description: '',
    result: 'runner-up',
    firstName: 'Yen-Yi',
    lastName: 'Lee',
    fileName: '2016-shark-torpedo.jpg',
  },
  {
    id: '_OJnBg3ShUy98xG8dA0Aq',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: 'zanninimassimo@yahoo.it',
    title: 'Humpback Dance',
    description: '',
    result: 'runner-up',
    firstName: 'Massimo',
    lastName: 'Zannini',
    fileName: '2016-humpback-dance.jpg',
  },
  {
    id: 'aJBBdYR96ejHyTtNb8JBZ',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'La Superba Regalità',
    description: '',
    result: 'runner-up',
    firstName: 'Mauro',
    lastName: 'Mainardi',
    fileName: '2016-la-superba-regalita.jpg',
  },
  {
    id: 'MdN6WbjuBOeiB9Sqq5gAO',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Planet Turtles',
    description: '',
    result: 'runner-up',
    firstName: 'Plamena',
    lastName: 'Mileva',
    fileName: '2016-planet-turtles.jpg',
  },
  {
    id: 'qHDkOBQ0q9txjIgfCAhWs',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Rombo Alla Ligure',
    description: '',
    result: 'first',
    firstName: 'Pietro',
    lastName: 'Formis',
    fileName: '2016-rombo-alla-ligure.jpg',
  },
  {
    id: 'Of0pvz4RVBzpy7jgcpQUJ',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: "Generazione D'oro",
    description: '',
    result: 'first',
    firstName: 'Pietro',
    lastName: 'Formis',
    fileName: '2016-generazione-doro.jpg',
  },
  {
    id: 'ibuiNVHUkO4XP70Vr-0aZ',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Monster & Co',
    description: '',
    result: 'first',
    firstName: 'Pietro',
    lastName: 'Formis',
    fileName: '2016-monster-co.jpg',
  },
  {
    id: 'h74iiwn-Wx_GAN2N33uQF',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: 'gabriella.luongo@yahoo.it',
    title: 'Nursery',
    description: '',
    result: 'second',
    firstName: 'Gabriella',
    lastName: 'Luongo',
    fileName: '2016-nursery.jpg',
  },
  {
    id: 'qAnU6fGxkQgjaofHa9OtD',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: 'gabriella.luongo@yahoo.it',
    title: 'Gorgonia Con Gameti',
    description: '',
    result: 'second',
    firstName: 'Gabriella',
    lastName: 'Luongo',
    fileName: '2016-gorgonia-con-gameti.jpg',
  },
  {
    id: '4pyb5JTjTUOaMsjQ1NMsY',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: 'gabriella.luongo@yahoo.it',
    title: 'Timidezza',
    description: '',
    result: 'second',
    firstName: 'Gabriella',
    lastName: 'Luongo',
    fileName: '2016-timidezza.jpg',
  },
  {
    id: 'SKpz59dxXoMN8-qZ4MF82',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: 'zanninimassimo@yahoo.it',
    title: 'Med Jewerly',
    description: '',
    result: 'third',
    firstName: 'Massimo',
    lastName: 'Zannini',
    fileName: '2016-med-jewerly-1.jpg',
  },
  {
    id: 'WKtYwtEHbb6z_9qbI4900',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: 'zanninimassimo@yahoo.it',
    title: 'Med Jewerly',
    description: '',
    result: 'third',
    firstName: 'Massimo',
    lastName: 'Zannini',
    fileName: '2016-med-jewerly-2.jpg',
  },
  {
    id: 'QjtGasqDhYJrlVHqgQOWL',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: 'zanninimassimo@yahoo.it',
    title: 'Med Jewerly',
    description: '',
    result: 'third',
    firstName: 'Massimo',
    lastName: 'Zannini',
    fileName: '2016-med-jewerly-3.jpg',
  },
  {
    id: 'TQNAjba3qoXjYs1zgvjkP',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Toward Orbit',
    description: '',
    result: 'runner-up',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: '2016-toward-orbit.jpg',
  },
  {
    id: '55CgO_UaOum0nMksnDFCL',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Yellow Mom',
    description: '',
    result: 'runner-up',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: '2016-yellow-mom.jpg',
  },
  {
    id: '9RTXQFplSjpdRBC2IBbcq',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Looking at the Sky',
    description: '',
    result: 'runner-up',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: '2016-looking-at-the-sky.jpg',
  },
  {
    id: 'A9WTD17h9DnDTReFg2_1V',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'The Queen',
    description: '',
    result: 'runner-up',
    firstName: 'Pasquale',
    lastName: 'Vassallo',
    fileName: '2016-the-queen.jpg',
  },
  {
    id: 'MwPL-hw0ptzQXgUwFWYPf',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Future',
    description: '',
    result: 'runner-up',
    firstName: 'Pasquale',
    lastName: 'Vassallo',
    fileName: '2016-future.jpg',
  },
  {
    id: 'eDw0bvSD6XJd2E051Xv9t',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'The Guest',
    description: '',
    result: 'runner-up',
    firstName: 'Pasquale',
    lastName: 'Vassallo',
    fileName: '2016-the-guest.jpg',
  },
  {
    id: 'vK1bccTzP9QWcObIOY0CV',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Doride in the Light',
    description: '',
    result: 'runner-up',
    firstName: 'Virginia',
    lastName: 'Salzedo',
    fileName: '2016-doride-in-the-light.jpg',
  },
  {
    id: 'hddHV0zcf3mMb6LN1PRgO',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'La Straniera',
    description: '',
    result: 'runner-up',
    firstName: 'Virginia',
    lastName: 'Salzedo',
    fileName: '2016-la-straniera.jpg',
  },
  {
    id: 'ttDsVVkdNDupd_5L8p0ab',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Una Finestra Sul Mare',
    description: '',
    result: 'runner-up',
    firstName: 'Virginia',
    lastName: 'Salzedo',
    fileName: '2016-una-finestra-sul-mare.jpg',
  },
  {
    id: 'm9PMrfBA1nTk1smDHMAAP',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: '',
    title: 'Inno Alla Gioia',
    description: '',
    result: 'first',
    firstName: 'Gianluca',
    lastName: 'Romano',
    fileName: '2016-inno-alla-gioia.jpg',
  },
  {
    id: 'paZMZOaFoKfuZVRHdNFON',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: '',
    title: 'Magic Moment',
    description: '',
    result: 'second',
    firstName: 'Flavio',
    lastName: 'Vailati',
    fileName: '2016-magic-moment.jpg',
  },
  {
    id: 'JEz8h2fnxzfhFp5ZZKjRh',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: 'mauapule@tin.it',
    title: 'Alla Finestra',
    description: '',
    result: 'third',
    firstName: 'Mauro',
    lastName: 'Apuleo',
    fileName: '2016-alla-finestra.jpg',
  },
  {
    id: 'gRh5_EzuyMe3w107mwSRc',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: 'info@gmphotosub.com',
    title: 'Red Family',
    description: '',
    result: 'runner-up',
    firstName: 'Giacomo',
    lastName: 'Marchione',
    fileName: '2016-red-family.jpg',
  },
  {
    id: 'JeScQtWEv47aEUBAUSBT8',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: 'margar68@gmail.com',
    title: 'Monster',
    description: '',
    result: 'runner-up',
    firstName: 'Marco',
    lastName: 'Gargiulo',
    fileName: '2016-monster.jpg',
  },
  {
    id: 'uvCXULX1aXuQ7AIxu7Tuo',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: '',
    title: 'Scusate',
    description: '',
    result: 'runner-up',
    firstName: 'Massimo',
    lastName: 'Corradi',
    fileName: '2016-scusate.jpg',
  },
  {
    id: 'VXoDhxb0SptEaBT88q6XH',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: '',
    title: 'Occhio Per Occhio',
    description: '',
    result: 'runner-up',
    firstName: 'Gianni',
    lastName: 'Colucci',
    fileName: '2016-occhio-per-occhio.jpg',
  },
  {
    id: 'SOO7lwkSnxA_HIdsgHiAz',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: 'raffaelelivornese@alice.it',
    title: 'Cavalluccio Luminoso',
    description: '',
    result: 'runner-up',
    firstName: 'Raffaele',
    lastName: 'Livornese',
    fileName: '2016-cavalluccio-luminoso.jpg',
  },
  {
    id: 'm829hsnfuBz2hIbi0PIUh',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: '',
    title: 'Red & Blue',
    description: '',
    result: 'runner-up',
    firstName: 'Jordi',
    lastName: 'Benitex',
    fileName: '2016-red-blue.jpg',
  },
  {
    id: '-LxsWcDHoHIVkhmb4o7GY',
    contestId: 'uw-2016',
    categoryId: 'waves',
    userEmail: '',
    title: 'Sardinia Wave',
    description: '',
    result: 'first',
    firstName: 'Andrea',
    lastName: 'Izzotti',
    fileName: '2016-sardinia-wave.jpg',
  },
  {
    id: 'z-AtHBKJnKCVAt0qdaG9r',
    contestId: 'uw-2016',
    categoryId: 'waves',
    userEmail: '',
    title: 'W2',
    description: '',
    result: 'second',
    firstName: 'Carlos',
    lastName: 'Virgili Ribe',
    fileName: '2016-w2.jpg',
  },
  {
    id: '5ZzbGAegWUcijTM82Cb0i',
    contestId: 'uw-2016',
    categoryId: 'waves',
    userEmail: 'mauapule@tin.it',
    title: 'Splash',
    description: '',
    result: 'third',
    firstName: 'Mauro',
    lastName: 'Apuleo',
    fileName: '2016-splash.jpg',
  },
  {
    id: 'c88BcfQs2rf76ODPotG3D',
    contestId: 'uw-2016',
    categoryId: 'waves',
    userEmail: '',
    title: 'Tranquility',
    description: '',
    result: 'runner-up',
    firstName: 'Beth',
    lastName: 'Watson',
    fileName: '2016-tranquility.jpg',
  },
  {
    id: '5-jUOwkOreQAG0BHnGyC1',
    contestId: 'uw-2016',
    categoryId: 'waves',
    userEmail: '',
    title: "L'attimo di cristallo",
    description: '',
    result: 'runner-up',
    firstName: 'Gianluca',
    lastName: 'Romano',
    fileName: '2016-lattimo-di-cristallo.jpg',
  },
  {
    id: 'ikEhot6w0CmjXX5vN0cc2',
    contestId: 'uw-2016',
    categoryId: 'waves',
    userEmail: '',
    title: 'Il Tubo',
    description: '',
    result: 'runner-up',
    firstName: 'Gianluca',
    lastName: 'Romano',
    fileName: '2016-il-tubo.jpg',
  },
];
