export interface MigrationSubmission {
  id: string;
  contestId: string;
  categoryId: string;
  userEmail: string;
  title: string;
  description: string;
  result: string;
  firstName: string;
  lastName: string;
  fileName: string;
}

export const submissions: MigrationSubmission[] = [
  {
    id: 'OVbGju9JQBaE8FXjweBlH',
    contestId: 'uw-2009',
    categoryId: 'unknown',
    userEmail: '',
    title: 'Ginnie',
    description: '',
    result: 'second',
    firstName: 'Alessio',
    lastName: 'Viora',
    fileName: '2009-ginnie.jpg',
  },
  {
    id: 'G9eFq4LOTb95cyBIfOcN5',
    contestId: 'uw-2009',
    categoryId: 'unknown',
    userEmail: '',
    title: 'On Tip Toes',
    description: '',
    result: 'third',
    firstName: 'Stefano',
    lastName: 'Gradi',
    fileName: '2009-on-tip-toes.jpg',
  },
  {
    id: 'V2mcO9xEXrptVXg9wgGxJ',
    contestId: 'uw-2009',
    categoryId: 'environment',
    userEmail: '',
    title: '',
    description: '',
    result: 'first',
    firstName: 'Giovanni',
    lastName: 'Smorti',
    fileName: '2009-image-3.jpg',
  },
  {
    id: 'oV5oTV9uO3PiBquT2PDG1',
    contestId: 'uw-2009',
    categoryId: 'environment',
    userEmail: '',
    title: 'Butterfly',
    description: '',
    result: 'third',
    firstName: 'Giovanni',
    lastName: 'Smorti',
    fileName: '2009-butterfly.jpg',
  },
  {
    id: 'Md2IMv_Ju2AHtojwNhPCm',
    contestId: 'uw-2009',
    categoryId: 'environment',
    userEmail: 'pignatarog65@gmail.com',
    title: 'Pettinino',
    description: '',
    result: 'first',
    firstName: 'Giuseppe',
    lastName: 'Piccioli Resta',
    fileName: '2009-pettinino.jpg',
  },
  {
    id: 'VzIQJKr2R7pkPHMCGRr7p',
    contestId: 'uw-2009',
    categoryId: 'environment',
    userEmail: '',
    title: 'Più Sù',
    description: '',
    result: 'second',
    firstName: 'Stefano',
    lastName: 'Gradi',
    fileName: '2009-pi-s.jpg',
  },
  {
    id: 'r1fxEebj3VD8af59V6d2u',
    contestId: 'uw-2009',
    categoryId: 'environment',
    userEmail: 'dcg1983@alice.it',
    title: '',
    description: '',
    result: 'third',
    firstName: 'Gabriele',
    lastName: 'Donati',
    fileName: '2009-image-7.jpg',
  },
  {
    id: 'snKomzKCORrxN40M6mC5w',
    contestId: 'uw-2009',
    categoryId: 'macro',
    userEmail: '',
    title: '',
    description: '',
    result: 'first',
    firstName: 'Antonio',
    lastName: 'Palermo',
    fileName: '2009-image-8.jpg',
  },
  {
    id: 'XxlhClezP3SIC9ZUjStAD',
    contestId: 'uw-2009',
    categoryId: 'macro',
    userEmail: '',
    title: 'Clown',
    description: '',
    result: 'second',
    firstName: 'Giovanni',
    lastName: 'Smorti',
    fileName: '2009-clown.jpg',
  },
  {
    id: 'duXmVDutzkYbSDMZKzN_s',
    contestId: 'uw-2009',
    categoryId: 'open',
    userEmail: 'sadilauro@live.it',
    title: '',
    description: '',
    result: 'second',
    firstName: 'Salvatore',
    lastName: 'Franco',
    fileName: '2009-image-10.jpg',
  },
  {
    id: 'MDI71EatiTLPFu4BRfzZj',
    contestId: 'uw-2009',
    categoryId: 'macro',
    userEmail: '',
    title: 'The challenge',
    description: '',
    result: 'third',
    firstName: 'Annibale',
    lastName: 'Simi',
    fileName: '2009-image-11.jpg',
  },
  {
    id: 'p8jXFd9yKwQKN7ZhYSysu',
    contestId: 'uw-2009',
    categoryId: 'open',
    userEmail: '',
    title: 'Out of the Tunnel',
    description: '',
    result: 'first',
    firstName: 'Stefano',
    lastName: 'Gradi',
    fileName: '2009-out-of-the-tunnel.jpg',
  },
];
