export interface MigrationSubmission {
  id: string;
  contestId: string;
  categoryId: string;
  userEmail: string;
  title: string;
  description: string;
  result: string;
  firstName: string;
  lastName: string;
  fileName: string;
}

export const submissions: MigrationSubmission[] = [
  {
    id: 'hPSLlD-Y0wAO8n5pqs_5I',
    contestId: 'uw-2017',
    categoryId: 'compact',
    userEmail: 'davide.clementelli@gmail.com',
    title: 'Fly of the Queen',
    description: '',
    result: 'first',
    firstName: 'Davide',
    lastName: 'Clementelli',
    fileName: '2017-fly-of-the-queen.jpg',
  },
  {
    id: 'IZ20izNQrEGNS5WnyCKt1',
    contestId: 'uw-2017',
    categoryId: 'compact',
    userEmail: 'stefano.cerb@libero.it',
    title: 'Elvis',
    description: '',
    result: 'second',
    firstName: 'Stefano',
    lastName: 'Cerbai',
    fileName: '2017-elvis.jpg',
  },
  {
    id: '0AYEntN5A62R59hJpn4if',
    contestId: 'uw-2017',
    categoryId: 'compact',
    userEmail: '',
    title: 'Bursatella',
    description: '',
    result: 'third',
    firstName: 'Giacomo',
    lastName: 'Giovannini',
    fileName: '2017-bursatella.jpg',
  },
  {
    id: 'eVhD7QJEAe6Mhyx1tdFcl',
    contestId: 'uw-2017',
    categoryId: 'compact',
    userEmail: '',
    title: 'The Swarm',
    description: '',
    result: 'runner-up',
    firstName: 'Enrico',
    lastName: 'Somogyi',
    fileName: '2017-the-swarm.jpg',
  },
  {
    id: 'ypaWGPXzZYNdKg6N8dYWb',
    contestId: 'uw-2017',
    categoryId: 'compact',
    userEmail: '',
    title: 'Shark Smile',
    description: '',
    result: 'runner-up',
    firstName: 'Francesco',
    lastName: 'Bazzotti',
    fileName: '2017-shark-smile.jpg',
  },
  {
    id: 'l5dGPgE06FIASYWN8cl5S',
    contestId: 'uw-2017',
    categoryId: 'compact',
    userEmail: '',
    title: 'Missione Su Marte',
    description: '',
    result: 'runner-up',
    firstName: 'Edoardo',
    lastName: 'Errani',
    fileName: '2017-missione-su-marte.jpg',
  },
  {
    id: '8MtYErWj1Xu6KBYerR7lr',
    contestId: 'uw-2017',
    categoryId: 'wide-angle',
    userEmail: 'pbau63@libero.it',
    title: "L'albero della vita",
    description: '',
    result: 'first',
    firstName: 'Paolo',
    lastName: 'Bausani',
    fileName: '2017-lalbero-della-vita.jpg',
  },
  {
    id: 'jqTi5oebum-19zHJ30TC7',
    contestId: 'uw-2017',
    categoryId: 'wide-angle',
    userEmail: 'gabriella.luongo@yahoo.it',
    title: 'Mi Stai Guardando',
    description: '',
    result: 'second',
    firstName: 'Gabriella',
    lastName: 'Luongo',
    fileName: '2017-mi-stai-guardando.jpg',
  },
  {
    id: 'DfUjkVbK9n1yoOiuGiPWu',
    contestId: 'uw-2017',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Non Era Una Chimera',
    description: '',
    result: 'third',
    firstName: 'Domenico',
    lastName: 'Roscigno',
    fileName: '2017-non-era-una-chimera.jpg',
  },
  {
    id: '3vrOQkkwFDWaSYuxuOR5v',
    contestId: 'uw-2017',
    categoryId: 'wide-angle',
    userEmail: 'info@maxgiorgetta.it',
    title: 'Cocco Mirror',
    description: '',
    result: 'runner-up',
    firstName: 'Massimo',
    lastName: 'Giorgetta',
    fileName: '2017-cocco-mirror-giorgetta.jpg',
  },
  {
    id: 'uJ-ijcCXcwGfh6aU9qwjx',
    contestId: 'uw-2017',
    categoryId: 'wide-angle',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Acqua Dolce',
    description: '',
    result: 'runner-up',
    firstName: 'Francesco',
    lastName: 'Visintin',
    fileName: '2017-acqua-dolce.jpg',
  },
  {
    id: 'U6rNF2btKAHgOIk8oEIhC',
    contestId: 'uw-2017',
    categoryId: 'wide-angle',
    userEmail: 'zanninimassimo@yahoo.it',
    title: 'Cocco Mirror',
    description: '',
    result: 'runner-up',
    firstName: 'Massimo',
    lastName: 'Zannini',
    fileName: '2017-cocco-mirror-zannini.jpg',
  },
  {
    id: 'GeY0GBryJc8QguS5XhRoI',
    contestId: 'uw-2017',
    categoryId: 'molluscs',
    userEmail: 'gabriella.luongo@yahoo.it',
    title: 'In Un Cielo Trapunto Di Stelle',
    description: '',
    result: 'first',
    firstName: 'Gabriella',
    lastName: 'Luongo',
    fileName: '2017-in-un-cielo-trapunto-di-stelle.jpg',
  },
  {
    id: 'GZqDRQMpZkvTxj1_IlJgq',
    contestId: 'uw-2017',
    categoryId: 'molluscs',
    userEmail: 'pbau63@libero.it',
    title: 'Monolocale',
    description: '',
    result: 'second',
    firstName: 'Paolo',
    lastName: 'Bausani',
    fileName: '2017-monolocale.jpg',
  },
  {
    id: '0Wiv9brEuay9HP6PtlAVY',
    contestId: 'uw-2017',
    categoryId: 'molluscs',
    userEmail: '',
    title: 'Decollo Mediterraneo',
    description: '',
    result: 'third',
    firstName: 'Domenico',
    lastName: 'Roscigno',
    fileName: '2017-decollo-mediterraneo.jpg',
  },
  {
    id: 'zS5frlKh-QqqpFQz25Fgt',
    contestId: 'uw-2017',
    categoryId: 'molluscs',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Tritone',
    description: '',
    result: 'runner-up',
    firstName: 'Francesco',
    lastName: 'Visintin',
    fileName: '2017-tritone.jpg',
  },
  {
    id: '8oqYC9arnbML9tUrL212H',
    contestId: 'uw-2017',
    categoryId: 'molluscs',
    userEmail: 'raffaelelivornese@alice.it',
    title: 'Occhi Dolci',
    description: '',
    result: 'runner-up',
    firstName: 'Raffaele',
    lastName: 'Livornese',
    fileName: '2017-occhi-dolci.jpg',
  },
  {
    id: 'gn_NXO_6lW6HI1nxTfOfS',
    contestId: 'uw-2017',
    categoryId: 'molluscs',
    userEmail: 'mauapule@tin.it',
    title: 'A Bocca Aperta',
    description: '',
    result: 'runner-up',
    firstName: 'Mauro',
    lastName: 'Apuleo',
    fileName: '2017-a-bocca-aperta-apuleo.jpg',
  },
  {
    id: 'x0hoHg3ICabXfMbJQA-kr',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'margar68@gmail.com',
    title: 'Variazioni Cromatiche in Beige - San Pietro',
    description: '',
    result: 'first',
    firstName: 'Marco',
    lastName: 'Gargiulo',
    fileName: '2017-variazioni-cromatiche-in-beige-san-pietro.jpg',
  },
  {
    id: 'FfeJNLInnA2Ct7qeqUpYy',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'margar68@gmail.com',
    title: 'Variazioni Cromatiche in Beige - the Mask',
    description: '',
    result: 'first',
    firstName: 'Marco',
    lastName: 'Gargiulo',
    fileName: '2017-variazioni-cromatiche-in-beige-the-mask.jpg',
  },
  {
    id: 'jrFaS9HB-zgsIVFEVZueJ',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'margar68@gmail.com',
    title: 'Variazioni Cromatiche in Beige - Jelly & Vesuvio',
    description: '',
    result: 'first',
    firstName: 'Marco',
    lastName: 'Gargiulo',
    fileName: '2017-variazioni-cromatiche-in-beige-jelly-vesuvio.jpg',
  },
  {
    id: 'szbdu1ybReysMtSWSFkbS',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'nicholas.samaras@me.com',
    title: 'Swirl of the Fish',
    description: '',
    result: 'second',
    firstName: 'Nicholas',
    lastName: 'Samaras',
    fileName: '2017-swirl-of-the-fish.jpg',
  },
  {
    id: '3eFF9BK3DsjrDpbXGY5zk',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'nicholas.samaras@me.com',
    title: 'Pink Heart',
    description: '',
    result: 'second',
    firstName: 'Nicholas',
    lastName: 'Samaras',
    fileName: '2017-pink-heart.jpg',
  },
  {
    id: 'Koufj_WRW4CYrdzCFZMOT',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'nicholas.samaras@me.com',
    title: 'Fragile Elegance',
    description: '',
    result: 'second',
    firstName: 'Nicholas',
    lastName: 'Samaras',
    fileName: '2017-fragile-elegance.jpg',
  },
  {
    id: 'TWfYjpAcS2PbUgD5UTflM',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'The Mask',
    description: '',
    result: 'third',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: '2017-the-mask.jpg',
  },
  {
    id: 'i9GcVtsySfmkTglromet6',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Double Stress',
    description: '',
    result: 'third',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: '2017-double-stress.jpg',
  },
  {
    id: 'Sbi9Hf3eHN_1-XdMIFKPP',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Octopus Mammutt',
    description: '',
    result: 'third',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: '2017-octopus-mammutt.jpg',
  },
  {
    id: 'zcUJU8kmOU83MKltXtt8_',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'lombrosod@gmail.com',
    title: 'Phatos',
    description: '',
    result: 'runner-up',
    firstName: 'Davide',
    lastName: 'Lombroso',
    fileName: '2017-phatos.jpg',
  },
  {
    id: 'YyKLO0PsFTcwBrnifFyHf',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'lombrosod@gmail.com',
    title: 'Effetti Speciali',
    description: '',
    result: 'runner-up',
    firstName: 'Davide',
    lastName: 'Lombroso',
    fileName: '2017-effetti-speciali.jpg',
  },
  {
    id: '8HM8jMGjY_j4v9jx3p8j_',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'lombrosod@gmail.com',
    title: "L'attimo fuggente",
    description: '',
    result: 'runner-up',
    firstName: 'Davide',
    lastName: 'Lombroso',
    fileName: '2017-lattimo-fuggente-mediterranean.jpg',
  },
  {
    id: 'C5P48A4Ya9ePHqqL25i2t',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Barracuda Portrait',
    description: '',
    result: 'runner-up',
    firstName: 'Domenico',
    lastName: 'Roscigno',
    fileName: '2017-barracuda-portrait.jpg',
  },
  {
    id: '6d1zsPf9yIFKch1grRgmd',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Classico Mediterraneo',
    description: '',
    result: 'runner-up',
    firstName: 'Domenico',
    lastName: 'Roscigno',
    fileName: '2017-classico-mediterraneo.jpg',
  },
  {
    id: 'h0RnnRsKytXh7vSOFGFZp',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Gattopardi',
    description: '',
    result: 'runner-up',
    firstName: 'Domenico',
    lastName: 'Roscigno',
    fileName: '2017-gattopardi.jpg',
  },
  {
    id: '1BVBGYS3YdacGjRxVCho4',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'claudiozori@claudiozori.it',
    title: 'Cannabina Axinella',
    description: '',
    result: 'runner-up',
    firstName: 'Claudio',
    lastName: 'Zori',
    fileName: '2017-cannabina-axinella.jpg',
  },
  {
    id: 'uoALdoyJpF_8lVBVedUmI',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'claudiozori@claudiozori.it',
    title: 'Riflessi',
    description: '',
    result: 'runner-up',
    firstName: 'Claudio',
    lastName: 'Zori',
    fileName: '2017-riflessi-zori.jpg',
  },
  {
    id: 'wLXSIEh9q3jrZV3NtvFdd',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'claudiozori@claudiozori.it',
    title: 'A Bocca Aperta',
    description: '',
    result: 'runner-up',
    firstName: 'Claudio',
    lastName: 'Zori',
    fileName: '2017-a-bocca-aperta-zori.jpg',
  },
  {
    id: 'EqhGxVZtl0Ep-l4kcWdpp',
    contestId: 'uw-2017',
    categoryId: 'the-sea',
    userEmail: '',
    title: 'Shark Whisperer',
    description: '',
    result: 'first',
    firstName: 'Fan',
    lastName: 'Ping',
    fileName: '2017-shark-whisperer.jpg',
  },
  {
    id: 'tOh1Rs5chSGGgNodiBlnW',
    contestId: 'uw-2017',
    categoryId: 'the-sea',
    userEmail: '',
    title: 'Pescatore Al Sabbione',
    description: '',
    result: 'second',
    firstName: 'Flavio',
    lastName: 'Vailati',
    fileName: '2017-pescatore-al-sabbione.jpg',
  },
  {
    id: '1Fm9fCdPLxTGftpJGXYxd',
    contestId: 'uw-2017',
    categoryId: 'the-sea',
    userEmail: '',
    title: 'Mattanza',
    description: '',
    result: 'third',
    firstName: 'Alessio',
    lastName: 'Viora',
    fileName: '2017-mattanza.jpg',
  },
  {
    id: 'p4BPp6WGWGGpxBIC4iTU7',
    contestId: 'uw-2017',
    categoryId: 'dan-europe-photography-security',
    userEmail: 'stefano.cerb@libero.it',
    title: 'In Coppia',
    description: '',
    result: 'first',
    firstName: 'Stefano',
    lastName: 'Cerbai',
    fileName: '2017-in-coppia.jpg',
  },
  {
    id: '-XQXBepZJeUZupXzVzlCt',
    contestId: 'uw-2017',
    categoryId: 'dan-europe-photography-security',
    userEmail: '',
    title: 'Forever',
    description: '',
    result: 'second',
    firstName: 'Emanuele',
    lastName: 'Vitale',
    fileName: '2017-forever.jpg',
  },
  {
    id: 'bzENyoG-lVEmoSVP56AFC',
    contestId: 'uw-2017',
    categoryId: 'dan-europe-photography-security',
    userEmail: '',
    title: 'Unknown Title',
    description: '',
    result: 'third',
    firstName: 'Unknown',
    lastName: 'Photographer',
    fileName: '2017-unknown-title.jpg',
  },
  {
    id: 'vIhtB9oxmmO3dAeEcQ4mt',
    contestId: 'uw-2017',
    categoryId: 'giovanni-smorti-award',
    userEmail: 'lombrosod@gmail.com',
    title: "L'attimo fuggente",
    description: '',
    result: 'first',
    firstName: 'Davide',
    lastName: 'Lombroso',
    fileName: '2017-lattimo-fuggente-smorti-award.jpg',
  },
];
