export interface MigrationSubmission {
  id: string;
  contestId: string;
  categoryId: string;
  userEmail: string;
  title: string;
  description: string;
  result: string;
  firstName: string;
  lastName: string;
  fileName: string;
}

export const submissions: MigrationSubmission[] = [
  {
    id: '8hGGW1e7gqv0bhBCGeLaA',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: '',
    title: 'Specchio',
    description: '',
    result: 'first',
    firstName: 'Edoardo',
    lastName: 'Errani',
    fileName: 'specchio.jpg',
  },
  {
    id: 'Lk0UH_JEcGptmMDR24Zpp',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: '',
    title: 'In the mood for love',
    description: '',
    result: 'second',
    firstName: 'Gianluca',
    lastName: 'Cucco',
    fileName: 'in-the-mood-for-love.jpg',
  },
  {
    id: 'TRm4mWRyH_QMT0JEioBKz',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: '',
    title: 'Dugongo',
    description: '',
    result: 'third',
    firstName: 'Andrea',
    lastName: 'Izzotti',
    fileName: 'dugongo.jpg',
  },
  {
    id: 'Z12bqJBAgeNZZ61WR5rOl',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: '',
    title: "Il polpo da un' altra prospettiva",
    description: '',
    result: 'runner-up',
    firstName: 'Pierluigi',
    lastName: 'Peis',
    fileName: 'il-polpo-da-un-altra-prospettiva.jpg',
  },
  {
    id: 'i0IxfDm2KRuWFJf5bY9OJ',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: 'info@maxgiorgetta.it',
    title: 'Rosso di notte',
    description: '',
    result: 'runner-up',
    firstName: 'Massimo',
    lastName: 'Giorgetta',
    fileName: 'rosso-di-notte.jpg',
  },
  {
    id: 'B5Mu6kngeZCQvXSO3iTzM',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: '',
    title: 'Upside down',
    description: '',
    result: 'runner-up',
    firstName: 'Lynn',
    lastName: 'Wu',
    fileName: 'upside-down.jpg',
  },
  {
    id: 'YVAgJvIR7nNEuAjqmU2FA',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: '',
    title: 'Anemone leopardo',
    description: '',
    result: 'runner-up',
    firstName: 'Virginia',
    lastName: 'Salzedo',
    fileName: 'anemone-leopardo.jpg',
  },
  {
    id: 'DhWqpAjNdXaQ4mpZjuhwg',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: '',
    title: 'Atteggiamento difensivo',
    description: '',
    result: 'runner-up',
    firstName: 'Gianni',
    lastName: 'Colucci',
    fileName: 'atteggiamento-difensivo.jpg',
  },
  {
    id: 'sMfHyl74g7tUDtioinA2Q',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: 'stefano.cerb@libero.it',
    title: 'Pulizia meccanica',
    description: '',
    result: 'runner-up',
    firstName: 'Stefano',
    lastName: 'Cerbai',
    fileName: 'pulizia-meccanica.jpg',
  },
  {
    id: 'gD5EejmNFy7e2UmnHWqm4',
    contestId: 'uw-2016',
    categoryId: 'compact',
    userEmail: '',
    title: 'Ascentic',
    description: '',
    result: 'runner-up',
    firstName: 'Emanuele',
    lastName: 'Vitale',
    fileName: 'ascentic.jpg',
  },
  {
    id: '62119fs-s8Bxa9hEXAEkZ',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: 'info@gmphotosub.com',
    title: 'Acrobata',
    description: '',
    result: 'first',
    firstName: 'Giacomo',
    lastName: 'Marchione',
    fileName: 'acrobata.jpg',
  },
  {
    id: 'nnffRNn9eTn5anoqRKqAz',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: 'Clownfish',
    description: '',
    result: 'second',
    firstName: 'Rooman',
    lastName: 'Luc',
    fileName: 'clownfish.jpg',
  },
  {
    id: '0_LVA4xclDOR7FAN8qCLT',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: 'Ladybug',
    description: '',
    result: 'third',
    firstName: 'Jorge',
    lastName: 'Marco',
    fileName: 'ladybug.jpg',
  },
  {
    id: '56L4yUDl7bHYTGPR1GCNq',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: 'albyx@icloud.com',
    title: 'Mi casa es tu casa !',
    description: '',
    result: 'runner-up',
    firstName: 'Alberto',
    lastName: 'Buonanno',
    fileName: 'mi-casa-es-tu-casa.jpg',
  },
  {
    id: 'EZV3jmDy_qsXQpq_cnhOu',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: 'Eye in the dark',
    description: '',
    result: 'runner-up',
    firstName: 'Lynn',
    lastName: 'Wu',
    fileName: 'eye-in-the-dark.jpg',
  },
  {
    id: 'zPJom7RxXrt_v0o-HG7zt',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: 'The little king',
    description: '',
    result: 'runner-up',
    firstName: 'Mauro',
    lastName: 'Mainardi',
    fileName: 'the-little-king.jpg',
  },
  {
    id: 'CZgbEOqkXW9vqSJ8AuGIu',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: 'Gorgonia Snooty',
    description: '',
    result: 'runner-up',
    firstName: 'Alessandro',
    lastName: 'Giannaccini',
    fileName: 'gorgonia-snooty.jpg',
  },
  {
    id: 'CNn6SZDCKsx6gE94kocs0',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: "L'Ago",
    description: '',
    result: 'runner-up',
    firstName: 'Domenico',
    lastName: 'Tritto',
    fileName: 'lago.jpg',
  },
  {
    id: 'LnXWjDhncQo396et7IgqW',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: 'Red devil',
    description: '',
    result: 'runner-up',
    firstName: 'Staes',
    lastName: 'Filip',
    fileName: 'red-devil.jpg',
  },
  {
    id: 'S3RRKtkInbMNnXkLpjfAp',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: 'Parto con successo',
    description: '',
    result: 'runner-up',
    firstName: 'Gianni',
    lastName: 'Colucci',
    fileName: 'parto-con-successo.jpg',
  },
  {
    id: 'qVF361bRTvxZrpv_N2mXx',
    contestId: 'uw-2016',
    categoryId: 'macro',
    userEmail: '',
    title: 'Sul tappeto rosso',
    description: '',
    result: 'runner-up',
    firstName: 'Gianluca',
    lastName: 'Romano',
    fileName: 'sul-tappeto-rosso.jpg',
  },
  {
    id: 'BwUOgQaF_MElP923r6Gqn',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: 'gabriella.luongo@yahoo.it',
    title: 'Dancers',
    description: '',
    result: 'first',
    firstName: 'Gabriella',
    lastName: 'Luongo',
    fileName: 'dancers.jpg',
  },
  {
    id: 'st6MBQ17SqMM3E34IBdWP',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Le pseudo orche di Karam Masamirit',
    description: '',
    result: 'second',
    firstName: 'Renato',
    lastName: 'La Grassa',
    fileName: 'le-pseudo-orche-di-karam-masamirit.jpg',
  },
  {
    id: 'Zw9T3wLcIoOiuLWL9Bys4',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Red Velvet',
    description: '',
    result: 'third',
    firstName: 'Fabio',
    lastName: 'Iardino',
    fileName: 'red-velvet.jpg',
  },
  {
    id: 'hBGxp-tSkdRkxLBWazYG-',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Verdesche atlantiche',
    description: '',
    result: 'runner-up',
    firstName: 'Flavio',
    lastName: 'Vailati',
    fileName: 'verdesche-atlantiche.jpg',
  },
  {
    id: 'wSZ9TPG_eJLWrOdspXYdw',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: 'albyx@icloud.com',
    title: 'Sunray in the deep',
    description: '',
    result: 'runner-up',
    firstName: 'Alberto',
    lastName: 'Buonanno',
    fileName: 'sunray-in-the-deep.jpg',
  },
  {
    id: 'PMVyMuhzF6pCXd7O_ATeW',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Diagonale doppia',
    description: '',
    result: 'runner-up',
    firstName: 'Mauro',
    lastName: 'Rapini',
    fileName: 'diagonale-doppia.jpg',
  },
  {
    id: 'bpkjLTTj7OxdxKj2410KH',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Shark torpedo',
    description: '',
    result: 'runner-up',
    firstName: 'Yen-Yi',
    lastName: 'Lee',
    fileName: 'shark-torpedo.jpg',
  },
  {
    id: '_OJnBg3ShUy98xG8dA0Aq',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: 'zanninimassimo@yahoo.it',
    title: 'Humpback dance',
    description: '',
    result: 'runner-up',
    firstName: 'Massimo',
    lastName: 'Zannini',
    fileName: 'humpback-dance.jpg',
  },
  {
    id: 'aJBBdYR96ejHyTtNb8JBZ',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'La superba regalità',
    description: '',
    result: 'runner-up',
    firstName: 'Mauro',
    lastName: 'Mainardi',
    fileName: 'la-superba-regalita.jpg',
  },
  {
    id: 'MdN6WbjuBOeiB9Sqq5gAO',
    contestId: 'uw-2016',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Planet turtles',
    description: '',
    result: 'runner-up',
    firstName: 'Plamena',
    lastName: 'Mileva',
    fileName: 'planet-turtles.jpg',
  },
  {
    id: 'qHDkOBQ0q9txjIgfCAhWs',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Rombo alla ligure',
    description: '',
    result: 'first',
    firstName: 'Pietro',
    lastName: 'Formis',
    fileName: 'rombo-alla-ligure.jpg',
  },
  {
    id: 'Of0pvz4RVBzpy7jgcpQUJ',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: "Generazione d'oro",
    description: '',
    result: 'first',
    firstName: 'Pietro',
    lastName: 'Formis',
    fileName: 'generazione-doro.jpg',
  },
  {
    id: 'ibuiNVHUkO4XP70Vr-0aZ',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Monster & Co',
    description: '',
    result: 'first',
    firstName: 'Pietro',
    lastName: 'Formis',
    fileName: 'monster-co.jpg',
  },
  {
    id: 'h74iiwn-Wx_GAN2N33uQF',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: 'gabriella.luongo@yahoo.it',
    title: 'Nursery',
    description: '',
    result: 'second',
    firstName: 'Gabriella',
    lastName: 'Luongo',
    fileName: 'nursery.jpg',
  },
  {
    id: 'qAnU6fGxkQgjaofHa9OtD',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: 'gabriella.luongo@yahoo.it',
    title: 'Gorgonia con gameti',
    description: '',
    result: 'second',
    firstName: 'Gabriella',
    lastName: 'Luongo',
    fileName: 'gorgonia-con-gameti.jpg',
  },
  {
    id: '4pyb5JTjTUOaMsjQ1NMsY',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: 'gabriella.luongo@yahoo.it',
    title: 'Timidezza',
    description: '',
    result: 'second',
    firstName: 'Gabriella',
    lastName: 'Luongo',
    fileName: 'timidezza.jpg',
  },
  {
    id: 'SKpz59dxXoMN8-qZ4MF82',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: 'zanninimassimo@yahoo.it',
    title: 'Med jewerly',
    description: '',
    result: 'third',
    firstName: 'Massimo',
    lastName: 'Zannini',
    fileName: 'med-jewerly.jpg',
  },
  {
    id: 'WKtYwtEHbb6z_9qbI4900',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: 'zanninimassimo@yahoo.it',
    title: 'Med jewerly',
    description: '',
    result: 'third',
    firstName: 'Massimo',
    lastName: 'Zannini',
    fileName: 'med-jewerly.jpg',
  },
  {
    id: 'QjtGasqDhYJrlVHqgQOWL',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: 'zanninimassimo@yahoo.it',
    title: 'Med jewerly',
    description: '',
    result: 'third',
    firstName: 'Massimo',
    lastName: 'Zannini',
    fileName: 'med-jewerly.jpg',
  },
  {
    id: 'TQNAjba3qoXjYs1zgvjkP',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Toward orbit',
    description: '',
    result: 'runner-up',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: 'toward-orbit.jpg',
  },
  {
    id: '55CgO_UaOum0nMksnDFCL',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Yellow mom',
    description: '',
    result: 'runner-up',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: 'yellow-mom.jpg',
  },
  {
    id: '9RTXQFplSjpdRBC2IBbcq',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Looking at the sky',
    description: '',
    result: 'runner-up',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: 'looking-at-the-sky.jpg',
  },
  {
    id: 'A9WTD17h9DnDTReFg2_1V',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'The queen',
    description: '',
    result: 'runner-up',
    firstName: 'Pasquale',
    lastName: 'Vassallo',
    fileName: 'the-queen.jpg',
  },
  {
    id: 'MwPL-hw0ptzQXgUwFWYPf',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Future',
    description: '',
    result: 'runner-up',
    firstName: 'Pasquale',
    lastName: 'Vassallo',
    fileName: 'future.jpg',
  },
  {
    id: 'eDw0bvSD6XJd2E051Xv9t',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'The guest',
    description: '',
    result: 'runner-up',
    firstName: 'Pasquale',
    lastName: 'Vassallo',
    fileName: 'the-guest.jpg',
  },
  {
    id: 'vK1bccTzP9QWcObIOY0CV',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Doride in the light',
    description: '',
    result: 'runner-up',
    firstName: 'Virginia',
    lastName: 'Salzedo',
    fileName: 'doride-in-the-light.jpg',
  },
  {
    id: 'hddHV0zcf3mMb6LN1PRgO',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'La straniera',
    description: '',
    result: 'runner-up',
    firstName: 'Virginia',
    lastName: 'Salzedo',
    fileName: 'la-straniera.jpg',
  },
  {
    id: 'ttDsVVkdNDupd_5L8p0ab',
    contestId: 'uw-2016',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Una finestra sul mare',
    description: '',
    result: 'runner-up',
    firstName: 'Virginia',
    lastName: 'Salzedo',
    fileName: 'una-finestra-sul-mare.jpg',
  },
  {
    id: 'm9PMrfBA1nTk1smDHMAAP',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: '',
    title: 'Inno alla gioia',
    description: '',
    result: 'first',
    firstName: 'Gianluca',
    lastName: 'Romano',
    fileName: 'inno-alla-gioia.jpg',
  },
  {
    id: 'paZMZOaFoKfuZVRHdNFON',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: '',
    title: 'Magic Moment',
    description: '',
    result: 'second',
    firstName: 'Flavio',
    lastName: 'Vailati',
    fileName: 'magic-moment.jpg',
  },
  {
    id: 'JEz8h2fnxzfhFp5ZZKjRh',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: 'mauapule@tin.it',
    title: 'Alla finestra',
    description: '',
    result: 'third',
    firstName: 'Mauro',
    lastName: 'Apuleo',
    fileName: 'alla-finestra.jpg',
  },
  {
    id: 'gRh5_EzuyMe3w107mwSRc',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: 'info@gmphotosub.com',
    title: 'Red family',
    description: '',
    result: 'runner-up',
    firstName: 'Giacomo',
    lastName: 'Marchione',
    fileName: 'red-family.jpg',
  },
  {
    id: 'JeScQtWEv47aEUBAUSBT8',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: 'margar68@gmail.com',
    title: 'Monster',
    description: '',
    result: 'runner-up',
    firstName: 'Marco',
    lastName: 'Gargiulo',
    fileName: 'monster.jpg',
  },
  {
    id: 'uvCXULX1aXuQ7AIxu7Tuo',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: '',
    title: 'Scusate',
    description: '',
    result: 'runner-up',
    firstName: 'Massimo',
    lastName: 'Corradi',
    fileName: 'scusate.jpg',
  },
  {
    id: 'VXoDhxb0SptEaBT88q6XH',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: '',
    title: 'Occhio per occhio',
    description: '',
    result: 'runner-up',
    firstName: 'Gianni',
    lastName: 'Colucci',
    fileName: 'occhio-per-occhio.jpg',
  },
  {
    id: 'SOO7lwkSnxA_HIdsgHiAz',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: 'raffaelelivornese@alice.it',
    title: 'Cavalluccio luminoso',
    description: '',
    result: 'runner-up',
    firstName: 'Raffaele',
    lastName: 'Livornese',
    fileName: 'cavalluccio-luminoso.jpg',
  },
  {
    id: 'm829hsnfuBz2hIbi0PIUh',
    contestId: 'uw-2016',
    categoryId: 'seahorse',
    userEmail: '',
    title: 'Red & Blue',
    description: '',
    result: 'runner-up',
    firstName: 'Jordi',
    lastName: 'Benitex',
    fileName: 'red-blue.jpg',
  },
  {
    id: '-LxsWcDHoHIVkhmb4o7GY',
    contestId: 'uw-2016',
    categoryId: 'waves',
    userEmail: '',
    title: 'Sardinia wave',
    description: '',
    result: 'first',
    firstName: 'Andrea',
    lastName: 'Izzotti',
    fileName: 'sardinia-wave.jpg',
  },
  {
    id: 'z-AtHBKJnKCVAt0qdaG9r',
    contestId: 'uw-2016',
    categoryId: 'waves',
    userEmail: '',
    title: 'W2',
    description: '',
    result: 'second',
    firstName: 'Carlos',
    lastName: 'Virgili Ribe',
    fileName: 'w2.jpg',
  },
  {
    id: '5ZzbGAegWUcijTM82Cb0i',
    contestId: 'uw-2016',
    categoryId: 'waves',
    userEmail: 'mauapule@tin.it',
    title: 'Splash',
    description: '',
    result: 'third',
    firstName: 'Mauro',
    lastName: 'Apuleo',
    fileName: 'splash.jpg',
  },
  {
    id: 'c88BcfQs2rf76ODPotG3D',
    contestId: 'uw-2016',
    categoryId: 'waves',
    userEmail: '',
    title: 'Tranquility',
    description: '',
    result: 'runner-up',
    firstName: 'Beth',
    lastName: 'Watson',
    fileName: 'tranquility.jpg',
  },
  {
    id: '5-jUOwkOreQAG0BHnGyC1',
    contestId: 'uw-2016',
    categoryId: 'waves',
    userEmail: '',
    title: "L'attimo di cristallo",
    description: '',
    result: 'runner-up',
    firstName: 'Gianluca',
    lastName: 'Romano',
    fileName: 'lattimo-di-cristallo.jpg',
  },
  {
    id: 'ikEhot6w0CmjXX5vN0cc2',
    contestId: 'uw-2016',
    categoryId: 'waves',
    userEmail: '',
    title: 'Il tubo',
    description: '',
    result: 'runner-up',
    firstName: 'Gianluca',
    lastName: 'Romano',
    fileName: 'il-tubo.jpg',
  },
];
