export interface MigrationSubmission {
  id: string;
  contestId: string;
  categoryId: string;
  userEmail: string;
  title: string;
  description: string;
  result: string;
  firstName: string;
  lastName: string;
  fileName: string;
}

export const submissions: MigrationSubmission[] = [
  {
    id: 'oBHY-HSjxfv9Roi0z_fIF',
    contestId: 'uw-2015',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'Parende padden',
    description: '',
    result: 'first',
    firstName: 'ROOMAN',
    lastName: 'LUC',
    fileName: 'parende-padden.jpg',
  },
  {
    id: 'gZucoWJlfoZzem669kFFg',
    contestId: 'uw-2015',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'Ephemeroptera larvae',
    description: '',
    result: 'second',
    firstName: 'MAURIZIO',
    lastName: 'PASI',
    fileName: 'ephemeroptera-larvae.jpg',
  },
  {
    id: 'nJYmtsrEkhVE-NB7OmX7X',
    contestId: 'uw-2015',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'Oilà',
    description: '',
    result: 'third',
    firstName: 'VIRGINIA',
    lastName: 'SALZEDO',
    fileName: 'oila.jpg',
  },
  {
    id: 'j5kgR2h7ho7YUsCDO6EYK',
    contestId: 'uw-2015',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'Salamander Larvae',
    description: '',
    result: 'runner-up',
    firstName: 'MAURIZIO',
    lastName: 'PASI',
    fileName: 'salamander-larvae.jpg',
  },
  {
    id: '3ppnHqqDBBPA02fpRYs80',
    contestId: 'uw-2015',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'Meerval',
    description: '',
    result: 'runner-up',
    firstName: 'ROOMAN',
    lastName: 'LUC',
    fileName: 'meerval.jpg',
  },
  {
    id: 'KwNtsm-WFNOK7fJwRXiWD',
    contestId: 'uw-2015',
    categoryId: 'fresh-waters',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Il guardiano del lago',
    description: '',
    result: 'runner-up',
    firstName: 'FRANCESCO',
    lastName: 'VISINTIN',
    fileName: 'il-guardiano-del-lago.jpg',
  },
  {
    id: 'jJf9k8LGczICdVbrUrfo5',
    contestId: 'uw-2015',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Face to face',
    description: '',
    result: 'first',
    firstName: 'DAVIDE',
    lastName: 'LOPRESTI',
    fileName: 'face-to-face.jpg',
  },
  {
    id: 'TqA8Rczao0vpiGKGyzERt',
    contestId: 'uw-2015',
    categoryId: 'wide-angle',
    userEmail: 'raffaelelivornese@alice.it',
    title: 'Dal profondo degli abissi',
    description: '',
    result: 'second',
    firstName: 'RAFFAELE',
    lastName: 'LIVORNESE',
    fileName: 'dal-profondo-degli-abissi.jpg',
  },
  {
    id: 'IUTBDLaTAYixfXjZktLTh',
    contestId: 'uw-2015',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Danza dell\'amore',
    description: '',
    result: 'third',
    firstName: 'DOMENICO',
    lastName: 'ROSCIGNO',
    fileName: 'danza-dellamore.jpg',
  },
  {
    id: 'iIz-hBBiTX0EBJW-0DN_b',
    contestId: 'uw-2015',
    categoryId: 'wide-angle',
    userEmail: 'margar68@gmail.com',
    title: 'Pesce San Pietro',
    description: '',
    result: 'runner-up',
    firstName: 'MARCO',
    lastName: 'GARGIULO',
    fileName: 'pesce-san-pietro.jpg',
  },
  {
    id: 'fjkogCnKW_RBgZ01efRQn',
    contestId: 'uw-2015',
    categoryId: 'wide-angle',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'The passenger',
    description: '',
    result: 'runner-up',
    firstName: 'FRANCESCO',
    lastName: 'VISINTIN',
    fileName: 'the-passenger.jpg',
  },
  {
    id: 'Yp-NXDMJYYxkp7atuy7pF',
    contestId: 'uw-2015',
    categoryId: 'wide-angle',
    userEmail: 'claudiozori@claudiozori.it',
    title: 'Alla scoperta del Mondo',
    description: '',
    result: 'runner-up',
    firstName: 'CLAUDIO',
    lastName: 'ZORI',
    fileName: 'alla-scoperta-del-mondo.jpg',
  },
  {
    id: 'AE0Vz2aEMcrXBm2O7iViU',
    contestId: 'uw-2015',
    categoryId: 'macro',
    userEmail: '',
    title: 'Nascita',
    description: '',
    result: 'first',
    firstName: 'ELIO',
    lastName: 'NICOSIA',
    fileName: 'nascita.jpg',
  },
  {
    id: 'lvmh-M5sDgNArIX5BPjzg',
    contestId: 'uw-2015',
    categoryId: 'macro',
    userEmail: 'claudiozori@claudiozori.it',
    title: 'Riflessi',
    description: '',
    result: 'second',
    firstName: 'CLAUDIO',
    lastName: 'ZORI',
    fileName: 'riflessi.jpg',
  },
  {
    id: 'YqEXyTuTENq5xTxP4qCw1',
    contestId: 'uw-2015',
    categoryId: 'macro',
    userEmail: 'pbau63@libero.it',
    title: 'Stazione di pulizia',
    description: '',
    result: 'third',
    firstName: 'PAOLO',
    lastName: 'BAUSANI',
    fileName: 'stazione-di-pulizia.jpg',
  },
  {
    id: 'nfw6fWhJewIJ5Hxdj6kZC',
    contestId: 'uw-2015',
    categoryId: 'macro',
    userEmail: '',
    title: 'Spotlight',
    description: '',
    result: 'runner-up',
    firstName: 'MATTEO',
    lastName: 'VISCONTI',
    fileName: 'spotlight.jpg',
  },
  {
    id: 'zZZh6yHPhVvsXl7nwHvCI',
    contestId: 'uw-2015',
    categoryId: 'macro',
    userEmail: '',
    title: 'Mysterious light',
    description: '',
    result: 'runner-up',
    firstName: 'BETH',
    lastName: 'WATSON',
    fileName: 'mysterious-light.jpg',
  },
  {
    id: 'WbxcdDL6OS8QKSD76_8kD',
    contestId: 'uw-2015',
    categoryId: 'macro',
    userEmail: '',
    title: 'The hijacker',
    description: '',
    result: 'runner-up',
    firstName: 'NICHOLAUS',
    lastName: 'SAMARAS',
    fileName: 'the-hijacker.jpg',
  },
  {
    id: 'MgxlSvbmn60E-53r9Vb12',
    contestId: 'uw-2015',
    categoryId: 'macro',
    userEmail: '',
    title: 'Eggs of the sea',
    description: '',
    result: 'runner-up',
    firstName: 'LORENZO',
    lastName: 'TERRANEO',
    fileName: 'eggs-of-the-sea.jpg',
  },
  {
    id: 'd7ejT5v58mMmhrg3CIDQl',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Un po nervoso',
    description: '',
    result: 'first',
    firstName: 'SALVATORE',
    lastName: 'IANNIELLO',
    fileName: 'un-po-nervoso.jpg',
  },
  {
    id: '87hemlSVp-AU6JCaEBgZB',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'San ippocampo',
    description: '',
    result: 'first',
    firstName: 'SALVATORE',
    lastName: 'IANNIELLO',
    fileName: 'san-ippocampo.jpg',
  },
  {
    id: 'RvNvRJJhbgtiYQNf7gNlO',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Doppia sfortuna',
    description: '',
    result: 'first',
    firstName: 'SALVATORE',
    lastName: 'IANNIELLO',
    fileName: 'doppia-sfortuna.jpg',
  },
  {
    id: '0QP15S5wPrBBY2QJP_RMM',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'The satellite',
    description: '',
    result: 'second',
    firstName: 'FRANCESCO',
    lastName: 'VISINTIN',
    fileName: 'the-satellite.jpg',
  },
  {
    id: 'NMMuWIYhMtBx2M-P7B013',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Pipefish',
    description: '',
    result: 'second',
    firstName: 'FRANCESCO',
    lastName: 'VISINTIN',
    fileName: 'pipefish.jpg',
  },
  {
    id: 'brFAwJIK_J7P2hrJpNTFk',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Life on the edge',
    description: '',
    result: 'second',
    firstName: 'FRANCESCO',
    lastName: 'VISINTIN',
    fileName: 'life-on-the-edge.jpg',
  },
  {
    id: 'REAoFMXf5Jo3494I9pXMh',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Portfolio 1',
    description: '',
    result: 'third',
    firstName: 'DAVIDE',
    lastName: 'LOPRESTI',
    fileName: 'portfolio-1.jpg',
  },
  {
    id: 'eXB6EYrzHLWt_mM9RKMLQ',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Portfolio 2',
    description: '',
    result: 'third',
    firstName: 'DAVIDE',
    lastName: 'LOPRESTI',
    fileName: 'portfolio-2.jpg',
  },
  {
    id: 'OJrSBkvEHc3HcsgtCncQ9',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Portfolio 3',
    description: '',
    result: 'third',
    firstName: 'DAVIDE',
    lastName: 'LOPRESTI',
    fileName: 'portfolio-3.jpg',
  },
  {
    id: 'NXbeRZfuKeAKv99c6PVi_',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Convivenza',
    description: '',
    result: 'runner-up',
    firstName: 'DOMENICO',
    lastName: 'ROSCIGNO',
    fileName: 'convivenza.jpg',
  },
  {
    id: 'z5_XYR_InQWdE4pahXj8s',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Femmine !',
    description: '',
    result: 'runner-up',
    firstName: 'DOMENICO',
    lastName: 'ROSCIGNO',
    fileName: 'femmine.jpg',
  },
  {
    id: 'KPkYujjqskt4BKLc4eDdW',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Coppia di fatto',
    description: '',
    result: 'runner-up',
    firstName: 'DOMENICO',
    lastName: 'ROSCIGNO',
    fileName: 'coppia-di-fatto.jpg',
  },
  {
    id: 'arJkcCR4h83VYDJdgwzqI',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Il golfo',
    description: '',
    result: 'runner-up',
    firstName: 'PASQUALE',
    lastName: 'VASSALLO',
    fileName: 'il-golfo.jpg',
  },
  {
    id: 'NjFK8SJPxMWo_0gKAyceP',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'The boss',
    description: '',
    result: 'runner-up',
    firstName: 'PASQUALE',
    lastName: 'VASSALLO',
    fileName: 'the-boss.jpg',
  },
  {
    id: 'aU_tWM_6bShz7KKCBwj_Y',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'L\'ospite',
    description: '',
    result: 'runner-up',
    firstName: 'PASQUALE',
    lastName: 'VASSALLO',
    fileName: 'lospite.jpg',
  },
  {
    id: 'KJJ96SVXIv7DfCkTwxNT_',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: 'buzzichelli@virgilio.it',
    title: 'Eye',
    description: '',
    result: 'runner-up',
    firstName: 'ALESSANDRO',
    lastName: 'BUZZICHELLI',
    fileName: 'eye.jpg',
  },
  {
    id: 'ebq-dhdAek9Gs04tp8dpB',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: 'buzzichelli@virgilio.it',
    title: 'Hippocampus',
    description: '',
    result: 'runner-up',
    firstName: 'ALESSANDRO',
    lastName: 'BUZZICHELLI',
    fileName: 'hippocampus.jpg',
  },
  {
    id: 'gmI0NDRYNKoh2dy_RCq_d',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: 'buzzichelli@virgilio.it',
    title: 'Parazoanhus',
    description: '',
    result: 'runner-up',
    firstName: 'ALESSANDRO',
    lastName: 'BUZZICHELLI',
    fileName: 'parazoanhus.jpg',
  },
  {
    id: 'NP1i9F1VfoZ4KNygC_LKr',
    contestId: 'uw-2015',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Cavalluccio su spirografo',
    description: '',
    result: 'first',
    firstName: 'ANGELO',
    lastName: 'PASCALE',
    fileName: 'cavalluccio-su-spirografo.jpg',
  },
  {
    id: 'nypAYToq-7qxEEUnVjTWB',
    contestId: 'uw-2015',
    categoryId: 'newcomers',
    userEmail: 'albyx@icloud.com',
    title: 'Life in a crane',
    description: '',
    result: 'second',
    firstName: 'ALBERTO',
    lastName: 'BUONANNO',
    fileName: 'life-in-a-crane.jpg',
  },
  {
    id: 'Z2hc4wpWd0ka63cCygV1v',
    contestId: 'uw-2015',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Amici',
    description: '',
    result: 'third',
    firstName: 'DANIELE',
    lastName: 'MAGGI',
    fileName: 'amici.jpg',
  },
  {
    id: 'Tcb48J6nmpTDpDZni8ZhH',
    contestId: 'uw-2015',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Boxeur',
    description: '',
    result: 'runner-up',
    firstName: 'GIANCARLO',
    lastName: 'ZAMBELLI',
    fileName: 'boxeur.jpg',
  },
  {
    id: 'SuMVWJmN3N7_9Ei-DrJWv',
    contestId: 'uw-2015',
    categoryId: 'newcomers',
    userEmail: 'gabriella.luongo@yahoo.it',
    title: 'Harlequin shrimp',
    description: '',
    result: 'runner-up',
    firstName: 'GABRIELLA',
    lastName: 'LUONGO',
    fileName: 'harlequin-shrimp.jpg',
  },
  {
    id: 'IcSWrxAB_hQTv4kEZFJZl',
    contestId: 'uw-2015',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Twins',
    description: '',
    result: 'runner-up',
    firstName: 'KEVIN',
    lastName: 'BERGAMINI',
    fileName: 'twins.jpg',
  },
  {
    id: 'iVMRgheK1DHYJkbq_ADrK',
    contestId: 'uw-2015',
    categoryId: 'dan-europe',
    userEmail: '',
    title: 'Diego e la boa sparabile',
    description: '',
    result: 'first',
    firstName: 'VIRGINIA',
    lastName: 'SALZEDO',
    fileName: 'diego-e-la-boa-sparabile.jpg',
  },
  {
    id: 'ES2EJ2OdM2s65A-UZLtAP',
    contestId: 'uw-2015',
    categoryId: 'dan-europe',
    userEmail: '',
    title: 'Unione',
    description: '',
    result: 'second',
    firstName: 'VITO',
    lastName: 'GIANNECCHINI',
    fileName: 'unione.jpg',
  },
  {
    id: 'vQgppTgiAk19ODPBNKfTy',
    contestId: 'uw-2015',
    categoryId: 'dan-europe',
    userEmail: '',
    title: 'Sistema di coppia a prescindere',
    description: '',
    result: 'third',
    firstName: 'LORENZO',
    lastName: 'TERRANEO',
    fileName: 'sistema-di-coppia-a-prescindere.jpg',
  },
  {
    id: '4m2I4AwY1OE8pF40IBjvC',
    contestId: 'uw-2015',
    categoryId: 'dan-europe',
    userEmail: '',
    title: 'Decompressione',
    description: '',
    result: 'runner-up',
    firstName: 'ALBERTO',
    lastName: 'GALLUCCI',
    fileName: 'decompressione.jpg',
  },
  {
    id: 'cerFO0usFkhc5dcpZyXdo',
    contestId: 'uw-2015',
    categoryId: 'dan-europe',
    userEmail: 'fabriziopompilio@gmail.com',
    title: 'La coppia',
    description: '',
    result: 'runner-up',
    firstName: 'FABRIZIO',
    lastName: 'POMPILIO',
    fileName: 'la-coppia.jpg',
  },
  {
    id: 'hQ_SrmSw0N8kze69eZN9R',
    contestId: 'uw-2015',
    categoryId: 'dan-europe',
    userEmail: '',
    title: 'Segnalazione',
    description: '',
    result: 'runner-up',
    firstName: 'LORENZO',
    lastName: 'TERRANEO',
    fileName: 'segnalazione.jpg',
  }
];
