export interface MigrationSubmission {
  id: string;
  contestId: string;
  categoryId: string;
  userEmail: string;
  title: string;
  description: string;
  result: string;
  firstName: string;
  lastName: string;
  fileName: string;
}

export const submissions: MigrationSubmission[] = [
  {
    id: '0F14dvZm-WjjbMgD822EC',
    contestId: 'uw-2018',
    categoryId: 'compact',
    userEmail: '',
    title: 'Corteggiamento',
    description: '',
    result: 'first',
    firstName: 'ALESSIO',
    lastName: 'TINTI',
    fileName: 'corteggiamento.jpg',
  },
  {
    id: 'R-KUk22-R8KFJJgd-Lz7d',
    contestId: 'uw-2018',
    categoryId: 'compact',
    userEmail: 'stefano.cerb@libero.it',
    title: "L'ultimo bicchiere",
    description: '',
    result: 'second',
    firstName: 'STEFANO',
    lastName: 'CERBAI',
    fileName: 'lultimo-bicchiere.jpg',
  },
  {
    id: '4ZWtBkr9nJnO9EKOHLY3-',
    contestId: 'uw-2018',
    categoryId: 'compact',
    userEmail: 'davide.clementelli@gmail.com',
    title: 'Platax in formazione',
    description: '',
    result: 'third',
    firstName: 'DAVIDE',
    lastName: 'CLEMENTELLI',
    fileName: 'platax-in-formazione.jpg',
  },
  {
    id: 'uL5B-pECq4aYJeGnNxZXL',
    contestId: 'uw-2018',
    categoryId: 'compact',
    userEmail: '',
    title: 'Squid mother and her egg',
    description: '',
    result: 'runner-up',
    firstName: 'CHUANG',
    lastName: 'MELODY',
    fileName: 'squid-mother-and-her-egg.jpg',
  },
  {
    id: 'gv6g_Sc_iubByA64Kk4_X',
    contestId: 'uw-2018',
    categoryId: 'compact',
    userEmail: '',
    title: 'Octopus protect her eggs',
    description: '',
    result: 'runner-up',
    firstName: 'CHEN',
    lastName: 'STAN',
    fileName: 'octopus-protect-her-eggs.jpg',
  },
  {
    id: 'GZcFeSDuz40xkxabwpa_j',
    contestId: 'uw-2018',
    categoryId: 'compact',
    userEmail: '',
    title: 'Learn to fly',
    description: '',
    result: 'runner-up',
    firstName: 'GIANLUCA',
    lastName: 'CUCCO',
    fileName: 'learn-to-fly.jpg',
  },
  {
    id: 'GZinETc4Jc0i31pl5YGpT',
    contestId: 'uw-2018',
    categoryId: 'wide-angle',
    userEmail: 'luc.rooman@telenet.be',
    title: 'Mating frogs',
    description: '',
    result: 'first',
    firstName: 'LUC',
    lastName: 'ROOMAN',
    fileName: 'mating-frogs.jpg',
  },
  {
    id: 'Ys_wg0seX6B1yrxSpP8MY',
    contestId: 'uw-2018',
    categoryId: 'wide-angle',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Dos amigos',
    description: '',
    result: 'second',
    firstName: 'FRANCESCO',
    lastName: 'VISINTIN',
    fileName: 'dos-amigos.jpg',
  },
  {
    id: 'xhOOVcGuLybDPRI3FrcgF',
    contestId: 'uw-2018',
    categoryId: 'wide-angle',
    userEmail: 'claudiozori@claudiozori.it',
    title: 'Canada',
    description: '',
    result: 'third',
    firstName: 'CLAUDIO',
    lastName: 'ZORI',
    fileName: 'canada.jpg',
  },
  {
    id: 'kP8MLP43qodrS4JhKVS0L',
    contestId: 'uw-2018',
    categoryId: 'wide-angle',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Crab and seafan',
    description: '',
    result: 'runner-up',
    firstName: 'FRANCESCO',
    lastName: 'VISINTIN',
    fileName: 'crab-and-seafan.jpg',
  },
  {
    id: 'AwF3Rndl1BpetVXtdRmNh',
    contestId: 'uw-2018',
    categoryId: 'wide-angle',
    userEmail: 'gabriella.luongo@yahoo.it',
    title: 'Nascondino',
    description: '',
    result: 'runner-up',
    firstName: 'GABRIELLA',
    lastName: 'LUONGO',
    fileName: 'nascondino.jpg',
  },
  {
    id: '32qTCwrXcBCNiUvQVdHRe',
    contestId: 'uw-2018',
    categoryId: 'wide-angle',
    userEmail: 'claudiozori@claudiozori.it',
    title: 'Rospi',
    description: '',
    result: 'runner-up',
    firstName: 'CLAUDIO',
    lastName: 'ZORI',
    fileName: 'rospi.jpg',
  },
  {
    id: 'q3q5sN2OWhUtGTTemr6w5',
    contestId: 'uw-2018',
    categoryId: 'macro',
    userEmail: '',
    title: 'Dancing',
    description: '',
    result: 'first',
    firstName: 'SONGDA',
    lastName: 'CAI',
    fileName: 'dancing.jpg',
  },
  {
    id: 'r6kh5qs27jM-clUWwUsRk',
    contestId: 'uw-2018',
    categoryId: 'macro',
    userEmail: 'pbau63@libero.it',
    title: 'In fondo la luce',
    description: '',
    result: 'second',
    firstName: 'PAOLO',
    lastName: 'BAUSANI',
    fileName: 'in-fondo-la-luce.jpg',
  },
  {
    id: 'gExzeqBxJceeCSrVNkrLq',
    contestId: 'uw-2018',
    categoryId: 'macro',
    userEmail: 'claudiozori@claudiozori.it',
    title: 'Giovane lupo',
    description: '',
    result: 'third',
    firstName: 'CLAUDIO',
    lastName: 'ZORI',
    fileName: 'giovane-lupo.jpg',
  },
  {
    id: 'wlJ_1k0CgykQgt3nf2XI3',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'In trappola',
    description: '',
    result: 'first',
    firstName: 'VIRGINIA',
    lastName: 'SALZEDO',
    fileName: 'in-trappola.jpg',
  },
  {
    id: 'LlO7F1akO90VSFhkBXzS-',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Cucciolo dagli abissi',
    description: '',
    result: 'first',
    firstName: 'VIRGINIA',
    lastName: 'SALZEDO',
    fileName: 'cucciolo-dagli-abissi.jpg',
  },
  {
    id: 'xVi7jS1z60fQcGQezQzL4',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Odi et amo',
    description: '',
    result: 'first',
    firstName: 'VIRGINIA',
    lastName: 'SALZEDO',
    fileName: 'odi-et-amo.jpg',
  },
  {
    id: '61B2PUdv9_yNDDeWnO_Rl',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: 'nicholas.samaras@me.com',
    title: 'Smiling in the sunlight',
    description: '',
    result: 'second',
    firstName: 'NICHOLAS',
    lastName: 'SAMARAS',
    fileName: 'smiling-in-the-sunlight.jpg',
  },
  {
    id: 'yWckJo7ThrlUZfhEZTnJ8',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: 'nicholas.samaras@me.com',
    title: 'Graceful in the dark',
    description: '',
    result: 'second',
    firstName: 'NICHOLAS',
    lastName: 'SAMARAS',
    fileName: 'graceful-in-the-dark.jpg',
  },
  {
    id: 'bij4eHg1KdoEOKiOVsWIa',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: 'nicholas.samaras@me.com',
    title: 'Magic sphere',
    description: '',
    result: 'second',
    firstName: 'NICHOLAS',
    lastName: 'SAMARAS',
    fileName: 'magic-sphere.jpg',
  },
  {
    id: 'EdPNpr0Q23oeUMZoOewPS',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Rainbow face',
    description: '',
    result: 'third',
    firstName: 'SALVATORE',
    lastName: 'IANNIELLO',
    fileName: 'rainbow-face.jpg',
  },
  {
    id: 'SPztK1iBmYfm03oSr8_sX',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Mirror',
    description: '',
    result: 'third',
    firstName: 'SALVATORE',
    lastName: 'IANNIELLO',
    fileName: 'mirror.jpg',
  },
  {
    id: 'eEAJ1txhvVVcX0BCoi8xp',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Kiss me',
    description: '',
    result: 'third',
    firstName: 'SALVATORE',
    lastName: 'IANNIELLO',
    fileName: 'kiss-me.jpg',
  },
  {
    id: 'zSQgxVLRMH27nzenfi7Fj',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Colazione da Tiffany',
    description: '',
    result: 'runner-up',
    firstName: 'GUIDO',
    lastName: 'VILLANI',
    fileName: 'colazione-da-tiffany.jpg',
  },
  {
    id: 'K3eSDktmAhVnGqJdJb7q5',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Gobius Bucchichi embryos',
    description: '',
    result: 'runner-up',
    firstName: 'GUIDO',
    lastName: 'VILLANI',
    fileName: 'gobius-bucchichi-embryos.jpg',
  },
  {
    id: 's6Gxm990CQt9fLqtuulm4',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'La coppia',
    description: '',
    result: 'runner-up',
    firstName: 'GUIDO',
    lastName: 'VILLANI',
    fileName: 'la-coppia.jpg',
  },
  {
    id: 'IOwYGAGVImTzvAYRSZVMe',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Thoughts in the head',
    description: '',
    result: 'runner-up',
    firstName: 'PAOLO',
    lastName: 'FONTANELLA',
    fileName: 'thoughts-in-the-head.jpg',
  },
  {
    id: '8HVjvtgVduuXxjyTPT7Gn',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Swans fossils',
    description: '',
    result: 'runner-up',
    firstName: 'PAOLO',
    lastName: 'FONTANELLA',
    fileName: 'swans-fossils.jpg',
  },
  {
    id: 'PzCkfi-0moOGS4yVsTBOk',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'You do not escape me',
    description: '',
    result: 'runner-up',
    firstName: 'PAOLO',
    lastName: 'FONTANELLA',
    fileName: 'you-do-not-escape-me.jpg',
  },
  {
    id: 'sG6DfMuwtE_xSRUg0gzMP',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Backlighted',
    description: '',
    result: 'runner-up',
    firstName: 'FABIO',
    lastName: 'STRAZZI',
    fileName: 'backlighted.jpg',
  },
  {
    id: 'i_0O4CPsEbJBuSo6TcWFz',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Flying',
    description: '',
    result: 'runner-up',
    firstName: 'FABIO',
    lastName: 'STRAZZI',
    fileName: 'flying.jpg',
  },
  {
    id: 'foyMhDcubcuV99y5P-Qj2',
    contestId: 'uw-2018',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Zeus faber',
    description: '',
    result: 'runner-up',
    firstName: 'FABIO',
    lastName: 'STRAZZI',
    fileName: 'zeus-faber.jpg',
  },
  {
    id: 'IGNlzQEZRDTb8vhmY4PLo',
    contestId: 'uw-2018',
    categoryId: 'storyboard',
    userEmail: '',
    title: 'Il pane quotidiano',
    description: '',
    result: 'first',
    firstName: 'VIRGINIA',
    lastName: 'SALZEDO',
    fileName: 'il-pane-quotidiano.jpg',
  },
  {
    id: 'JVT3twI8JkPpvwuBX5CQI',
    contestId: 'uw-2018',
    categoryId: 'storyboard',
    userEmail: 'gabriella.luongo@yahoo.it',
    title: 'Storyboard',
    description: '',
    result: 'second',
    firstName: 'GABRIELLA',
    lastName: 'LUONGO',
    fileName: 'storyboard.jpg',
  },
  {
    id: 'L0sVwlcNsvCumgfFsftqA',
    contestId: 'uw-2018',
    categoryId: 'storyboard',
    userEmail: '',
    title: 'Yin e Yang',
    description: '',
    result: 'third',
    firstName: 'EMANUELE',
    lastName: 'VITALE',
    fileName: 'yin-e-yang.jpg',
  },
];
