export interface MigrationSubmission {
  id: string;
  contestId: string;
  categoryId: string;
  userEmail: string;
  title: string;
  description: string;
  result: string;
  firstName: string;
  lastName: string;
  fileName: string;
}

export const submissions: MigrationSubmission[] = [
  {
    id: 'hPSLlD-Y0wAO8n5pqs_5I',
    contestId: 'uw-2017',
    categoryId: 'compact',
    userEmail: 'davide.clementelli@gmail.com',
    title: 'Fly of the queen',
    description: '',
    result: 'first',
    firstName: 'DAVIDE',
    lastName: 'CLEMENTELLI',
    fileName: 'fly-of-the-queen.jpg',
  },
  {
    id: 'IZ20izNQrEGNS5WnyCKt1',
    contestId: 'uw-2017',
    categoryId: 'compact',
    userEmail: 'stefano.cerb@libero.it',
    title: 'Elvis',
    description: '',
    result: 'second',
    firstName: 'STEFANO',
    lastName: 'CERBAI',
    fileName: 'elvis.jpg',
  },
  {
    id: '0AYEntN5A62R59hJpn4if',
    contestId: 'uw-2017',
    categoryId: 'compact',
    userEmail: '',
    title: 'Bursatella',
    description: '',
    result: 'third',
    firstName: 'GIACOMO',
    lastName: 'GIOVANNINI',
    fileName: 'bursatella.jpg',
  },
  {
    id: 'eVhD7QJEAe6Mhyx1tdFcl',
    contestId: 'uw-2017',
    categoryId: 'compact',
    userEmail: '',
    title: 'The swarm',
    description: '',
    result: 'runner-up',
    firstName: 'ENRICO',
    lastName: 'SOMOGYI',
    fileName: 'the-swarm.jpg',
  },
  {
    id: 'ypaWGPXzZYNdKg6N8dYWb',
    contestId: 'uw-2017',
    categoryId: 'compact',
    userEmail: '',
    title: 'Shark smile',
    description: '',
    result: 'runner-up',
    firstName: 'FRANCESCO',
    lastName: 'BAZZOTTI',
    fileName: 'shark-smile.jpg',
  },
  {
    id: 'l5dGPgE06FIASYWN8cl5S',
    contestId: 'uw-2017',
    categoryId: 'compact',
    userEmail: '',
    title: 'Missione su Marte',
    description: '',
    result: 'runner-up',
    firstName: 'EDOARDO',
    lastName: 'ERRANI',
    fileName: 'missione-su-marte.jpg',
  },
  {
    id: '8MtYErWj1Xu6KBYerR7lr',
    contestId: 'uw-2017',
    categoryId: 'wide-angle',
    userEmail: 'pbau63@libero.it',
    title: 'L\'albero della vita',
    description: '',
    result: 'first',
    firstName: 'PAOLO',
    lastName: 'BAUSANI',
    fileName: 'lalbero-della-vita.jpg',
  },
  {
    id: 'jqTi5oebum-19zHJ30TC7',
    contestId: 'uw-2017',
    categoryId: 'wide-angle',
    userEmail: 'gabriella.luongo@yahoo.it',
    title: 'Mi stai guardando',
    description: '',
    result: 'second',
    firstName: 'GABRIELLA',
    lastName: 'LUONGO',
    fileName: 'mi-stai-guardando.jpg',
  },
  {
    id: 'DfUjkVbK9n1yoOiuGiPWu',
    contestId: 'uw-2017',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Non era una chimera',
    description: '',
    result: 'third',
    firstName: 'DOMENICO',
    lastName: 'ROSCIGNO',
    fileName: 'non-era-una-chimera.jpg',
  },
  {
    id: '3vrOQkkwFDWaSYuxuOR5v',
    contestId: 'uw-2017',
    categoryId: 'wide-angle',
    userEmail: 'info@maxgiorgetta.it',
    title: 'Cocco mirror',
    description: '',
    result: 'runner-up',
    firstName: 'MASSIMO',
    lastName: 'GIORGETTA',
    fileName: 'cocco-mirror.jpg',
  },
  {
    id: 'uJ-ijcCXcwGfh6aU9qwjx',
    contestId: 'uw-2017',
    categoryId: 'wide-angle',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Acqua dolce',
    description: '',
    result: 'runner-up',
    firstName: 'FRANCESCO',
    lastName: 'VISINTIN',
    fileName: 'acqua-dolce.jpg',
  },
  {
    id: 'U6rNF2btKAHgOIk8oEIhC',
    contestId: 'uw-2017',
    categoryId: 'wide-angle',
    userEmail: 'zanninimassimo@yahoo.it',
    title: 'Riflessi',
    description: '',
    result: 'runner-up',
    firstName: 'MASSIMO',
    lastName: 'ZANNINI',
    fileName: 'riflessi.jpg',
  },
  {
    id: 'GeY0GBryJc8QguS5XhRoI',
    contestId: 'uw-2017',
    categoryId: 'molluscs',
    userEmail: 'gabriella.luongo@yahoo.it',
    title: 'In un cielo trapunto di stelle',
    description: '',
    result: 'first',
    firstName: 'GABRIELLA',
    lastName: 'LUONGO',
    fileName: 'in-un-cielo-trapunto-di-stelle.jpg',
  },
  {
    id: 'GZqDRQMpZkvTxj1_IlJgq',
    contestId: 'uw-2017',
    categoryId: 'molluscs',
    userEmail: 'pbau63@libero.it',
    title: 'Monolocale',
    description: '',
    result: 'second',
    firstName: 'PAOLO',
    lastName: 'BAUSANI',
    fileName: 'monolocale.jpg',
  },
  {
    id: '0Wiv9brEuay9HP6PtlAVY',
    contestId: 'uw-2017',
    categoryId: 'molluscs',
    userEmail: '',
    title: 'Decollo Mediterraneo',
    description: '',
    result: 'third',
    firstName: 'DOMENICO',
    lastName: 'ROSCIGNO',
    fileName: 'decollo-mediterraneo.jpg',
  },
  {
    id: 'zS5frlKh-QqqpFQz25Fgt',
    contestId: 'uw-2017',
    categoryId: 'molluscs',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Tritone',
    description: '',
    result: 'runner-up',
    firstName: 'FRANCESCO',
    lastName: 'VISINTIN',
    fileName: 'tritone.jpg',
  },
  {
    id: '8oqYC9arnbML9tUrL212H',
    contestId: 'uw-2017',
    categoryId: 'molluscs',
    userEmail: 'raffaelelivornese@alice.it',
    title: 'Occhi dolci',
    description: '',
    result: 'runner-up',
    firstName: 'RAFFAELE',
    lastName: 'LIVORNESE',
    fileName: 'occhi-dolci.jpg',
  },
  {
    id: 'gn_NXO_6lW6HI1nxTfOfS',
    contestId: 'uw-2017',
    categoryId: 'molluscs',
    userEmail: 'mauapule@tin.it',
    title: 'A bocca aperta',
    description: '',
    result: 'runner-up',
    firstName: 'MAURO',
    lastName: 'APULEO',
    fileName: 'a-bocca-aperta.jpg',
  },
  {
    id: 'x0hoHg3ICabXfMbJQA-kr',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'margar68@gmail.com',
    title: 'Variazioni cromatiche in beige - San Pietro',
    description: '',
    result: 'first',
    firstName: 'MARCO',
    lastName: 'GARGIULO',
    fileName: 'variazioni-cromatiche-in-beige-san-pietro.jpg',
  },
  {
    id: 'FfeJNLInnA2Ct7qeqUpYy',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'margar68@gmail.com',
    title: 'Variazioni cromatiche in beige - The mask',
    description: '',
    result: 'first',
    firstName: 'MARCO',
    lastName: 'GARGIULO',
    fileName: 'variazioni-cromatiche-in-beige-the-mask.jpg',
  },
  {
    id: 'jrFaS9HB-zgsIVFEVZueJ',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'margar68@gmail.com',
    title: 'Variazioni cromatiche in beige - Jelly & Vesuvio',
    description: '',
    result: 'first',
    firstName: 'MARCO',
    lastName: 'GARGIULO',
    fileName: 'variazioni-cromatiche-in-beige-jelly-vesuvio.jpg',
  },
  {
    id: 'szbdu1ybReysMtSWSFkbS',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'nicholas.samaras@me.com',
    title: 'Swirl of the fish',
    description: '',
    result: 'second',
    firstName: 'NICHOLAS',
    lastName: 'SAMARAS',
    fileName: 'swirl-of-the-fish.jpg',
  },
  {
    id: '3eFF9BK3DsjrDpbXGY5zk',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'nicholas.samaras@me.com',
    title: 'Pink Heart',
    description: '',
    result: 'second',
    firstName: 'NICHOLAS',
    lastName: 'SAMARAS',
    fileName: 'pink-heart.jpg',
  },
  {
    id: 'Koufj_WRW4CYrdzCFZMOT',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'nicholas.samaras@me.com',
    title: 'Fragile Elegance',
    description: '',
    result: 'second',
    firstName: 'NICHOLAS',
    lastName: 'SAMARAS',
    fileName: 'fragile-elegance.jpg',
  },
  {
    id: 'TWfYjpAcS2PbUgD5UTflM',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'The mask',
    description: '',
    result: 'third',
    firstName: 'SALVATORE',
    lastName: 'IANNIELLO',
    fileName: 'the-mask.jpg',
  },
  {
    id: 'i9GcVtsySfmkTglromet6',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Double stress',
    description: '',
    result: 'third',
    firstName: 'SALVATORE',
    lastName: 'IANNIELLO',
    fileName: 'double-stress.jpg',
  },
  {
    id: 'Sbi9Hf3eHN_1-XdMIFKPP',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Octopus mammutt',
    description: '',
    result: 'third',
    firstName: 'SALVATORE',
    lastName: 'IANNIELLO',
    fileName: 'octopus-mammutt.jpg',
  },
  {
    id: 'zcUJU8kmOU83MKltXtt8_',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'lombrosod@gmail.com',
    title: 'Phatos',
    description: '',
    result: 'runner-up',
    firstName: 'DAVIDE',
    lastName: 'LOMBROSO',
    fileName: 'phatos.jpg',
  },
  {
    id: 'YyKLO0PsFTcwBrnifFyHf',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'lombrosod@gmail.com',
    title: 'Effetti speciali',
    description: '',
    result: 'runner-up',
    firstName: 'DAVIDE',
    lastName: 'LOMBROSO',
    fileName: 'effetti-speciali.jpg',
  },
  {
    id: '8HM8jMGjY_j4v9jx3p8j_',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'lombrosod@gmail.com',
    title: 'L\'attimo fuggente',
    description: '',
    result: 'runner-up',
    firstName: 'DAVIDE',
    lastName: 'LOMBROSO',
    fileName: 'lattimo-fuggente.jpg',
  },
  {
    id: 'C5P48A4Ya9ePHqqL25i2t',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Barracuda portrait',
    description: '',
    result: 'runner-up',
    firstName: 'DOMENICO',
    lastName: 'ROSCIGNO',
    fileName: 'barracuda-portrait.jpg',
  },
  {
    id: '6d1zsPf9yIFKch1grRgmd',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Classico Mediterraneo',
    description: '',
    result: 'runner-up',
    firstName: 'DOMENICO',
    lastName: 'ROSCIGNO',
    fileName: 'classico-mediterraneo.jpg',
  },
  {
    id: 'h0RnnRsKytXh7vSOFGFZp',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Gattopardi',
    description: '',
    result: 'runner-up',
    firstName: 'DOMENICO',
    lastName: 'ROSCIGNO',
    fileName: 'gattopardi.jpg',
  },
  {
    id: '1BVBGYS3YdacGjRxVCho4',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'claudiozori@claudiozori.it',
    title: 'Cannabina axinella',
    description: '',
    result: 'runner-up',
    firstName: 'CLAUDIO',
    lastName: 'ZORI',
    fileName: 'cannabina-axinella.jpg',
  },
  {
    id: 'uoALdoyJpF_8lVBVedUmI',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'claudiozori@claudiozori.it',
    title: 'Riflessi',
    description: '',
    result: 'runner-up',
    firstName: 'CLAUDIO',
    lastName: 'ZORI',
    fileName: 'riflessi.jpg',
  },
  {
    id: 'wLXSIEh9q3jrZV3NtvFdd',
    contestId: 'uw-2017',
    categoryId: 'mediterranean',
    userEmail: 'claudiozori@claudiozori.it',
    title: 'A bocca aperta',
    description: '',
    result: 'runner-up',
    firstName: 'CLAUDIO',
    lastName: 'ZORI',
    fileName: 'a-bocca-aperta.jpg',
  },
  {
    id: 'EqhGxVZtl0Ep-l4kcWdpp',
    contestId: 'uw-2017',
    categoryId: 'the-sea',
    userEmail: '',
    title: 'Shark whisperer',
    description: '',
    result: 'first',
    firstName: 'FAN',
    lastName: 'PING',
    fileName: 'shark-whisperer.jpg',
  },
  {
    id: 'tOh1Rs5chSGGgNodiBlnW',
    contestId: 'uw-2017',
    categoryId: 'the-sea',
    userEmail: '',
    title: 'Pescatore al sabbione',
    description: '',
    result: 'second',
    firstName: 'FLAVIO',
    lastName: 'VAILATI',
    fileName: 'pescatore-al-sabbione.jpg',
  },
  {
    id: '1Fm9fCdPLxTGftpJGXYxd',
    contestId: 'uw-2017',
    categoryId: 'the-sea',
    userEmail: '',
    title: 'Mattanza',
    description: '',
    result: 'third',
    firstName: 'ALESSIO',
    lastName: 'VIORA',
    fileName: 'mattanza.jpg',
  },
  {
    id: 'p4BPp6WGWGGpxBIC4iTU7',
    contestId: 'uw-2017',
    categoryId: 'dan-europe-photography-security',
    userEmail: 'stefano.cerb@libero.it',
    title: 'In coppia',
    description: '',
    result: 'first',
    firstName: 'STEFANO',
    lastName: 'CERBAI',
    fileName: 'in-coppia.jpg',
  },
  {
    id: '-XQXBepZJeUZupXzVzlCt',
    contestId: 'uw-2017',
    categoryId: 'dan-europe-photography-security',
    userEmail: '',
    title: 'Forever',
    description: '',
    result: 'second',
    firstName: 'EMANUELE',
    lastName: 'VITALE',
    fileName: 'forever.jpg',
  },
  {
    id: 'bzENyoG-lVEmoSVP56AFC',
    contestId: 'uw-2017',
    categoryId: 'dan-europe-photography-security',
    userEmail: '',
    title: 'Unknown Title',
    description: '',
    result: 'third',
    firstName: 'UNKNOWN',
    lastName: 'PHOTOGRAPHER',
    fileName: 'unknown-title.jpg',
  },
  {
    id: 'vIhtB9oxmmO3dAeEcQ4mt',
    contestId: 'uw-2017',
    categoryId: 'giovanni-smorti-award',
    userEmail: 'lombrosod@gmail.com',
    title: 'L\'attimo fuggente',
    description: '',
    result: 'first',
    firstName: 'DAVIDE',
    lastName: 'LOMBROSO',
    fileName: 'lattimo-fuggente.jpg',
  }
];
