export const submissions = [
  {
    id: '3H-BlySO0TMarMRhuPCda',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: 'galice.g.hoarau@nord.no',
    title: 'Sharks',
    description: '',
    result: 'first',
    firstName: 'Hoarau',
    lastName: 'Galice',
    fileName: 'sharks.jpg',
  },
  {
    id: 'oJgaX65FmJo39kMLm6dDq',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: 'luc.rooman@telenet.be',
    title: 'Turtle',
    description: '',
    result: 'second',
    firstName: 'Luc',
    lastName: 'Rooman',
    fileName: 'turtle.jpg',
  },
  {
    id: 'HQrP1Kgpybm1OZuhTVmJf',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Carousel',
    description: '',
    result: 'third',
    firstName: 'Francesco',
    lastName: 'Visintin',
    fileName: 'carousel.jpg',
  },
  {
    id: '4zsBxE5hpxDq8l39Axhwr',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: 'raffaelelivornese@alice.it',
    title: 'Danza della natura',
    description: '',
    result: 'runner-up',
    firstName: 'Raffaele',
    lastName: 'Livornese',
    fileName: 'danza-della-natura.jpg',
  },
  {
    id: 'HZMyS5zQIdJRhHRZJQoY0',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: 'stefano.cerb@libero.it',
    title: 'Gray Seal',
    description: '',
    result: 'runner-up',
    firstName: 'Stefano',
    lastName: 'Cerbai',
    fileName: 'gray-seal.jpg',
  },
  {
    id: 'xgEwnMalPRWU5KedSyJ7W',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Grey nurse cruising along',
    description: '',
    result: 'runner-up',
    firstName: 'Lena',
    lastName: 'Remy',
    fileName: 'grey-nurse-cruising-along.jpg',
  },
  {
    id: 'VJDHLAK6pJHXOkp3R-32Q',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Mating toads in the sun',
    description: '',
    result: 'runner-up',
    firstName: 'Gino',
    lastName: 'Symus',
    fileName: 'mating-toads-in-the-sun.jpg',
  },
  {
    id: 'JyIHjiGZVHV2bvw5-Deok',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Pike between waterlines',
    description: '',
    result: 'runner-up',
    firstName: 'Gino',
    lastName: 'Symus',
    fileName: 'pike-between-waterlines.jpg',
  },
  {
    id: '1ocmMiY9WmMAAnORYbgsD',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Shark',
    description: '',
    result: 'runner-up',
    firstName: 'Alessandro',
    lastName: 'Pagano',
    fileName: 'shark.jpg',
  },
  {
    id: 'VIijqw9C_NHG3_SpNL3wc',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Delfini',
    description: '',
    result: 'runner-up',
    firstName: 'Alessandro',
    lastName: 'Grasso',
    fileName: 'delfini.jpg',
  },
  {
    id: 'L9kW2mX8vYpQ3nR7sT1uC',
    contestId: 'uw-2019',
    categoryId: 'macro',
    userEmail: 'pbau63@libero.it',
    title: 'Fluido mortale',
    description: '',
    result: 'first',
    firstName: 'Paolo',
    lastName: 'Bausani',
    fileName: 'fluido-mortale.jpg',
  },
  {
    id: 'M3pK9qR5tU8wV2nX7sA1B',
    contestId: 'uw-2019',
    categoryId: 'macro',
    userEmail: 'galice.g.hoarau@nord.no',
    title: 'Jack and Kelly',
    description: '',
    result: 'second',
    firstName: 'Hoarau',
    lastName: 'Galice',
    fileName: 'jack-and-kelly.jpg',
  },
  {
    id: 'N7dF2hY9pL6mK3rT8uQ5W',
    contestId: 'uw-2019',
    categoryId: 'macro',
    userEmail: '',
    title: 'Blue Angler',
    description: '',
    result: 'third',
    firstName: 'Marco',
    lastName: 'Steiner',
    fileName: 'blue-angler.jpg',
  },
  {
    id: 'P8kQ3rT5uV9wX2nY7sB1C',
    contestId: 'uw-2019',
    categoryId: 'macro',
    userEmail: 'stefano.cerb@libero.it',
    title: 'Illuminato',
    description: '',
    result: 'runner-up',
    firstName: 'Stefano',
    lastName: 'Cerbai',
    fileName: 'illuminato.jpg',
  },
  {
    id: 'Q9mS4tU6vW0xY3nZ8sC2D',
    contestId: 'uw-2019',
    categoryId: 'macro',
    userEmail: 'margar68@gmail.com',
    title: 'Zeus',
    description: '',
    result: 'runner-up',
    firstName: 'Marco',
    lastName: 'Gargiulo',
    fileName: 'zeus2.jpg',
  },
  {
    id: 'R1nT5uW7xZ0yA4oB9sD3E',
    contestId: 'uw-2019',
    categoryId: 'macro',
    userEmail: '',
    title: 'Neighbours',
    description: '',
    result: 'runner-up',
    firstName: 'Enrico',
    lastName: 'Simogyi',
    fileName: 'neighbours.jpg',
  },
  {
    id: 'S2oU6vY8zA1yB5pC0sE4F',
    contestId: 'uw-2019',
    categoryId: 'macro',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Punk boy',
    description: '',
    result: 'runner-up',
    firstName: 'Francesco',
    lastName: 'Visintin',
    fileName: 'punk-boy.jpg',
  },
  {
    id: 'T3pV7wZ9aB2yC6qD1sF5G',
    contestId: 'uw-2019',
    categoryId: 'macro',
    userEmail: '',
    title: 'Seahorse',
    description: '',
    result: 'runner-up',
    firstName: 'Fabio',
    lastName: 'Strazzi',
    fileName: 'seahorse.jpg',
  },
  {
    id: 'U4qW8xA0bC3yD7rE2sG6H',
    contestId: 'uw-2019',
    categoryId: 'macro',
    userEmail: '',
    title: 'Ospite inatteso',
    description: '',
    result: 'runner-up',
    firstName: 'Stefano',
    lastName: 'Proakis',
    fileName: 'ospite-inatteso.jpg',
  },
  {
    id: 'V5rX9yB1cD4zE8sF3tH7I',
    contestId: 'uw-2019',
    categoryId: 'macro',
    userEmail: '',
    title: 'San Pietrino affamato',
    description: '',
    result: 'runner-up',
    firstName: 'Giacomo',
    lastName: 'Giovannini',
    fileName: 'sanpietrino-affamato.jpg',
  },
  {
    id: 'Z1cV3wS5lP0oE8sF3tH7I',
    contestId: 'uw-2019',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Solar Reflection',
    description: '',
    result: 'first',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: 'solar-reflection.jpg',
  },
  {
    id: 'W6sY0zC2dE5aF9tG4uI8J',
    contestId: 'uw-2019',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'For protection',
    description: '',
    result: 'first',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: 'for-protection.jpg',
  },
  {
    id: 'X7tZ1aD3eF6bG0uH5vJ9K',
    contestId: 'uw-2019',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Yellow capture',
    description: '',
    result: 'first',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: 'yellow-capture.jpg',
  },
  {
    id: 'Y8uA2bE4fG7cH1vI6wK0L',
    contestId: 'uw-2019',
    categoryId: 'mediterranean',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Portfolio 1 3',
    description: '',
    result: 'second',
    firstName: 'Francesco',
    lastName: 'Visintin',
    fileName: 'portfolio-1-3.jpg',
  },
  {
    id: 'Z9vB3cF5gH8dI2wJ7xL1M',
    contestId: 'uw-2019',
    categoryId: 'mediterranean',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Portfolio 2 3',
    description: '',
    result: 'second',
    firstName: 'Francesco',
    lastName: 'Visintin',
    fileName: 'portfolio-2-3.jpg',
  },
  {
    id: 'A0wC4dG6hI9eJ3xK8yM2N',
    contestId: 'uw-2019',
    categoryId: 'mediterranean',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Portfolio 3 3',
    description: '',
    result: 'second',
    firstName: 'Francesco',
    lastName: 'Visintin',
    fileName: 'portfolio-3-3.jpg',
  },
  {
    id: 'B1xD5eH7iJ0fK4yL9zN3O',
    contestId: 'uw-2019',
    categoryId: 'mediterranean',
    userEmail: 'alessandro-grasso@libero.it',
    title: 'Cromatismi Mediterranei',
    description: '',
    result: 'third',
    firstName: 'Alessandro',
    lastName: 'Grasso',
    fileName: 'cromatismi-mediterranei-1.jpg',
  },
  {
    id: 'C2yE6fI8jK1gL5zM0aN4P',
    contestId: 'uw-2019',
    categoryId: 'mediterranean',
    userEmail: 'alessandro-grasso@libero.it',
    title: 'Cromatismi Mediterranei',
    description: '',
    result: 'third',
    firstName: 'Alessandro',
    lastName: 'Grasso',
    fileName: 'cromatismi-mediterranei-2.jpg',
  },
  {
    id: 'D3zF7gJ9kL2hM6aN1bO5Q',
    contestId: 'uw-2019',
    categoryId: 'mediterranean',
    userEmail: 'alessandro-grasso@libero.it',
    title: 'Cromatismi Mediterranei',
    description: '',
    result: 'third',
    firstName: 'Alessandro',
    lastName: 'Grasso',
    fileName: 'cromatismi-mediterranei-3.jpg',
  },
  {
    id: 'E4aG8hK0lM3iN7bO2cP6R',
    contestId: 'uw-2019',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'The Hunter',
    description: '',
    result: 'runner-up',
    firstName: 'Pasquale',
    lastName: 'Vassallo',
    fileName: 'the-hunter.jpg',
  },
  {
    id: 'F5bH9iL1mN4jO8cP3dQ7S',
    contestId: 'uw-2019',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'The Queen',
    description: '',
    result: 'runner-up',
    firstName: 'Pasquale',
    lastName: 'Vassallo',
    fileName: 'the-queen.jpg',
  },
  {
    id: 'G6cI0jM2nO5kP9dQ4eR8T',
    contestId: 'uw-2019',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'The Hunter',
    description: '',
    result: 'runner-up',
    firstName: 'Pasquale',
    lastName: 'Vassallo',
    fileName: 'the-hunter-2.jpg',
  },
  {
    id: 'H7dJ1kN3oP6lQ0eR5fS9U',
    contestId: 'uw-2019',
    categoryId: 'mediterranean',
    userEmail: 'nicholas.samaras@me.com',
    title: 'Hippocampus Hippocampus',
    description: '',
    result: 'runner-up',
    firstName: 'Nicholas',
    lastName: 'Samaras',
    fileName: 'hippocampus-hippocampus.jpg',
  },
];
