export interface MigrationSubmission {
  id: string;
  contestId: string;
  categoryId: string;
  userEmail: string;
  title: string;
  description: string;
  result: string;
  firstName: string;
  lastName: string;
  fileName: string;
}

export const submissions: MigrationSubmission[] = [
  {
    id: 'oBHY-HSjxfv9Roi0z_fIF',
    contestId: 'uw-2015',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'Parende Padden',
    description: '',
    result: 'first',
    firstName: 'Rooman',
    lastName: 'Luc',
    fileName: '2015-parende-padden.jpg',
  },
  {
    id: 'gZucoWJlfoZzem669kFFg',
    contestId: 'uw-2015',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'Ephemeroptera Larvae',
    description: '',
    result: 'second',
    firstName: 'Maurizio',
    lastName: 'Pasi',
    fileName: '2015-ephemeroptera-larvae.jpg',
  },
  {
    id: 'nJYmtsrEkhVE-NB7OmX7X',
    contestId: 'uw-2015',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'Oilà',
    description: '',
    result: 'third',
    firstName: 'Virginia',
    lastName: 'Salzedo',
    fileName: '2015-oila.jpg',
  },
  {
    id: 'j5kgR2h7ho7YUsCDO6EYK',
    contestId: 'uw-2015',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'Salamander Larvae',
    description: '',
    result: 'runner-up',
    firstName: 'Maurizio',
    lastName: 'Pasi',
    fileName: '2015-salamander-larvae.jpg',
  },
  {
    id: '3ppnHqqDBBPA02fpRYs80',
    contestId: 'uw-2015',
    categoryId: 'fresh-waters',
    userEmail: '',
    title: 'Meerval',
    description: '',
    result: 'runner-up',
    firstName: 'Rooman',
    lastName: 'Luc',
    fileName: '2015-meerval.jpg',
  },
  {
    id: 'KwNtsm-WFNOK7fJwRXiWD',
    contestId: 'uw-2015',
    categoryId: 'fresh-waters',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Il Guardiano Del Lago',
    description: '',
    result: 'runner-up',
    firstName: 'Francesco',
    lastName: 'Visintin',
    fileName: '2015-il-guardiano-del-lago.jpg',
  },
  {
    id: 'jJf9k8LGczICdVbrUrfo5',
    contestId: 'uw-2015',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Face to Face',
    description: '',
    result: 'first',
    firstName: 'Davide',
    lastName: 'Lopresti',
    fileName: '2015-face-to-face.jpg',
  },
  {
    id: 'TqA8Rczao0vpiGKGyzERt',
    contestId: 'uw-2015',
    categoryId: 'wide-angle',
    userEmail: 'raffaelelivornese@alice.it',
    title: 'Dal Profondo Degli Abissi',
    description: '',
    result: 'second',
    firstName: 'Raffaele',
    lastName: 'Livornese',
    fileName: '2015-dal-profondo-degli-abissi.jpg',
  },
  {
    id: 'IUTBDLaTAYixfXjZktLTh',
    contestId: 'uw-2015',
    categoryId: 'wide-angle',
    userEmail: '',
    title: "Danza Dell'amore",
    description: '',
    result: 'third',
    firstName: 'Domenico',
    lastName: 'Roscigno',
    fileName: '2015-danza-dellamore.jpg',
  },
  {
    id: 'iIz-hBBiTX0EBJW-0DN_b',
    contestId: 'uw-2015',
    categoryId: 'wide-angle',
    userEmail: 'margar68@gmail.com',
    title: 'Pesce San Pietro',
    description: '',
    result: 'runner-up',
    firstName: 'Marco',
    lastName: 'Gargiulo',
    fileName: '2015-pesce-san-pietro.jpg',
  },
  {
    id: 'fjkogCnKW_RBgZ01efRQn',
    contestId: 'uw-2015',
    categoryId: 'wide-angle',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'The Passenger',
    description: '',
    result: 'runner-up',
    firstName: 'Francesco',
    lastName: 'Visintin',
    fileName: '2015-the-passenger.jpg',
  },
  {
    id: 'Yp-NXDMJYYxkp7atuy7pF',
    contestId: 'uw-2015',
    categoryId: 'wide-angle',
    userEmail: 'claudiozori@claudiozori.it',
    title: 'Alla Scoperta Del Mondo',
    description: '',
    result: 'runner-up',
    firstName: 'Claudio',
    lastName: 'Zori',
    fileName: '2015-alla-scoperta-del-mondo.jpg',
  },
  {
    id: 'AE0Vz2aEMcrXBm2O7iViU',
    contestId: 'uw-2015',
    categoryId: 'macro',
    userEmail: '',
    title: 'Nascita',
    description: '',
    result: 'first',
    firstName: 'Elio',
    lastName: 'Nicosia',
    fileName: '2015-nascita.jpg',
  },
  {
    id: 'lvmh-M5sDgNArIX5BPjzg',
    contestId: 'uw-2015',
    categoryId: 'macro',
    userEmail: 'claudiozori@claudiozori.it',
    title: 'Riflessi',
    description: '',
    result: 'second',
    firstName: 'Claudio',
    lastName: 'Zori',
    fileName: '2015-riflessi.jpg',
  },
  {
    id: 'YqEXyTuTENq5xTxP4qCw1',
    contestId: 'uw-2015',
    categoryId: 'macro',
    userEmail: 'pbau63@libero.it',
    title: 'Stazione Di Pulizia',
    description: '',
    result: 'third',
    firstName: 'Paolo',
    lastName: 'Bausani',
    fileName: '2015-stazione-di-pulizia.jpg',
  },
  {
    id: 'nfw6fWhJewIJ5Hxdj6kZC',
    contestId: 'uw-2015',
    categoryId: 'macro',
    userEmail: '',
    title: 'Spotlight',
    description: '',
    result: 'runner-up',
    firstName: 'Matteo',
    lastName: 'Visconti',
    fileName: '2015-spotlight.jpg',
  },
  {
    id: 'zZZh6yHPhVvsXl7nwHvCI',
    contestId: 'uw-2015',
    categoryId: 'macro',
    userEmail: '',
    title: 'Mysterious Light',
    description: '',
    result: 'runner-up',
    firstName: 'Beth',
    lastName: 'Watson',
    fileName: '2015-mysterious-light.jpg',
  },
  {
    id: 'WbxcdDL6OS8QKSD76_8kD',
    contestId: 'uw-2015',
    categoryId: 'macro',
    userEmail: '',
    title: 'The Hijacker',
    description: '',
    result: 'runner-up',
    firstName: 'Nicholaus',
    lastName: 'Samaras',
    fileName: '2015-the-hijacker.jpg',
  },
  {
    id: 'MgxlSvbmn60E-53r9Vb12',
    contestId: 'uw-2015',
    categoryId: 'macro',
    userEmail: '',
    title: 'Eggs of the Sea',
    description: '',
    result: 'runner-up',
    firstName: 'Lorenzo',
    lastName: 'Terraneo',
    fileName: '2015-eggs-of-the-sea.jpg',
  },
  {
    id: 'd7ejT5v58mMmhrg3CIDQl',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Un Po Nervoso',
    description: '',
    result: 'first',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: '2015-un-po-nervoso.jpg',
  },
  {
    id: '87hemlSVp-AU6JCaEBgZB',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'San Ippocampo',
    description: '',
    result: 'first',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: '2015-san-ippocampo.jpg',
  },
  {
    id: 'RvNvRJJhbgtiYQNf7gNlO',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Doppia Sfortuna',
    description: '',
    result: 'first',
    firstName: 'Salvatore',
    lastName: 'Ianniello',
    fileName: '2015-doppia-sfortuna.jpg',
  },
  {
    id: '0QP15S5wPrBBY2QJP_RMM',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'The Satellite',
    description: '',
    result: 'second',
    firstName: 'Francesco',
    lastName: 'Visintin',
    fileName: '2015-the-satellite.jpg',
  },
  {
    id: 'NMMuWIYhMtBx2M-P7B013',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Pipefish',
    description: '',
    result: 'second',
    firstName: 'Francesco',
    lastName: 'Visintin',
    fileName: '2015-pipefish.jpg',
  },
  {
    id: 'brFAwJIK_J7P2hrJpNTFk',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Life on the Edge',
    description: '',
    result: 'second',
    firstName: 'Francesco',
    lastName: 'Visintin',
    fileName: '2015-life-on-the-edge.jpg',
  },
  {
    id: 'REAoFMXf5Jo3494I9pXMh',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Portfolio 1',
    description: '',
    result: 'third',
    firstName: 'Davide',
    lastName: 'Lopresti',
    fileName: '2015-portfolio-1.jpg',
  },
  {
    id: 'eXB6EYrzHLWt_mM9RKMLQ',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Portfolio 2',
    description: '',
    result: 'third',
    firstName: 'Davide',
    lastName: 'Lopresti',
    fileName: '2015-portfolio-2.jpg',
  },
  {
    id: 'OJrSBkvEHc3HcsgtCncQ9',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Portfolio 3',
    description: '',
    result: 'third',
    firstName: 'Davide',
    lastName: 'Lopresti',
    fileName: '2015-portfolio-3.jpg',
  },
  {
    id: 'NXbeRZfuKeAKv99c6PVi_',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Convivenza',
    description: '',
    result: 'runner-up',
    firstName: 'Domenico',
    lastName: 'Roscigno',
    fileName: '2015-convivenza.jpg',
  },
  {
    id: 'z5_XYR_InQWdE4pahXj8s',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Femmine !',
    description: '',
    result: 'runner-up',
    firstName: 'Domenico',
    lastName: 'Roscigno',
    fileName: '2015-femmine.jpg',
  },
  {
    id: 'KPkYujjqskt4BKLc4eDdW',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Coppia Di Fatto',
    description: '',
    result: 'runner-up',
    firstName: 'Domenico',
    lastName: 'Roscigno',
    fileName: '2015-coppia-di-fatto.jpg',
  },
  {
    id: 'arJkcCR4h83VYDJdgwzqI',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'Il Golfo',
    description: '',
    result: 'runner-up',
    firstName: 'Pasquale',
    lastName: 'Vassallo',
    fileName: '2015-il-golfo.jpg',
  },
  {
    id: 'NjFK8SJPxMWo_0gKAyceP',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: 'The Boss',
    description: '',
    result: 'runner-up',
    firstName: 'Pasquale',
    lastName: 'Vassallo',
    fileName: '2015-the-boss.jpg',
  },
  {
    id: 'aU_tWM_6bShz7KKCBwj_Y',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: '',
    title: "L'ospite",
    description: '',
    result: 'runner-up',
    firstName: 'Pasquale',
    lastName: 'Vassallo',
    fileName: '2015-lospite.jpg',
  },
  {
    id: 'KJJ96SVXIv7DfCkTwxNT_',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: 'buzzichelli@virgilio.it',
    title: 'Eye',
    description: '',
    result: 'runner-up',
    firstName: 'Alessandro',
    lastName: 'Buzzichelli',
    fileName: '2015-eye.jpg',
  },
  {
    id: 'ebq-dhdAek9Gs04tp8dpB',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: 'buzzichelli@virgilio.it',
    title: 'Hippocampus',
    description: '',
    result: 'runner-up',
    firstName: 'Alessandro',
    lastName: 'Buzzichelli',
    fileName: '2015-hippocampus.jpg',
  },
  {
    id: 'gmI0NDRYNKoh2dy_RCq_d',
    contestId: 'uw-2015',
    categoryId: 'mediterranean',
    userEmail: 'buzzichelli@virgilio.it',
    title: 'Parazoanhus',
    description: '',
    result: 'runner-up',
    firstName: 'Alessandro',
    lastName: 'Buzzichelli',
    fileName: '2015-parazoanhus.jpg',
  },
  {
    id: 'NP1i9F1VfoZ4KNygC_LKr',
    contestId: 'uw-2015',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Cavalluccio Su Spirografo',
    description: '',
    result: 'first',
    firstName: 'Angelo',
    lastName: 'Pascale',
    fileName: '2015-cavalluccio-su-spirografo.jpg',
  },
  {
    id: 'nypAYToq-7qxEEUnVjTWB',
    contestId: 'uw-2015',
    categoryId: 'newcomers',
    userEmail: 'albyx@icloud.com',
    title: 'Life in a Crane',
    description: '',
    result: 'second',
    firstName: 'Alberto',
    lastName: 'Buonanno',
    fileName: '2015-life-in-a-crane.jpg',
  },
  {
    id: 'Z2hc4wpWd0ka63cCygV1v',
    contestId: 'uw-2015',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Amici',
    description: '',
    result: 'third',
    firstName: 'Daniele',
    lastName: 'Maggi',
    fileName: '2015-amici.jpg',
  },
  {
    id: 'Tcb48J6nmpTDpDZni8ZhH',
    contestId: 'uw-2015',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Boxeur',
    description: '',
    result: 'runner-up',
    firstName: 'Giancarlo',
    lastName: 'Zambelli',
    fileName: '2015-boxeur.jpg',
  },
  {
    id: 'SuMVWJmN3N7_9Ei-DrJWv',
    contestId: 'uw-2015',
    categoryId: 'newcomers',
    userEmail: 'gabriella.luongo@yahoo.it',
    title: 'Harlequin Shrimp',
    description: '',
    result: 'runner-up',
    firstName: 'Gabriella',
    lastName: 'Luongo',
    fileName: '2015-harlequin-shrimp.jpg',
  },
  {
    id: 'IcSWrxAB_hQTv4kEZFJZl',
    contestId: 'uw-2015',
    categoryId: 'newcomers',
    userEmail: '',
    title: 'Twins',
    description: '',
    result: 'runner-up',
    firstName: 'Kevin',
    lastName: 'Bergamini',
    fileName: '2015-twins.jpg',
  },
  {
    id: 'iVMRgheK1DHYJkbq_ADrK',
    contestId: 'uw-2015',
    categoryId: 'dan-europe',
    userEmail: '',
    title: 'Diego E La Boa Sparabile',
    description: '',
    result: 'first',
    firstName: 'Virginia',
    lastName: 'Salzedo',
    fileName: '2015-diego-e-la-boa-sparabile.jpg',
  },
  {
    id: 'ES2EJ2OdM2s65A-UZLtAP',
    contestId: 'uw-2015',
    categoryId: 'dan-europe',
    userEmail: '',
    title: 'Unione',
    description: '',
    result: 'second',
    firstName: 'Vito',
    lastName: 'Giannecchini',
    fileName: '2015-unione.jpg',
  },
  {
    id: 'vQgppTgiAk19ODPBNKfTy',
    contestId: 'uw-2015',
    categoryId: 'dan-europe',
    userEmail: '',
    title: 'Sistema Di Coppia a Prescindere',
    description: '',
    result: 'third',
    firstName: 'Lorenzo',
    lastName: 'Terraneo',
    fileName: '2015-sistema-di-coppia-a-prescindere.jpg',
  },
  {
    id: '4m2I4AwY1OE8pF40IBjvC',
    contestId: 'uw-2015',
    categoryId: 'dan-europe',
    userEmail: '',
    title: 'Decompressione',
    description: '',
    result: 'runner-up',
    firstName: 'Alberto',
    lastName: 'Gallucci',
    fileName: '2015-decompressione.jpg',
  },
  {
    id: 'cerFO0usFkhc5dcpZyXdo',
    contestId: 'uw-2015',
    categoryId: 'dan-europe',
    userEmail: 'fabriziopompilio@gmail.com',
    title: 'La Coppia',
    description: '',
    result: 'runner-up',
    firstName: 'Fabrizio',
    lastName: 'Pompilio',
    fileName: '2015-la-coppia.jpg',
  },
  {
    id: 'hQ_SrmSw0N8kze69eZN9R',
    contestId: 'uw-2015',
    categoryId: 'dan-europe',
    userEmail: '',
    title: 'Segnalazione',
    description: '',
    result: 'runner-up',
    firstName: 'Lorenzo',
    lastName: 'Terraneo',
    fileName: '2015-segnalazione.jpg',
  },
];
