export const submissions = [
  {
    id: '3H-BlySO0TMarMRhuPCda',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: 'galice.g.hoarau@nord.no',
    title: 'Sharks',
    description: '',
    result: 'first',
    firstName: 'Hoarau',
    lastName: 'Galice',
    fileName: 'sharks.jpg',
  },
  {
    id: 'oJgaX65FmJo39kMLm6dDq',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: 'luc.rooman@telenet.be',
    title: 'Turtle',
    description: '',
    result: 'second',
    firstName: 'Luc',
    lastName: 'Rooman',
    fileName: 'turtle.jpg',
  },
  {
    id: 'HQrP1Kgpybm1OZuhTVmJf',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: 'francesco.visntin@gmail.com',
    title: 'Carousel',
    description: '',
    result: 'third',
    firstName: 'Francesco',
    lastName: 'Visintin',
    fileName: 'carousel.jpg',
  },
  {
    id: '4zsBxE5hpxDq8l39Axhwr',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: 'raffaelelivornese@alice.it',
    title: 'Danza della natura',
    description: '',
    result: 'runner-up',
    firstName: 'Raffaele',
    lastName: 'Livornese',
    fileName: 'danza-della-natura.jpg',
  },
  {
    id: 'HZMyS5zQIdJRhHRZJQoY0',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: 'stefano.cerb@libero.it',
    title: 'Gray Seal',
    description: '',
    result: 'runner-up',
    firstName: 'Stefano',
    lastName: 'Cerbai',
    fileName: 'gray-seal.jpg',
  },
  {
    id: 'xgEwnMalPRWU5KedSyJ7W',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Grey nurse cruising along',
    description: '',
    result: 'runner-up',
    firstName: 'Lena',
    lastName: 'Remy',
    fileName: 'grey-nurse-cruising-along.jpg',
  },
  {
    id: 'VJDHLAK6pJHXOkp3R-32Q',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Mating toads in the sun',
    description: '',
    result: 'runner-up',
    firstName: 'Gino',
    lastName: 'Symus',
    fileName: 'mating-toads-in-the-sun.jpg',
  },
  {
    id: 'JyIHjiGZVHV2bvw5-Deok',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Pike between waterlines',
    description: '',
    result: 'runner-up',
    firstName: 'Gino',
    lastName: 'Symus',
    fileName: 'pike-between-waterlines.jpg',
  },
  {
    id: '1ocmMiY9WmMAAnORYbgsD',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Shark',
    description: '',
    result: 'runner-up',
    firstName: 'Alessandro',
    lastName: 'Pagano',
    fileName: 'shark.jpg',
  },
  {
    id: 'VIijqw9C_NHG3_SpNL3wc',
    contestId: 'uw-2019',
    categoryId: 'wide-angle',
    userEmail: '',
    title: 'Delfini',
    description: '',
    result: 'runner-up',
    firstName: 'Alessandro',
    lastName: 'Grasso',
    fileName: 'delfini.jpg',
  },
];
