/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserSubmissionsRouteImport } from './routes/user/submissions'
import { Route as UserLoginRouteImport } from './routes/user/login'
import { Route as AdminCreateRouteImport } from './routes/admin/create'
import { Route as AdminContestsRouteImport } from './routes/admin/contests'
import { Route as AdminContestIdSubmissionsRouteImport } from './routes/admin/$contestId.submissions'
import { Route as AdminContestIdResultsRouteImport } from './routes/admin/$contestId.results'

const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSubmissionsRoute = UserSubmissionsRouteImport.update({
  id: '/user/submissions',
  path: '/user/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLoginRoute = UserLoginRouteImport.update({
  id: '/user/login',
  path: '/user/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateRoute = AdminCreateRouteImport.update({
  id: '/admin/create',
  path: '/admin/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContestsRoute = AdminContestsRouteImport.update({
  id: '/admin/contests',
  path: '/admin/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContestIdSubmissionsRoute =
  AdminContestIdSubmissionsRouteImport.update({
    id: '/admin/$contestId/submissions',
    path: '/admin/$contestId/submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContestIdResultsRoute = AdminContestIdResultsRouteImport.update({
  id: '/admin/$contestId/results',
  path: '/admin/$contestId/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin/contests': typeof AdminContestsRoute
  '/admin/create': typeof AdminCreateRoute
  '/user/login': typeof UserLoginRoute
  '/user/submissions': typeof UserSubmissionsRoute
  '/admin': typeof AdminIndexRoute
  '/user': typeof UserIndexRoute
  '/admin/$contestId/results': typeof AdminContestIdResultsRoute
  '/admin/$contestId/submissions': typeof AdminContestIdSubmissionsRoute
}
export interface FileRoutesByTo {
  '/admin/contests': typeof AdminContestsRoute
  '/admin/create': typeof AdminCreateRoute
  '/user/login': typeof UserLoginRoute
  '/user/submissions': typeof UserSubmissionsRoute
  '/admin': typeof AdminIndexRoute
  '/user': typeof UserIndexRoute
  '/admin/$contestId/results': typeof AdminContestIdResultsRoute
  '/admin/$contestId/submissions': typeof AdminContestIdSubmissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin/contests': typeof AdminContestsRoute
  '/admin/create': typeof AdminCreateRoute
  '/user/login': typeof UserLoginRoute
  '/user/submissions': typeof UserSubmissionsRoute
  '/admin/': typeof AdminIndexRoute
  '/user/': typeof UserIndexRoute
  '/admin/$contestId/results': typeof AdminContestIdResultsRoute
  '/admin/$contestId/submissions': typeof AdminContestIdSubmissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin/contests'
    | '/admin/create'
    | '/user/login'
    | '/user/submissions'
    | '/admin'
    | '/user'
    | '/admin/$contestId/results'
    | '/admin/$contestId/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/contests'
    | '/admin/create'
    | '/user/login'
    | '/user/submissions'
    | '/admin'
    | '/user'
    | '/admin/$contestId/results'
    | '/admin/$contestId/submissions'
  id:
    | '__root__'
    | '/admin/contests'
    | '/admin/create'
    | '/user/login'
    | '/user/submissions'
    | '/admin/'
    | '/user/'
    | '/admin/$contestId/results'
    | '/admin/$contestId/submissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminContestsRoute: typeof AdminContestsRoute
  AdminCreateRoute: typeof AdminCreateRoute
  UserLoginRoute: typeof UserLoginRoute
  UserSubmissionsRoute: typeof UserSubmissionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  UserIndexRoute: typeof UserIndexRoute
  AdminContestIdResultsRoute: typeof AdminContestIdResultsRoute
  AdminContestIdSubmissionsRoute: typeof AdminContestIdSubmissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/submissions': {
      id: '/user/submissions'
      path: '/user/submissions'
      fullPath: '/user/submissions'
      preLoaderRoute: typeof UserSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/login': {
      id: '/user/login'
      path: '/user/login'
      fullPath: '/user/login'
      preLoaderRoute: typeof UserLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create': {
      id: '/admin/create'
      path: '/admin/create'
      fullPath: '/admin/create'
      preLoaderRoute: typeof AdminCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contests': {
      id: '/admin/contests'
      path: '/admin/contests'
      fullPath: '/admin/contests'
      preLoaderRoute: typeof AdminContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$contestId/submissions': {
      id: '/admin/$contestId/submissions'
      path: '/admin/$contestId/submissions'
      fullPath: '/admin/$contestId/submissions'
      preLoaderRoute: typeof AdminContestIdSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$contestId/results': {
      id: '/admin/$contestId/results'
      path: '/admin/$contestId/results'
      fullPath: '/admin/$contestId/results'
      preLoaderRoute: typeof AdminContestIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AdminContestsRoute: AdminContestsRoute,
  AdminCreateRoute: AdminCreateRoute,
  UserLoginRoute: UserLoginRoute,
  UserSubmissionsRoute: UserSubmissionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  UserIndexRoute: UserIndexRoute,
  AdminContestIdResultsRoute: AdminContestIdResultsRoute,
  AdminContestIdSubmissionsRoute: AdminContestIdSubmissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
