// Auto-generated by scripts/export-past-contests.ts
// Do not edit manually

// Newest contest with judges. Its own module so client bundles can link to the
// judges page without pulling in the whole past-contests.ts dataset.
export const latestJudgesContestId = 'uw-2026';
